// html-react/src/pages/article/ArticleList.tsx
import { useState } from 'react'
import { App, Space, Switch, Table } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { useTranslation } from 'react-i18next'
import { deleteArticle, getArticleList, updateArticle } from '@/api/article'
import { useListPage } from '@/hooks/useListPage'
import { handlePaginatedTableChange } from '@/utils/tableChange'
import { useCrudActions } from '@/hooks/useCrudActions'
import { usePermission } from '@/hooks/usePermission'
import { useUnhandledError } from '@/hooks/useUnhandledError'
import PageContainer from '@/components/PageContainer'
import SearchForm from '@/components/SearchForm'
import PermissionButton from '@/components/PermissionButton'
import logger from '@/utils/logger'
import { extractTextFromMarkdown } from '@/utils/markdown'
import ArticleFormModal from './ArticleFormModal'
import { articleInitialSearchForm, getAdminDisplayName, transformArticleRow, type ArticleRow } from './article.config'

export default function ArticleList() {
  const { t } = useTranslation()
  const { message } = App.useApp()
  const showError = useUnhandledError()
  const { getButtonState } = usePermission()
  const [open, setOpen] = useState(false)
  const [editId, setEditId] = useState<string | number | null>(null)

  const {
    tableData,
    loading,
    pagination,
    searchForm,
    onSearchFormChange,
    loadData,
    handleSearch,
    handleReset,
    handleSortChange,
    refresh,
  } = useListPage<ArticleRow>({
    fetchApi: getArticleList,
    initialSearchForm: articleInitialSearchForm,
    normalizeRows: false,
    transformData: (row) => transformArticleRow(row),
  })

  const { toolbar, confirmDelete } = useCrudActions({
    createPermission: 'article.store',
    onRefresh: refresh,
    onCreate: () => {
      setEditId(null)
      setOpen(true)
    },
    deleteApi: deleteArticle,
  })

  const handleStatusChange = async (row: ArticleRow, checked: boolean) => {
    try {
      await updateArticle(row.id, { status: checked ? 1 : 0 })
      message.success(t('common.update_success'))
      await refresh()
    } catch (error) {
      logger.error('Status change error:', error)
      showError(error, t('common.operation_failed'))
    }
  }

  const columns: ColumnsType<ArticleRow> = [
    { title: t('table.id'), dataIndex: 'id', width: 80, sorter: true },
    {
      title: t('admin_id'),
      dataIndex: 'admin_id',
      width: 140,
      render: (_, row) => getAdminDisplayName(row),
    },
    { title: t('title'), dataIndex: 'title', ellipsis: true },
    {
      title: t('content'),
      dataIndex: 'content',
      ellipsis: true,
      render: (content: string) => extractTextFromMarkdown(content).slice(0, 120),
    },
    {
      title: t('common.status'),
      dataIndex: 'status',
      width: 100,
      render: (status: number, row) => (
        <Switch
          checked={Number(status ?? 1) === 1}
          disabled={getButtonState('article.update').disabled}
          onChange={(checked) => void handleStatusChange(row, checked)}
        />
      ),
    },
    { title: t('table.updated_at'), dataIndex: 'updated_at', width: 180, sorter: true },
    { title: t('table.created_at'), dataIndex: 'created_at', width: 180, sorter: true },
    {
      title: t('common.operation'),
      key: 'operation',
      width: 160,
      fixed: 'right',
      render: (_, row) => (
        <Space>
          {getButtonState('article.update').show && (
            <PermissionButton
              permission="article.update"
              type="link"
              onClick={() => {
                setEditId(row.id)
                setOpen(true)
              }}
            >
              {t('common.edit')}
            </PermissionButton>
          )}
          {getButtonState('article.destroy').show && (
            <PermissionButton
              permission="article.destroy"
              type="link"
              danger
              onClick={() => confirmDelete(row.id, row.title)}
            >
              {t('common.delete')}
            </PermissionButton>
          )}
        </Space>
      ),
    },
  ]

  return (
    <PageContainer title={t('menu.article')} extra={toolbar}>
      <SearchForm
        fields={[
          { name: 'admin_id', label: t('admin_id') },
          { name: 'title', label: t('title') },
          { name: 'content', label: t('content'), advanced: true },
          {
            name: 'status',
            label: t('common.status'),
            type: 'select',
            advanced: true,
            options: [
              { label: t('common.enabled'), value: 1 },
              { label: t('common.disabled'), value: 0 },
            ],
          },
        ]}
        values={searchForm}
        onChange={onSearchFormChange}
        onSearch={handleSearch}
        onReset={handleReset}
      />
      <Table<ArticleRow>
        rowKey="id"
        loading={loading}
        columns={columns}
        dataSource={tableData}
        scroll={{ x: 1200 }}
        pagination={{
          current: pagination.page,
          pageSize: pagination.pageSize,
          total: pagination.total,
          showSizeChanger: true,
          showTotal: (total) => t('common.total', { total }),
        }}
        onChange={(pager, _f, sorter) =>
          handlePaginatedTableChange({ pager, sorter, pagination, loadData, handleSortChange })
        }
      />
      <ArticleFormModal
        open={open}
        editId={editId}
        onClose={() => setOpen(false)}
        onSuccess={() => void refresh()}
      />
    </PageContainer>
  )
}

// html/src/views/article/ArticleList.vue
<template>
  <div class="article-list">
    <el-card>
      <template #header>
        <div class="card-header">
          <span>{{ $t("menu.article") }}</span>

          <el-button
            type="primary"
            :disabled="getButtonState('article.store').disabled"
            @click="handleAdd"
          >
            <el-icon><PlusIcon /></el-icon>
            {{ $t("common.add") }}
          </el-button>
        </div>
      </template>

      <SearchForm
        :model="searchForm"
        :fields="searchFields"
        :initial-values="initialSearchForm"
        i18n-prefix="article"
        @search="handleSearch"
        @reset="handleReset"
      >
      </SearchForm>

      <VxeTable
        ref="tableRef"
        :data="tableData"
        :loading="loading"
        :columns="tableColumns"
        :height="600"
        @sort-change="handleSortChange"
      >
        <template #admin_id="{ row }">
          {{ getadminDisplayName(row.admin || row.admin_id) }}
        </template>
        <template #operation="{ row }">
          <TableActionButtons
            :row="row"
            :primary-actions="getPrimaryActions(row)"
            :more-actions="getMoreActions(row)"
            :get-button-state="getButtonState"
            @action="handleAction"
          />
        </template>
      </VxeTable>

      <Pagination
        v-model="pagination"
        :auto-load="true"
        :on-page-change="loadData"
      />
    </el-card>

    <ArticleForm
      ref="formRef"
      v-model="dialogVisible"
      :edit-id="editId"
      @success="handleFormSuccess"
    />
  </div>
</template>

<script setup>
import { ref, reactive, onMounted, computed, markRaw } from "vue";
import { useI18n } from "vue-i18n";

import { ElMessage, ElMessageBox } from "element-plus";
import { Plus } from "@element-plus/icons-vue";
import SearchForm from "../../components/SearchForm.vue";
import Pagination from "../../components/Pagination.vue";
import VxeTable from "../../components/VxeTable.vue";
import TableActionButtons from "../../components/TableActionButtons.vue";
import ArticleForm from "./ArticleForm.vue";
import { useListPage } from "../../composables/useListPage";
import { usePermission } from "../../composables/usePermission";
import { useCrud } from "../../composables/useCrud";

import {
  getArticleList,
  deleteArticle,
  updateArticle,
} from "../../api/article";
import logger from "../../utils/logger";
import ErrorHandler from "../../utils/errorHandler";

const PlusIcon = markRaw(Plus);

// 权限控制
const { getButtonState } = usePermission();

const { t } = useI18n();

const tableRef = ref(null);
const formRef = ref(null);

const {
  dialogVisible,
  editId,
  handleAdd,
  handleClose,
  handleDelete: handleDeleteCrud,
} = useCrud({
  deleteApi: deleteArticle,
});

const initialSearchForm = {
  admin_id: "",
  title: "",
  content: "",
  status: "",
};

const {
  pagination,
  tableData,
  loading,
  searchForm,
  loadData,
  handleSearch,
  handleReset,
  handleSortChange,
  initDefaultSort,
} = useListPage({
  fetchApi: getArticleList,
  initialSearchForm,
  fieldMapping: {},
  defaultSort: "id:desc",
  tableRef: computed(() => tableRef.value?.tableRef),
});

const searchFields = computed(() => [
  {
    prop: "admin_id",
    label: t("article.admin_id"),
    type: "input",
    clearable: true,
    width: "200px",
    advanced: false,
  },
  {
    prop: "title",
    label: t("article.title"),
    type: "input",
    clearable: true,
    width: "200px",
    advanced: false,
  },
  {
    prop: "content",
    label: t("article.content"),
    type: "input",
    clearable: true,
    width: "200px",
    advanced: false,
  },
  {
    prop: "status",
    label: t("article.status"),
    type: "select",
    clearable: true,
    apiUrl: "/options?type=dictionary&dictionary_type=status",
    width: "200px",
    advanced: false,
  },
]);

const tableColumns = computed(() => [
  {
    field: "id",
    title: t("table.id"),
    width: 80,
    sortable: true,
  },
  {
    field: "admin_id",
    title: t("article.admin_id"),
    slot: "admin_id",
    sortable: false,
  },
  {
    field: "title",
    title: t("article.title"),
    sortable: false,
  },
  {
    field: "content",
    title: t("article.content"),
    sortable: false,
  },
  {
    field: "status",
    title: t("article.status"),
    sortable: false,
  },
  {
    field: "created_at",
    title: t("table.created_at"),
    width: 180,
    sortable: true,
  },
  {
    field: "operation",
    title: t("table.operation"),
    width: 220,
    fixed: "right",
    slot: "operation",
  },
]);

const getadminDisplayName = (admin_id) => {
  if (!admin_id) return "-";
  return admin_id.nickname || admin_id.admin || "-";
};

const handleEdit = (row) => {
  editId.value = row.id;
  dialogVisible.value = true;
};

const handleDelete = (row) => handleDeleteCrud(row, loadData);

const handleFormSuccess = () => {
  handleClose();
  loadData();
};

// 获取主要操作按钮配置
const getPrimaryActions = (row) => {
  return [
    {
      key: "edit",
      label: t("common.edit"),
      type: "primary",
      permission: "article.update",
      handler: handleEdit,
    },
    {
      key: "delete",
      label: t("common.delete"),
      type: "danger",
      permission: "article.destroy",
      handler: handleDelete,
    },
  ];
};

// 获取更多操作按钮配置（可根据需要扩展）
const getMoreActions = (row) => {
  return [];
};

// 处理操作事件
const handleAction = (command, row) => {
  switch (command) {
    case "edit":
      handleEdit(row);
      break;
    case "delete":
      handleDelete(row);
      break;
  }
};

onMounted(async () => {
  try {
    initDefaultSort();
    await loadData();
  } catch (error) {
    logger.error("ListPage onMounted error:", error);
    ErrorHandler.handle(error);
  }
});
</script>

<style scoped>
.article-list {
}
</style>
