// html-react/src/pages/user/UserList.tsx
import { useState } from 'react'
import { App, Button, Dropdown, Form, Input, InputNumber, Modal, Radio, Select, Space, Switch, Table } from 'antd'
import type { ColumnsType, TablePaginationConfig } from 'antd/es/table'
import type { MenuProps } from 'antd'
import { DownOutlined, SettingOutlined } from '@ant-design/icons'
import { useNavigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import {
  createUser,
  deleteUser,
  exportUsers,
  getUserDetail,
  getUserList,
  resetUserPassword,
  updateBalance,
  updateUser,
} from '@/api/user'
import { useListPage } from '@/hooks/useListPage'
import { useCrudActions } from '@/hooks/useCrudActions'
import { usePermission } from '@/hooks/usePermission'
import { useUnhandledError } from '@/hooks/useUnhandledError'
import { useColumnSetting } from '@/hooks/useColumnSetting'
import PageContainer from '@/components/PageContainer'
import ColumnSettingDialog from '@/components/ColumnSettingDialog'
import SearchForm from '@/components/SearchForm'
import PermissionButton from '@/components/PermissionButton'
import { entityField } from '@/utils/normalize'

interface UserRow {
  id: number | string
  username: string
  nickname?: string
  email?: string
  phone?: string
  status?: number
  balance?: number | string
  currency?: string
  created_at?: string
  name?: string
}

function formatBalance(balance: number | string | undefined, currency?: string) {
  const amount = Number(balance || 0).toFixed(2)
  return currency ? `${amount} ${currency}` : amount
}

export default function UserList() {
  const { t } = useTranslation()
  const navigate = useNavigate()
  const { message, modal } = App.useApp()
  const showError = useUnhandledError()
  const { getButtonState } = usePermission()
  const [form] = Form.useForm()
  const [pwdForm] = Form.useForm()
  const [balanceForm] = Form.useForm()
  const [formOpen, setFormOpen] = useState(false)
  const [editId, setEditId] = useState<string | number | null>(null)
  const [submitting, setSubmitting] = useState(false)
  const [loadingDetail, setLoadingDetail] = useState(false)
  const [exporting, setExporting] = useState(false)
  const [balanceOpen, setBalanceOpen] = useState(false)
  const [balanceUser, setBalanceUser] = useState<UserRow | null>(null)

  const {
    tableData,
    loading,
    pagination,
    searchForm,
    setSearchForm,
    loadData,
    handleSearch,
    handleReset,
    handleSortChange,
    refresh,
  } = useListPage<UserRow, Record<string, unknown>>({
    fetchApi: getUserList as never,
    initialSearchForm: { username: '', status: '' },
    defaultSort: 'id:desc',
    normalizeRows: true,
    transformData: (row) => {
      const record = row as unknown as Record<string, unknown>
      return {
        id: entityField(record, 'id', '')!,
        username: String(entityField(record, 'username', '') ?? ''),
        nickname: String(entityField(record, 'nickname', '') ?? ''),
        email: String(entityField(record, 'email', '') ?? ''),
        phone: String(entityField(record, 'phone', '') ?? ''),
        status: Number(entityField(record, 'status', 0) ?? 0),
        balance: (entityField(record, 'balance', 0) as number | string) ?? 0,
        currency: String(entityField(record, 'currency', '') ?? ''),
        created_at: String(entityField(record, 'created_at', '') ?? ''),
        name: String(entityField(record, 'username', '') ?? ''),
      }
    },
  })

  const { toolbar, confirmDelete } = useCrudActions({
    createPermission: 'user.store',
    onRefresh: refresh,
    onCreate: () => {
      setEditId(null)
      form.setFieldsValue({
        username: '',
        password: '',
        nickname: '',
        email: '',
        phone: '',
        status: 1,
      })
      setFormOpen(true)
    },
    deleteApi: deleteUser,
  })

  const openEdit = async (row: UserRow) => {
    setEditId(row.id)
    setFormOpen(true)
    setLoadingDetail(true)
    try {
      const res = await getUserDetail(row.id)
      const data = (res.data || {}) as Record<string, unknown>
      form.setFieldsValue({
        username: entityField(data, 'username', ''),
        nickname: entityField(data, 'nickname', ''),
        email: entityField(data, 'email', ''),
        phone: entityField(data, 'phone', ''),
        status: Number(entityField(data, 'status', 1)),
      })
    } catch (error) {
      showError(error, t('common.query_failed'))
    } finally {
      setLoadingDetail(false)
    }
  }

  const handleStatusChange = async (row: UserRow, checked: boolean) => {
    try {
      await updateUser(row.id, { status: checked ? 1 : 0 })
      message.success(t('common.update_success'))
      await refresh()
    } catch (error) {
      showError(error, t('common.operation_failed'))
    }
  }

  const handleResetPassword = (row: UserRow) => {
    pwdForm.resetFields()
    modal.confirm({
      title: t('user.reset_password'),
      content: (
        <Form form={pwdForm} layout="vertical" style={{ marginTop: 16 }}>
          <Form.Item
            name="password"
            label={t('user.new_password')}
            rules={[
              { required: true },
              { min: 6, message: t('user.password_min_length') },
            ]}
          >
            <Input.Password />
          </Form.Item>
        </Form>
      ),
      onOk: async () => {
        const values = await pwdForm.validateFields()
        try {
          await resetUserPassword(row.id, { password: values.password })
          message.success(t('user.reset_password_success'))
        } catch (error) {
          showError(error, t('common.operation_failed'))
          throw error
        }
      },
    })
  }

  const openBalance = (row: UserRow) => {
    setBalanceUser(row)
    balanceForm.setFieldsValue({ amount: undefined, type: 'income' })
    setBalanceOpen(true)
  }

  const handleBalanceOk = async () => {
    if (!balanceUser) return
    try {
      const values = await balanceForm.validateFields()
      const amount = Math.abs(Number(values.amount))
      if (!amount) {
        message.error(t('user.amount_cannot_be_zero'))
        return
      }
      await updateBalance(balanceUser.id, {
        amount,
        type: values.type,
        source: 'manual',
        description: t('user.manual_balance_adjustment'),
      })
      message.success(t('user.balance_update_success'))
      setBalanceOpen(false)
      await refresh()
    } catch (error) {
      if ((error as { errorFields?: unknown })?.errorFields) return
      showError(error, t('common.operation_failed'))
    }
  }

  const handleExport = async () => {
    setExporting(true)
    try {
      await exportUsers({ ...searchForm, order_by: 'id:desc' })
      message.success(t('common.queued'))
    } catch (error) {
      showError(error, t('common.operation_failed'))
    } finally {
      setExporting(false)
    }
  }

  const handleSubmit = async () => {
    try {
      const values = await form.validateFields()
      setSubmitting(true)
      const payload = { ...values, status: Number(values.status) }
      if (editId) {
        delete payload.password
        await updateUser(editId, payload)
        message.success(t('common.update_success'))
      } else {
        await createUser(payload)
        message.success(t('common.create_success'))
      }
      setFormOpen(false)
      await refresh()
    } catch (error) {
      if ((error as { errorFields?: unknown })?.errorFields) return
      showError(error, t('common.operation_failed'))
    } finally {
      setSubmitting(false)
    }
  }

  const moreMenu = (row: UserRow): MenuProps['items'] =>
    [
      getButtonState('user.password').show
        ? {
            key: 'resetPassword',
            label: t('user.reset_password'),
            onClick: () => handleResetPassword(row),
          }
        : null,
      getButtonState('user_balance_log.index').show
        ? {
            key: 'balanceLogs',
            label: t('user.balance_logs'),
            onClick: () => navigate(`/user-balance-logs?user_id=${row.id}`),
          }
        : null,
      getButtonState('user.destroy').show
        ? {
            key: 'delete',
            danger: true,
            label: t('common.delete'),
            onClick: () => confirmDelete(row.id, row.username),
          }
        : null,
    ].filter(Boolean) as MenuProps['items']

  const columns: ColumnsType<UserRow> = [
    { title: t('table.id'), dataIndex: 'id', width: 80, sorter: true },
    { title: t('table.username'), dataIndex: 'username' },
    { title: t('table.nickname'), dataIndex: 'nickname' },
    { title: t('table.email'), dataIndex: 'email' },
    { title: t('table.phone'), dataIndex: 'phone' },
    {
      title: t('table.balance'),
      dataIndex: 'balance',
      width: 140,
      render: (balance, row) => (
        <span style={{ color: 'var(--ant-color-primary)', fontWeight: 600 }}>
          {formatBalance(balance, row.currency)}
        </span>
      ),
    },
    {
      title: t('common.status'),
      dataIndex: 'status',
      width: 100,
      render: (status: number, row) => (
        <Switch
          checked={status === 1}
          disabled={getButtonState('user.update').disabled}
          onChange={(checked) => void handleStatusChange(row, checked)}
        />
      ),
    },
    { title: t('table.created_at'), dataIndex: 'created_at', width: 180, sorter: true },
    {
      title: t('common.operation'),
      key: 'operation',
      width: 220,
      fixed: 'right',
      render: (_, row) => (
        <Space>
          {getButtonState('user.update').show && (
            <PermissionButton permission="user.update" type="link" onClick={() => void openEdit(row)}>
              {t('common.edit')}
            </PermissionButton>
          )}
          {getButtonState('user.update_balance').show && (
            <PermissionButton permission="user.update_balance" type="link" onClick={() => openBalance(row)}>
              {t('user.update_balance')}
            </PermissionButton>
          )}
          <Dropdown menu={{ items: moreMenu(row) }}>
            <a onClick={(e) => e.preventDefault()}>
              {t('common.more')} <DownOutlined />
            </a>
          </Dropdown>
        </Space>
      ),
    },
  ]

  const {
    filteredColumns,
    open: columnSettingOpen,
    openColumnSetting,
    closeColumnSetting,
    allColumns,
    visibleColumns,
    columnOrder,
    fixedColumns,
    handleConfirm: handleColumnSettingConfirm,
  } = useColumnSetting('user', columns)

  return (
    <PageContainer
      title={t('menu.user')}
      extra={
        <Space>
          {toolbar}
          <PermissionButton permission="user.export" loading={exporting} onClick={() => void handleExport()}>
            {t('common.export')}
          </PermissionButton>
          <Button icon={<SettingOutlined />} onClick={openColumnSetting}>
            {t('common.column_setting')}
          </Button>
        </Space>
      }
    >
      <SearchForm
        fields={[
          { name: 'username', label: t('table.username') },
          {
            name: 'status',
            label: t('common.status'),
            type: 'select',
            options: [
              { label: t('common.enabled'), value: 1 },
              { label: t('common.disabled'), value: 0 },
            ],
          },
        ]}
        values={searchForm}
        onChange={(values) => setSearchForm(values as typeof searchForm)}
        onSearch={handleSearch}
        onReset={handleReset}
      />
      <Table<UserRow>
        rowKey="id"
        loading={loading}
        columns={filteredColumns}
        dataSource={tableData}
        scroll={{ x: 1200 }}
        pagination={{
          current: pagination.page,
          pageSize: pagination.pageSize,
          total: pagination.total,
          showSizeChanger: true,
          showTotal: (total) => t('common.total', { total }),
        }}
        onChange={(pager: TablePaginationConfig, _f, sorter) => {
          const sort = Array.isArray(sorter) ? sorter[0] : sorter
          const sortObj = sort as { field?: string; order?: 'ascend' | 'descend' | null; column?: unknown }
          if (sortObj?.column && sortObj.field) {
            handleSortChange(String(sortObj.field), sortObj.order)
            return
          }
          void loadData({
            currentPage: pager.current || 1,
            pageSize: pager.pageSize || pagination.pageSize,
          })
        }}
      />

      <Modal
        open={formOpen}
        title={editId ? t('user.edit') : t('user.add')}
        onCancel={() => setFormOpen(false)}
        onOk={() => void handleSubmit()}
        confirmLoading={submitting}
        destroyOnHidden
      >
        <Form form={form} layout="vertical" disabled={loadingDetail}>
          <Form.Item name="username" label={t('table.username')} rules={[{ required: true }]}>
            <Input disabled={!!editId} />
          </Form.Item>
          {!editId && (
            <Form.Item name="password" label={t('common.password')} rules={[{ required: true }, { min: 6 }]}>
              <Input.Password />
            </Form.Item>
          )}
          <Form.Item name="nickname" label={t('table.nickname')}>
            <Input />
          </Form.Item>
          <Form.Item name="email" label={t('table.email')}>
            <Input />
          </Form.Item>
          <Form.Item name="phone" label={t('table.phone')}>
            <Input />
          </Form.Item>
          <Form.Item name="status" label={t('common.status')}>
            <Radio.Group
              options={[
                { label: t('common.enabled'), value: 1 },
                { label: t('common.disabled'), value: 0 },
              ]}
            />
          </Form.Item>
        </Form>
      </Modal>

      <Modal
        open={balanceOpen}
        title={t('user.update_balance')}
        onCancel={() => setBalanceOpen(false)}
        onOk={() => void handleBalanceOk()}
        destroyOnHidden
      >
        <Form form={balanceForm} layout="vertical">
          <Form.Item label={t('table.username')}>
            <Input value={balanceUser?.username} disabled />
          </Form.Item>
          <Form.Item label={t('table.balance')}>
            <Input value={formatBalance(balanceUser?.balance, balanceUser?.currency)} disabled />
          </Form.Item>
          <Form.Item
            name="amount"
            label={t('user.amount')}
            rules={[{ required: true, message: t('user.amount_required') }]}
            extra={t('user.update_balance_prompt')}
          >
            <InputNumber style={{ width: '100%' }} min={0.01} precision={2} />
          </Form.Item>
          <Form.Item name="type" label={t('user.change_type')} rules={[{ required: true }]}>
            <Select
              options={[
                { label: t('user.balance_income'), value: 'income' },
                { label: t('user.balance_expense'), value: 'expense' },
                { label: t('user.balance_refund'), value: 'refund' },
              ]}
            />
          </Form.Item>
        </Form>
      </Modal>
      <ColumnSettingDialog
        open={columnSettingOpen}
        onClose={closeColumnSetting}
        allColumns={allColumns}
        visibleColumns={visibleColumns}
        columnOrder={columnOrder}
        fixedColumns={fixedColumns}
        onConfirm={handleColumnSettingConfirm}
      />
    </PageContainer>
  )
}

// html/src/views/user/UserList.vue
<template>
  <ListPage
    ref="listPageRef"
    page-class="user"
    :title="$t('menu.user')"
    :add-button-text="$t('user.add_user')"
    :add-button-disabled="getButtonState('user.store').disabled"
    :search-form="searchForm"
    :search-fields="searchFields"
    :initial-search-values="userInitialSearchForm"
    i18n-prefix="user"
    :table-data="tableData"
    :loading="loading"
    :table-columns="tableColumns"
    :table-key="`table-${tableColumns.length}`"
    :pagination="pagination"
    show-toolbar
    show-column-setting
    :visible-columns="visibleColumns"
    :all-columns="allColumns"
    :default-visible-columns="defaultVisibleColumns"
    :column-order="columnOrder"
    :fixed-columns="fixedColumns"
    :on-column-setting-confirm="handleColumnSettingConfirm"
    @add="handleAdd"
    @search="handleSearch"
    @reset="handleReset"
    @refresh="loadData"
    @page-change="loadData"
    @sort-change="handleSortChange"
  >
    <template #extra-buttons>
      <el-button
        type="success"
        :disabled="getButtonState('user.export').disabled || isExporting"
        :loading="isExporting"
        @click="handleExport"
      >
        <el-icon><Download /></el-icon>
        {{ $t('common.export') }}
      </el-button>
    </template>

    <template #status="{ row }">
      <el-switch
        :model-value="rowStatus(row) === 1"
        :disabled="getButtonState('user.update').disabled"
        @change="(val) => handleStatusChange(row, val)"
      />
    </template>

    <template #balance="{ row }">
      <span style="color: var(--el-color-primary); font-weight: bold;">
        {{ formatBalance(row.balance || 0, row.currency) }}
      </span>
    </template>

    <template #operation="{ row }">
      <TableActionButtons
        :row="row"
        :primary-actions="getPrimaryActions(row)"
        :more-actions="getMoreActions(row)"
        :get-button-state="getButtonState"
        @action="handleAction"
      />
    </template>

    <template #form>
      <UserForm
        ref="userFormRef"
        v-model="dialogVisible"
        :edit-id="editId"
        @success="handleFormSuccess"
      />
    </template>
  </ListPage>
</template>

<script setup>
import { ref, computed } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Download } from '@element-plus/icons-vue'
import ListPage from '@/components/ListPage.vue'
import TableActionButtons from '@/components/TableActionButtons.vue'
import UserForm from './UserForm.vue'
import { useStandardListPage } from '@/composables/useStandardListPage'
import { useColumnSetting } from '@/composables/useColumnSetting'
import { rowStatus } from '@/utils/listPageHelpers'
import { getStatusOptions } from '@/utils/fieldOptions'
import {
  getUserList,
  deleteUser,
  updateUser,
  resetPassword,
  updateBalance,
  exportUsers
} from '@/api/user'
import logger from '@/utils/logger'
import ErrorHandler from '@/utils/errorHandler'
import {
  userInitialSearchForm,
  createUserSearchFields,
  createUserTableColumns,
  formatBalance
} from './user.config'

const { t } = useI18n()
const router = useRouter()
const listPageRef = ref(null)
const userFormRef = ref(null)
const isExporting = ref(false)

const allTableColumns = computed(() => createUserTableColumns(t))

const {
  tableColumns,
  visibleColumns,
  allColumns,
  defaultVisibleColumns,
  columnOrder,
  fixedColumns,
  handleColumnSettingConfirm
} = useColumnSetting('user', allTableColumns)

const searchFields = computed(() => createUserSearchFields(t, getStatusOptions))

const {
  pagination,
  tableData,
  loading,
  searchForm,
  dialogVisible,
  editId,
  loadData,
  handleSearch,
  handleReset,
  handleSortChange,
  handleAdd,
  handleEdit,
  handleClose,
  handleDelete: handleDeleteRow,
  getButtonState
} = useStandardListPage({
  fetchApi: getUserList,
  initialSearchForm: userInitialSearchForm,
  defaultSort: 'id:desc',
  deleteApi: deleteUser,
  normalizeRows: false,
  tableRef: computed(() => listPageRef.value?.tableRef?.tableRef)
})

const getPrimaryActions = () => [
  { key: 'edit', label: t('common.edit'), permission: 'user.update' },
  { key: 'updateBalance', label: t('user.update_balance'), permission: 'user.update_balance', type: 'warning' }
]

const getMoreActions = () => [
  { key: 'resetPassword', command: 'resetPassword', label: t('user.reset_password'), permission: 'user.password' },
  { key: 'balanceLogs', command: 'balanceLogs', label: t('user.balance_logs'), permission: 'user_balance_log.index', divided: true },
  { key: 'delete', command: 'delete', label: t('common.delete'), permission: 'user.destroy', type: 'danger' }
]

const handleAction = async (command, row) => {
  switch (command) {
    case 'edit':
      handleEdit(row)
      break
    case 'updateBalance':
      await handleUpdateBalance(row)
      break
    case 'resetPassword':
      await handleResetPassword(row)
      break
    case 'balanceLogs':
      handleBalanceLogs(row)
      break
    case 'delete':
      await handleDelete(row)
      break
    default:
      logger.warn('Unknown action command:', command)
  }
}

const handleUpdateBalance = async (row) => {
  try {
    const { value: amountStr } = await ElMessageBox.prompt(
      t('user.update_balance_prompt'),
      t('user.update_balance'),
      {
        confirmButtonText: t('common.confirm'),
        cancelButtonText: t('common.cancel'),
        inputType: 'number',
        inputValidator: (value) => (!value || Number(value) === 0 ? t('user.amount_required') : true)
      }
    )

    const amount = Number(amountStr)
    if (amount === 0) {
      ElMessage.error(t('user.amount_cannot_be_zero'))
      return
    }

    const typeOptions = [
      { value: 'income', label: t('user.balance_income') },
      { value: 'expense', label: t('user.balance_expense') },
      { value: 'refund', label: t('user.balance_refund') }
    ]

    const { value: typeIndex } = await ElMessageBox.prompt(
      `${t('user.select_change_type_prompt')}\n\n${typeOptions.map((opt, idx) => `${idx + 1}. ${opt.label}`).join('\n')}`,
      t('user.select_change_type'),
      {
        confirmButtonText: t('common.confirm'),
        cancelButtonText: t('common.cancel'),
        inputType: 'number',
        inputPlaceholder: '1-3',
        inputValidator: (value) => {
          const num = Number(value)
          return !value || num < 1 || num > 3 ? t('user.invalid_selection') : true
        }
      }
    )

    const selectedIndex = Number(typeIndex) - 1
    if (selectedIndex < 0 || selectedIndex >= typeOptions.length) return

    await ElMessageBox.confirm(
      `${t('user.balance_update_confirm')}\n${t('user.amount')}: ${Math.abs(amount).toFixed(2)}\n${t('user.change_type')}: ${typeOptions[selectedIndex].label}`,
      t('common.confirm'),
      { type: 'warning' }
    )

    await updateBalance(row.id, {
      amount: Math.abs(amount),
      type: typeOptions[selectedIndex].value,
      source: 'manual',
      description: t('user.manual_balance_adjustment')
    })
    ElMessage.success(t('user.balance_update_success'))
    loadData()
  } catch (error) {
    if (error !== 'cancel' && error !== 'close') {
      ErrorHandler.handle(error)
    }
  }
}

const handleResetPassword = async (row) => {
  try {
    const { value: password } = await ElMessageBox.prompt(t('user.new_password'), t('user.reset_password'), {
      confirmButtonText: t('common.confirm'),
      cancelButtonText: t('common.cancel'),
      inputType: 'password',
      inputValidator: (value) => (!value || value.length < 6 ? t('user.password_min_length') : true)
    })
    await resetPassword(row.id, { password })
    ElMessage.success(t('user.reset_password_success'))
  } catch (error) {
    if (error !== 'cancel' && error !== 'close') {
      ErrorHandler.handle(error, { silent: true })
    }
  }
}

const handleBalanceLogs = (row) => {
  router.push({ path: '/user-balance-logs', query: { user_id: row.id } })
}

const handleDelete = async (row) => {
  await handleDeleteRow(row, loadData)
}

const handleStatusChange = async (row, val) => {
  try {
    await updateUser(row.id, { status: val ? 1 : 0 })
    ElMessage.success(t('common.update_success'))
    loadData()
  } catch (error) {
    ErrorHandler.handle(error)
  }
}

const handleFormSuccess = () => {
  handleClose()
  loadData()
}

const handleExport = async () => {
  if (isExporting.value) return
  isExporting.value = true
  try {
    const response = await exportUsers({ ...searchForm, order_by: 'id:desc' })
    const exportId = response.data?.data?.export_id || response.data?.export_id
    if (!exportId) {
      ElMessage.error(t('export.failed'))
      return
    }
    ElMessage.success(t('export.task_submitted'))
    router.push('/exports')
  } catch (error) {
    if (error.response?.status === 429) {
      ElMessage.warning(t('common.already_queued'))
    } else if (!error.__handled) {
      ErrorHandler.handle(error, { silent: true })
    }
  } finally {
    isExporting.value = false
  }
}
</script>
