// html/src/views/payment/PaymentList.vue
<template>
  <div class="list-page">
    <el-card>
      <template #header>
        <div class="card-header">
          <span>{{ $t('menu.payment') }}</span>
        </div>
      </template>

      <!-- 搜索表单 -->
      <SearchForm
        :model="searchForm"
        :fields="searchFields"
        :initial-values="initialSearchForm"
        i18n-prefix="payment"
        @search="handleSearch"
        @reset="handleReset"
      />

      <VxeTable
        ref="tableRef"
        :data="tableData"
        :loading="loading"
        :columns="tableColumns"
        :height="600"
        @sort-change="handleSortChange"
      >
        <template #status="{ row }">
          <el-tag
            :type="getStatusType(row.status || row.Status)"
            size="small"
          >
            {{ getStatusText(row.status || row.Status) }}
          </el-tag>
        </template>

        <template #payment_method="{ row }">
          {{ getPaymentMethodName(row.payment_method || row.PaymentMethod) }}
        </template>

        <template #amount="{ row }">
          {{ formatAmount(row.amount || row.Amount) }}
        </template>

        <template #operation="{ row }">
          <el-button
            type="primary"
            size="small"
            :disabled="getButtonState('payment.show').disabled"
            @click="handleView(row)"
          >
            {{ $t('common.view') }}
          </el-button>
        </template>
      </VxeTable>

      <Pagination
        v-model="pagination"
        :auto-load="true"
        :on-page-change="loadData"
      />
    </el-card>

    <!-- 详情对话框 -->
    <el-dialog
      v-model="detailDialogVisible"
      :title="$t('payment.payment_detail')"
      width="800px"
    >
      <div v-loading="detailLoading">
        <el-descriptions :column="2" border v-if="paymentDetail">
          <el-descriptions-item :label="$t('payment.payment_no')">
            {{ paymentDetail.payment_no || paymentDetail.PaymentNo }}
          </el-descriptions-item>
          <el-descriptions-item :label="$t('payment.order_no')">
            {{ paymentDetail.order_no || paymentDetail.OrderNo }}
          </el-descriptions-item>
          <el-descriptions-item :label="$t('payment.payment_method')">
            {{ getPaymentMethodName(paymentDetail.payment_method || paymentDetail.PaymentMethod) }}
          </el-descriptions-item>
          <el-descriptions-item :label="$t('payment.user_id')">
            {{ paymentDetail.user_id || paymentDetail.UserID }}
          </el-descriptions-item>
          <el-descriptions-item :label="$t('payment.amount')">
            {{ formatAmount(paymentDetail.amount || paymentDetail.Amount) }}
          </el-descriptions-item>
          <el-descriptions-item :label="$t('payment.status')">
            <el-tag
              :type="getStatusType(paymentDetail.status || paymentDetail.Status)"
              size="small"
            >
              {{ getStatusText(paymentDetail.status || paymentDetail.Status) }}
            </el-tag>
          </el-descriptions-item>
          <el-descriptions-item :label="$t('payment.third_party_no')">
            {{ paymentDetail.third_party_no || paymentDetail.ThirdPartyNo || '-' }}
          </el-descriptions-item>
          <el-descriptions-item :label="$t('payment.pay_time')">
            {{ paymentDetail.pay_time || paymentDetail.PayTime || '-' }}
          </el-descriptions-item>
          <el-descriptions-item :label="$t('payment.fail_reason')" :span="2" v-if="paymentDetail.fail_reason || paymentDetail.FailReason">
            {{ paymentDetail.fail_reason || paymentDetail.FailReason }}
          </el-descriptions-item>
          <el-descriptions-item :label="$t('payment.remark')" :span="2" v-if="paymentDetail.remark || paymentDetail.Remark">
            {{ paymentDetail.remark || paymentDetail.Remark }}
          </el-descriptions-item>
          <el-descriptions-item :label="$t('table.created_at')">
            {{ formatDateTime(paymentDetail.created_at || paymentDetail.CreatedAt) }}
          </el-descriptions-item>
          <el-descriptions-item :label="$t('table.updated_at')">
            {{ formatDateTime(paymentDetail.updated_at || paymentDetail.UpdatedAt) }}
          </el-descriptions-item>
        </el-descriptions>
      </div>
    </el-dialog>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { useI18n } from 'vue-i18n'
import { usePermission } from '../../composables/usePermission'
import { useListPage } from '../../composables/useListPage'
import SearchForm from '../../components/SearchForm.vue'
import Pagination from '../../components/Pagination.vue'
import VxeTable from '../../components/VxeTable.vue'
import { getPaymentList, getPaymentDetail } from '../../api/payment'
import logger from '../../utils/logger'
import ErrorHandler from '../../utils/errorHandler'
import { getSevenDaysAgo } from '../../utils/dateUtils'

// 权限控制
const { getButtonState } = usePermission()

const { t } = useI18n()
const tableRef = ref(null)
const detailDialogVisible = ref(false)
const detailLoading = ref(false)
const paymentDetail = ref(null)

const {
  pagination,
  tableData,
  loading,
  searchForm,
  loadData,
  handleSearch,
  handleReset,
  handleSortChange,
  initDefaultSort
} = useListPage({
  fetchApi: getPaymentList,
  initialSearchForm: {
    payment_no: '',
    order_no: '',
    payment_method_id: '',
    user_id: '',
    status: '',
    start_time: getSevenDaysAgo(),
    end_time: ''
  },
  fieldMapping: {},
  defaultSort: 'created_at:desc',
  tableRef: computed(() => tableRef.value?.tableRef)
})

// 初始搜索表单（开始时间默认为一周前）
const initialSearchForm = {
  payment_no: '',
  order_no: '',
  payment_method_id: '',
  user_id: '',
  status: '',
  start_time: getSevenDaysAgo(),
  end_time: ''
}

// 搜索字段配置
const searchFields = computed(() => [
  {
    prop: 'payment_no',
    type: 'input',
    placeholder: t('payment.payment_no_placeholder')
  },
  {
    prop: 'order_no',
    type: 'input',
    placeholder: t('payment.order_no_placeholder')
  },
  {
    prop: 'payment_method_id',
    type: 'select',
    placeholder: t('payment.payment_method_id_placeholder'),
    apiUrl: '/options?type=payment_method',
    filterable: true
  },
  {
    prop: 'user_id',
    type: 'input',
    placeholder: t('payment.user_id_placeholder')
  },
  {
    prop: 'status',
    type: 'select',
    placeholder: t('payment.status_placeholder'),
    options: [
      { label: t('payment.status_pending'), value: 'pending' },
      { label: t('payment.status_paid'), value: 'paid' },
      { label: t('payment.status_failed'), value: 'failed' },
      { label: t('payment.status_cancelled'), value: 'cancelled' }
    ]
  },
  {
    prop: 'start_time',
    type: 'datetime',
    placeholder: t('payment.start_time_placeholder')
  },
  {
    prop: 'end_time',
    type: 'datetime',
    placeholder: t('payment.end_time_placeholder')
  }
])

// 表格列配置
const tableColumns = computed(() => [
  {
    field: 'id',
    title: t('table.id'),
    width: 80,
    sortable: true
  },
  {
    field: 'payment_no',
    title: t('payment.payment_no'),
    minWidth: 180,
    sortable: true
  },
  {
    field: 'order_no',
    title: t('payment.order_no'),
    minWidth: 180,
    sortable: true
  },
  {
    field: 'payment_method',
    title: t('payment.payment_method'),
    width: 150,
    slot: 'payment_method'
  },
  {
    field: 'user_id',
    title: t('payment.user_id'),
    width: 100,
    sortable: true
  },
  {
    field: 'amount',
    title: t('payment.amount'),
    width: 120,
    align: 'right',
    slot: 'amount',
    sortable: true
  },
  {
    field: 'status',
    title: t('payment.status'),
    width: 100,
    slot: 'status',
    sortable: true
  },
  {
    field: 'pay_time',
    title: t('payment.pay_time'),
    width: 180,
    sortable: true
  },
  {
    field: 'created_at',
    title: t('table.created_at'),
    width: 180,
    sortable: true
  },
  {
    field: 'operation',
    title: t('table.operation'),
    width: 100,
    fixed: 'right',
    slot: 'operation',
    sortable: false
  }
])

// 获取状态类型
const getStatusType = (status) => {
  const statusMap = {
    pending: 'warning',
    paid: 'success',
    failed: 'danger',
    cancelled: 'info'
  }
  return statusMap[status] || undefined
}

// 获取状态文本
const getStatusText = (status) => {
  const statusMap = {
    pending: t('payment.status_pending'),
    paid: t('payment.status_paid'),
    failed: t('payment.status_failed'),
    cancelled: t('payment.status_cancelled')
  }
  return statusMap[status] || status
}

// 获取支付方式名称
const getPaymentMethodName = (paymentMethod) => {
  if (!paymentMethod) return '-'
  if (typeof paymentMethod === 'string') return paymentMethod
  if (typeof paymentMethod === 'object') {
    return paymentMethod.name || paymentMethod.Name || paymentMethod.code || paymentMethod.Code || '-'
  }
  return '-'
}

// 格式化金额
const formatAmount = (amount) => {
  if (amount === null || amount === undefined) return '0.00'
  return Number(amount).toFixed(2)
}

// 格式化日期时间
const formatDateTime = (dateTime) => {
  if (!dateTime) return '-'
  if (typeof dateTime === 'string') {
    return dateTime.replace('T', ' ').substring(0, 19)
  }
  return dateTime
}

// 查看详情（使用支付单号查询，因为分表后ID可能重复）
const handleView = async (row) => {
  detailDialogVisible.value = true
  detailLoading.value = true
  try {
    const paymentNo = row.payment_no || row.PaymentNo
    const response = await getPaymentDetail(paymentNo)
    paymentDetail.value = response.data?.data || response.data || {}
  } catch (error) {
    logger.error('Load payment detail error:', error)
    ErrorHandler.handle(error)
  } finally {
    detailLoading.value = false
  }
}

// 初始化
onMounted(() => {
  initDefaultSort()
  loadData()
})
</script>

<style scoped>
.list-page {
  padding: 20px;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}
</style>

// html-react/src/pages/payment/PaymentList.tsx
import { useMemo, useState } from 'react'
import { Descriptions, Drawer, Space, Spin, Table, Tag, Button } from 'antd'
import type { ColumnsType, TablePaginationConfig } from 'antd/es/table'
import { useTranslation } from 'react-i18next'
import { exportPayments, getPaymentDetail, getPaymentList } from '@/api/payment'
import { useListPage } from '@/hooks/useListPage'
import { useQueuedExport } from '@/hooks/useQueuedExport'
import { useOptions } from '@/hooks/useOptions'
import { usePermission } from '@/hooks/usePermission'
import { useUnhandledError } from '@/hooks/useUnhandledError'
import PageContainer from '@/components/PageContainer'
import SearchForm from '@/components/SearchForm'
import PermissionButton from '@/components/PermissionButton'
import { entityField } from '@/utils/normalize'
import {
  createPaymentInitialSearchForm,
  createPaymentStatusOptions,
  formatPaymentAmount,
  formatPaymentDateTime,
  getPaymentMethodName,
  getPaymentStatusColor,
  getPaymentStatusText,
  type PaymentSearchForm,
} from './payment.config'

interface PaymentRow {
  id: number | string
  payment_no: string
  order_no: string
  payment_method?: unknown
  user_id: string | number
  amount: number | string
  status: string
  pay_time?: string
  created_at?: string
}

export default function PaymentList() {
  const { t } = useTranslation()
  const showError = useUnhandledError()
  const { getButtonState } = usePermission()
  const { selectOptions: paymentMethodOptions } = useOptions('payment_method')
  const [detailOpen, setDetailOpen] = useState(false)
  const [detailLoading, setDetailLoading] = useState(false)
  const [paymentDetail, setPaymentDetail] = useState<Record<string, unknown> | null>(null)

  const initialSearchForm = useMemo(() => createPaymentInitialSearchForm(), [])

  const {
    tableData,
    loading,
    pagination,
    searchForm,
    setSearchForm,
    loadData,
    handleSearch,
    handleReset,
    handleSortChange,
    refresh,
  } = useListPage<PaymentRow, PaymentSearchForm>({
    fetchApi: getPaymentList as never,
    initialSearchForm,
    defaultSort: 'created_at:desc',
    normalizeRows: true,
    transformData: (row) => {
      const record = row as unknown as Record<string, unknown>
      return {
        id: entityField(record, 'id', '')!,
        payment_no: String(entityField(record, 'payment_no', '') ?? ''),
        order_no: String(entityField(record, 'order_no', '') ?? ''),
        payment_method: entityField(record, 'payment_method'),
        user_id: entityField(record, 'user_id', '')!,
        amount: (entityField(record, 'amount', 0) as number | string) ?? 0,
        status: String(entityField(record, 'status', '') ?? ''),
        pay_time: String(entityField(record, 'pay_time', '') ?? ''),
        created_at: String(entityField(record, 'created_at', '') ?? ''),
      }
    },
  })

  const { exporting, handleExport } = useQueuedExport({
    exportApi: exportPayments,
    getParams: () => ({ ...searchForm, order_by: 'created_at:desc' }),
    queuedMessageKey: 'common.queued',
  })

  const openDetail = async (row: PaymentRow) => {
    setDetailOpen(true)
    setDetailLoading(true)
    setPaymentDetail(null)
    try {
      const res = await getPaymentDetail(row.payment_no)
      const data = res.data as Record<string, unknown> | undefined
      const detail = (data?.data || data || {}) as Record<string, unknown>
      setPaymentDetail(detail)
    } catch (error) {
      showError(error, t('common.query_failed'))
      setDetailOpen(false)
    } finally {
      setDetailLoading(false)
    }
  }

  const columns: ColumnsType<PaymentRow> = [
    { title: t('table.id'), dataIndex: 'id', width: 80, sorter: true },
    { title: t('payment.payment_no'), dataIndex: 'payment_no', minWidth: 300, sorter: true },
    { title: t('payment.order_no'), dataIndex: 'order_no', minWidth: 180, sorter: true },
    {
      title: t('payment.payment_method'),
      dataIndex: 'payment_method',
      width: 150,
      render: (method) => getPaymentMethodName(method),
    },
    { title: t('payment.user_id'), dataIndex: 'user_id', width: 100, sorter: true },
    {
      title: t('payment.amount'),
      dataIndex: 'amount',
      width: 120,
      align: 'right',
      sorter: true,
      render: (amount) => formatPaymentAmount(amount),
    },
    {
      title: t('payment.status'),
      dataIndex: 'status',
      width: 100,
      sorter: true,
      render: (status) => (
        <Tag color={getPaymentStatusColor(status)}>{getPaymentStatusText(t, status)}</Tag>
      ),
    },
    { title: t('payment.pay_time'), dataIndex: 'pay_time', width: 180, sorter: true },
    { title: t('table.created_at'), dataIndex: 'created_at', width: 180, sorter: true },
    {
      title: t('common.operation'),
      key: 'operation',
      width: 100,
      fixed: 'right',
      render: (_, row) =>
        getButtonState('payment.show').show ? (
          <PermissionButton permission="payment.show" type="link" onClick={() => void openDetail(row)}>
            {t('common.view')}
          </PermissionButton>
        ) : null,
    },
  ]

  return (
    <PageContainer
      title={t('menu.payment')}
      extra={
        <Space>
          <PermissionButton permission="payment.export" loading={exporting} onClick={() => void handleExport()}>
            {t('common.export')}
          </PermissionButton>
          <Button onClick={() => void refresh()}>{t('common.refresh')}</Button>
        </Space>
      }
    >
      <SearchForm
        fields={[
          {
            name: 'payment_no',
            label: t('payment.payment_no'),
            placeholder: t('payment.payment_no_placeholder'),
          },
          {
            name: 'order_no',
            label: t('payment.order_no'),
            placeholder: t('payment.order_no_placeholder'),
          },
          {
            name: 'payment_method_id',
            label: t('payment.payment_method_id'),
            type: 'select',
            placeholder: t('payment.payment_method_id_placeholder'),
            options: paymentMethodOptions,
          },
          {
            name: 'user_id',
            label: t('payment.user_id'),
            placeholder: t('payment.user_id_placeholder'),
          },
          {
            name: 'status',
            label: t('payment.status'),
            type: 'select',
            placeholder: t('payment.status_placeholder'),
            options: createPaymentStatusOptions(t),
          },
          {
            name: 'start_time',
            label: t('payment.start_time'),
            type: 'datetime',
            placeholder: t('payment.start_time_placeholder'),
          },
          {
            name: 'end_time',
            label: t('payment.end_time'),
            type: 'datetime',
            placeholder: t('payment.end_time_placeholder'),
          },
        ]}
        values={searchForm}
        onChange={(values) => setSearchForm(values as unknown as PaymentSearchForm)}
        onSearch={handleSearch}
        onReset={handleReset}
      />
      <Table<PaymentRow>
        rowKey="id"
        loading={loading}
        columns={columns}
        dataSource={tableData}
        scroll={{ x: 1400 }}
        pagination={{
          current: pagination.page,
          pageSize: pagination.pageSize,
          total: pagination.total,
          showSizeChanger: true,
          showTotal: (total) => (total >= 100000 ? t('common.total', { total: '100000+' }) : t('common.total', { total })),
        }}
        onChange={(pager: TablePaginationConfig, _f, sorter) => {
          const sort = Array.isArray(sorter) ? sorter[0] : sorter
          const sortObj = sort as { field?: string; order?: 'ascend' | 'descend' | null; column?: unknown }
          if (sortObj?.column && sortObj.field) {
            handleSortChange(String(sortObj.field), sortObj.order)
            return
          }
          void loadData({
            currentPage: pager.current || 1,
            pageSize: pager.pageSize || pagination.pageSize,
          })
        }}
      />
      <Drawer
        open={detailOpen}
        title={t('payment.payment_detail')}
        width={800}
        onClose={() => setDetailOpen(false)}
      >
        <Spin spinning={detailLoading}>
          {paymentDetail ? (
            <Descriptions bordered column={2} size="small">
              <Descriptions.Item label={t('payment.payment_no')}>
                {String(entityField(paymentDetail, 'payment_no', '-') ?? '-')}
              </Descriptions.Item>
              <Descriptions.Item label={t('payment.order_no')}>
                {String(entityField(paymentDetail, 'order_no', '-') ?? '-')}
              </Descriptions.Item>
              <Descriptions.Item label={t('payment.payment_method')}>
                {getPaymentMethodName(entityField(paymentDetail, 'payment_method'))}
              </Descriptions.Item>
              <Descriptions.Item label={t('payment.user_id')}>
                {String(entityField(paymentDetail, 'user_id', '-') ?? '-')}
              </Descriptions.Item>
              <Descriptions.Item label={t('payment.amount')}>
                {formatPaymentAmount(entityField(paymentDetail, 'amount'))}
              </Descriptions.Item>
              <Descriptions.Item label={t('payment.status')}>
                <Tag color={getPaymentStatusColor(String(entityField(paymentDetail, 'status', '')))}>
                  {getPaymentStatusText(t, String(entityField(paymentDetail, 'status', '')))}
                </Tag>
              </Descriptions.Item>
              <Descriptions.Item label={t('payment.third_party_no')}>
                {String(entityField(paymentDetail, 'third_party_no', '-') || '-')}
              </Descriptions.Item>
              <Descriptions.Item label={t('payment.pay_time')}>
                {String(entityField(paymentDetail, 'pay_time', '-') || '-')}
              </Descriptions.Item>
              {entityField(paymentDetail, 'fail_reason') ? (
                <Descriptions.Item label={t('payment.fail_reason')} span={2}>
                  {String(entityField(paymentDetail, 'fail_reason', ''))}
                </Descriptions.Item>
              ) : null}
              {entityField(paymentDetail, 'remark') ? (
                <Descriptions.Item label={t('payment.remark')} span={2}>
                  {String(entityField(paymentDetail, 'remark', ''))}
                </Descriptions.Item>
              ) : null}
              <Descriptions.Item label={t('table.created_at')}>
                {formatPaymentDateTime(entityField(paymentDetail, 'created_at'))}
              </Descriptions.Item>
              <Descriptions.Item label={t('table.updated_at')}>
                {formatPaymentDateTime(entityField(paymentDetail, 'updated_at'))}
              </Descriptions.Item>
            </Descriptions>
          ) : null}
        </Spin>
      </Drawer>
    </PageContainer>
  )
}
