// html-react/src/pages/admin/AdminList.tsx
import { useState } from 'react'
import { App, Button, Dropdown, Form, Input, Space, Switch, Table, Tag } from 'antd'
import type { ColumnsType, TablePaginationConfig } from 'antd/es/table'
import type { MenuProps } from 'antd'
import { DownOutlined, SettingOutlined } from '@ant-design/icons'
import { useTranslation } from 'react-i18next'
import {
  deleteAdmin,
  exportAdmin,
  getAdminList,
  kickOutUser,
  resetAdminGoogleAuth,
  resetPassword,
  unbindAdminGoogleAuth,
  updateAdmin,
} from '@/api/admin'
import { useListPage } from '@/hooks/useListPage'
import { useCrudActions } from '@/hooks/useCrudActions'
import { usePermission } from '@/hooks/usePermission'
import { useUnhandledError } from '@/hooks/useUnhandledError'
import { useColumnSetting } from '@/hooks/useColumnSetting'
import PageContainer from '@/components/PageContainer'
import SearchForm from '@/components/SearchForm'
import PermissionButton from '@/components/PermissionButton'
import ColumnSettingDialog from '@/components/ColumnSettingDialog'
import { entityField } from '@/utils/normalize'
import AdminFormModal from './AdminFormModal'

interface AdminRow {
  id: number | string
  username: string
  nickname?: string
  email?: string
  phone?: string
  status?: number
  created_at?: string
  is_2fa_bound?: boolean
  department?: { name?: string } | string
  position?: { name?: string } | string
  roles?: Array<{ id?: number | string; name?: string }>
}

const protectedIds = new Set([1, 2])

export default function AdminList() {
  const { t } = useTranslation()
  const { message, modal } = App.useApp()
  const showError = useUnhandledError()
  const { getButtonState } = usePermission()
  const [formOpen, setFormOpen] = useState(false)
  const [editId, setEditId] = useState<string | number | null>(null)
  const [exporting, setExporting] = useState(false)
  const [pwdForm] = Form.useForm()

  const {
    tableData,
    loading,
    pagination,
    searchForm,
    setSearchForm,
    loadData,
    handleSearch,
    handleReset,
    handleSortChange,
    refresh,
  } = useListPage<AdminRow, Record<string, unknown>>({
    fetchApi: getAdminList as never,
    initialSearchForm: { username: '', status: '', is_2fa_bound: '' },
    defaultSort: 'id:desc',
    normalizeRows: true,
    transformData: (row) => {
      const record = row as unknown as Record<string, unknown>
      return {
        id: entityField(record, 'id', '')!,
        username: String(entityField(record, 'username', '') ?? ''),
        nickname: String(entityField(record, 'nickname', '') ?? ''),
        email: String(entityField(record, 'email', '') ?? ''),
        phone: String(entityField(record, 'phone', '') ?? ''),
        status: Number(entityField(record, 'status', 0) ?? 0),
        created_at: String(entityField(record, 'created_at', '') ?? ''),
        is_2fa_bound: !!(
          entityField(record, 'is_2fa_bound', false) || entityField(record, 'Is2faBound', false)
        ),
        department: (entityField(record, 'department', null) as AdminRow['department']) || undefined,
        position: (entityField(record, 'position', null) as AdminRow['position']) || undefined,
        roles: (entityField(record, 'roles', []) as AdminRow['roles']) || [],
      }
    },
  })

  const { toolbar, confirmDelete } = useCrudActions({
    createPermission: 'admin.store',
    onRefresh: refresh,
    onCreate: () => {
      setEditId(null)
      setFormOpen(true)
    },
    deleteApi: deleteAdmin,
  })

  const deptName = (dept: AdminRow['department']) => {
    if (!dept) return '-'
    if (typeof dept === 'string') return dept
    return dept.name || '-'
  }

  const posName = (pos: AdminRow['position']) => {
    if (!pos) return '-'
    if (typeof pos === 'string') return pos
    return pos.name || '-'
  }

  const handleStatusChange = async (row: AdminRow, checked: boolean) => {
    if (protectedIds.has(Number(row.id)) && !checked) {
      message.warning(t('admin.protected_cannot_disable', { defaultValue: '受保护账号不能禁用' }))
      return
    }
    try {
      await updateAdmin(row.id, { status: checked ? 1 : 0 })
      message.success(t('common.update_success'))
      await refresh()
    } catch (error) {
      showError(error, t('common.operation_failed'))
    }
  }

  const handleResetPassword = (row: AdminRow) => {
    pwdForm.resetFields()
    modal.confirm({
      title: t('admin.reset_password'),
      content: (
        <Form form={pwdForm} layout="vertical" style={{ marginTop: 16 }}>
          <Form.Item
            name="password"
            label={t('admin.new_password', { defaultValue: '新密码' })}
            rules={[{ required: true, message: t('admin.password_required') }]}
          >
            <Input.Password />
          </Form.Item>
        </Form>
      ),
      onOk: async () => {
        const values = await pwdForm.validateFields()
        try {
          await resetPassword(row.id, { password: values.password })
          message.success(t('admin.reset_password_success', { defaultValue: '密码已重置' }))
        } catch (error) {
          showError(error, t('common.operation_failed'))
          throw error
        }
      },
    })
  }

  const runConfirm = (title: string, content: string, action: () => Promise<void>) => {
    modal.confirm({
      title,
      content,
      onOk: async () => {
        try {
          await action()
        } catch (error) {
          showError(error, t('common.operation_failed'))
          throw error
        }
      },
    })
  }

  const moreMenu = (row: AdminRow): MenuProps['items'] =>
    [
      getButtonState('admin.password').show
        ? {
            key: 'resetPassword',
            label: t('admin.reset_password'),
            onClick: () => handleResetPassword(row),
          }
        : null,
      getButtonState('admin.kick_out').show
        ? {
            key: 'kickOut',
            label: t('admin.kick_out', { defaultValue: '踢出登录' }),
            onClick: () =>
              runConfirm(
                t('admin.kick_out', { defaultValue: '踢出登录' }),
                t('admin.kick_out_confirm', {
                  username: row.username,
                  defaultValue: `确定踢出 ${row.username} 的全部登录吗？`,
                }),
                async () => {
                  await kickOutUser(row.id)
                  message.success(t('admin.kick_out_success', { defaultValue: '已踢出' }))
                },
              ),
          }
        : null,
      row.is_2fa_bound && getButtonState('admin.unbind_google_auth').show
        ? {
            key: 'unbind2fa',
            label: t('admin.unbind_google_auth', { defaultValue: '解绑谷歌验证' }),
            onClick: () =>
              runConfirm(
                t('admin.unbind_google_auth', { defaultValue: '解绑谷歌验证' }),
                t('admin.unbind_google_auth_confirm', {
                  defaultValue: '确定解绑该管理员的谷歌验证码吗？',
                }),
                async () => {
                  await unbindAdminGoogleAuth(row.id)
                  message.success(t('common.update_success'))
                  await refresh()
                },
              ),
          }
        : null,
      getButtonState('admin.reset_google_auth').show
        ? {
            key: 'reset2fa',
            label: t('admin.reset_google_auth', { defaultValue: '重置谷歌验证' }),
            onClick: () =>
              runConfirm(
                t('admin.reset_google_auth', { defaultValue: '重置谷歌验证' }),
                t('admin.reset_google_auth_confirm', {
                  defaultValue: '确定重置该管理员的谷歌验证码吗？',
                }),
                async () => {
                  await resetAdminGoogleAuth(row.id)
                  message.success(t('common.update_success'))
                  await refresh()
                },
              ),
          }
        : null,
    ].filter(Boolean) as MenuProps['items']

  const columns: ColumnsType<AdminRow> = [
    { title: t('table.id'), dataIndex: 'id', width: 80, sorter: true },
    { title: t('table.username'), dataIndex: 'username' },
    { title: t('table.nickname'), dataIndex: 'nickname' },
    { title: t('table.email'), dataIndex: 'email' },
    { title: t('table.department'), dataIndex: 'department', render: (v) => deptName(v) },
    { title: t('table.position'), dataIndex: 'position', render: (v) => posName(v) },
    {
      title: t('table.roles'),
      dataIndex: 'roles',
      render: (roles: AdminRow['roles']) =>
        roles?.length ? (
          <Space size={[4, 4]} wrap>
            {roles.map((role) => (
              <Tag key={String(role.id)}>{role.name}</Tag>
            ))}
          </Space>
        ) : (
          '-'
        ),
    },
    {
      title: t('admin.google_auth_status', { defaultValue: '谷歌验证' }),
      dataIndex: 'is_2fa_bound',
      width: 110,
      render: (bound: boolean) =>
        bound
          ? t('admin.google_auth_bound', { defaultValue: '已绑定' })
          : t('admin.google_auth_not_bound', { defaultValue: '未绑定' }),
    },
    {
      title: t('table.status'),
      dataIndex: 'status',
      width: 100,
      render: (status: number, row) => (
        <Switch
          checked={status === 1}
          disabled={protectedIds.has(Number(row.id)) || getButtonState('admin.update').disabled}
          onChange={(checked) => void handleStatusChange(row, checked)}
        />
      ),
    },
    { title: t('table.created_at'), dataIndex: 'created_at', width: 180, sorter: true },
    {
      title: t('common.operation'),
      key: 'operation',
      width: 220,
      fixed: 'right',
      render: (_, row) => (
        <Space>
          {getButtonState('admin.update').show && (
            <PermissionButton
              permission="admin.update"
              type="link"
              onClick={() => {
                setEditId(row.id)
                setFormOpen(true)
              }}
            >
              {t('common.edit')}
            </PermissionButton>
          )}
          {getButtonState('admin.destroy').show && !protectedIds.has(Number(row.id)) && (
            <PermissionButton
              permission="admin.destroy"
              type="link"
              danger
              onClick={() => confirmDelete(row.id, row.username)}
            >
              {t('common.delete')}
            </PermissionButton>
          )}
          <Dropdown menu={{ items: moreMenu(row) }}>
            <a onClick={(e) => e.preventDefault()}>
              {t('common.more', { defaultValue: '更多' })} <DownOutlined />
            </a>
          </Dropdown>
        </Space>
      ),
    },
  ]

  const handleExport = async () => {
    setExporting(true)
    try {
      await exportAdmin(searchForm)
      message.success(t('common.queued', { defaultValue: '导出任务已提交，请稍后查看导出记录' }))
    } catch (error) {
      showError(error, t('common.operation_failed'))
    } finally {
      setExporting(false)
    }
  }

  const {
    filteredColumns,
    open: columnSettingOpen,
    openColumnSetting,
    closeColumnSetting,
    allColumns,
    visibleColumns,
    columnOrder,
    fixedColumns,
    handleConfirm: handleColumnSettingConfirm,
  } = useColumnSetting('admin', columns)

  return (
    <PageContainer
      title={t('menu.admin_management')}
      extra={
        <Space>
          {toolbar}
          <PermissionButton permission="admin.export" loading={exporting} onClick={() => void handleExport()}>
            {t('common.export', { defaultValue: '导出' })}
          </PermissionButton>
          <Button icon={<SettingOutlined />} onClick={openColumnSetting}>
            {t('common.column_setting')}
          </Button>
        </Space>
      }
    >
      <SearchForm
        fields={[
          { name: 'username', label: t('table.username') },
          {
            name: 'status',
            label: t('table.status'),
            type: 'select',
            options: [
              { label: t('common.enabled'), value: 1 },
              { label: t('common.disabled'), value: 0 },
            ],
          },
          {
            name: 'is_2fa_bound',
            label: t('admin.google_auth_status', { defaultValue: '谷歌验证' }),
            type: 'select',
            options: [
              { label: t('admin.google_auth_bound', { defaultValue: '已绑定' }), value: '1' },
              { label: t('admin.google_auth_not_bound', { defaultValue: '未绑定' }), value: '0' },
            ],
          },
        ]}
        values={searchForm}
        onChange={(values) => setSearchForm(values as typeof searchForm)}
        onSearch={handleSearch}
        onReset={handleReset}
      />
      <Table<AdminRow>
        rowKey="id"
        loading={loading}
        columns={filteredColumns}
        dataSource={tableData}
        scroll={{ x: 1400 }}
        pagination={{
          current: pagination.page,
          pageSize: pagination.pageSize,
          total: pagination.total,
          showSizeChanger: true,
          showTotal: (total) => t('common.total', { total }),
        }}
        onChange={(pager: TablePaginationConfig, _f, sorter) => {
          const sort = Array.isArray(sorter) ? sorter[0] : sorter
          const sortObj = sort as { field?: string; order?: 'ascend' | 'descend' | null; column?: unknown }
          if (sortObj?.column && sortObj.field) {
            handleSortChange(String(sortObj.field), sortObj.order)
            return
          }
          void loadData({
            currentPage: pager.current || 1,
            pageSize: pager.pageSize || pagination.pageSize,
          })
        }}
      />
      <AdminFormModal
        open={formOpen}
        editId={editId}
        onClose={() => setFormOpen(false)}
        onSuccess={() => void refresh()}
      />
      <ColumnSettingDialog
        open={columnSettingOpen}
        onClose={closeColumnSetting}
        allColumns={allColumns}
        visibleColumns={visibleColumns}
        columnOrder={columnOrder}
        fixedColumns={fixedColumns}
        onConfirm={handleColumnSettingConfirm}
      />
    </PageContainer>
  )
}

// html/src/views/admin/AdminList.vue
<template>
  <div class="list-page">
    <el-card>
      <template #header>
        <div class="card-header">
          <span>{{ $t('menu.admin') }}</span>
          <el-button 
            type="primary" 
            :disabled="getButtonState('admin.store').disabled"
            @click="handleAdd"
          >
            <el-icon><PlusIcon /></el-icon>
            {{ $t('admin.add_admin') }}
          </el-button>
        </div>
      </template>

      <!-- 搜索表单 -->
      <SearchForm
        :model="searchForm"
        :fields="searchFields"
        :initial-values="initialSearchForm"
        i18n-prefix="admin"
        @search="handleSearch"
        @reset="handleReset"
      >
        <template #extra-buttons>
          <el-button 
            type="success" 
            :disabled="getButtonState('admin.export').disabled || isExporting"
            :loading="isExporting"
            @click="handleExport"
          >
            {{ $t('common.export') }}
          </el-button>
        </template>
      </SearchForm>

      <!-- 表格工具栏 -->
      <TableToolbar
        :on-refresh="handleRefresh"
        fullscreen-target=".list-page"
        :visible-columns="visibleColumns"
        :all-columns="allTableColumns"
        :default-visible-columns="defaultVisibleColumns"
        :column-order="columnOrder"
        :fixed-columns="fixedColumns"
        :on-column-setting-confirm="handleColumnSettingConfirm"
      />

      <VxeTable
        ref="tableRef"
        :key="`table-${tableColumns.length}-${JSON.stringify(tableColumns.map(c => c.field || c.slot || c.key))}`"
        :data="tableData"
        :loading="loading"
        :columns="tableColumns"
        :height="600"
        @sort-change="handleSortChange"
      >
        <template #status="{ row }">
          <el-switch
            :model-value="Number(row.status ?? row.Status ?? 1) === 1"
            :disabled="isProtectedAdmin(row.id) || getButtonState('admin.update').disabled"
            @change="(val) => handleStatusChange(row, val)"
          />
        </template>

        <template #department="{ row }">
          {{ getDepartmentDisplayName(row.Department || row.department) }}
        </template>

        <template #position="{ row }">
          {{ getPositionDisplayName(row.Position || row.position) }}
        </template>

        <template #roles="{ row }">
          <template v-if="(row.Roles || row.roles) && (row.Roles || row.roles).length > 0">
            <el-tag
              v-for="role in getUniqueRoles(row.Roles || row.roles)"
              :key="role.id || role.ID"
              style="margin-right: 5px;margin-bottom:2px"
            >
              {{ role.Name || role.name }}
            </el-tag>
          </template>
          <span v-else>-</span>
        </template>

        <template #is_2fa_bound="{ row }">
          {{ (row.is_2fa_bound || row.Is2FABound) ? $t('admin.google_auth_bound') : $t('admin.google_auth_not_bound') }}
        </template>

        <template #operation="{ row }">
          <TableActionButtons
            :row="row"
            :primary-actions="getPrimaryActions(row)"
            :more-actions="getMoreActions(row)"
            :get-button-state="getButtonState"
            @action="handleAction"
          />
        </template>
      </VxeTable>

      <Pagination
        v-model="pagination"
        :auto-load="true"
        :on-page-change="loadData"
      />
    </el-card>

    <!-- 添加/编辑对话框 -->
    <AdminForm
      ref="adminFormRef"
      v-model="dialogVisible"
      :edit-id="editId"
      @success="handleFormSuccess"
    />
  </div>
</template>

<script setup>
import { ref, reactive, onMounted, computed, markRaw } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Plus } from '@element-plus/icons-vue'
import SearchForm from '../../components/SearchForm.vue'
import Pagination from '../../components/Pagination.vue'
import VxeTable from '../../components/VxeTable.vue'
import TableActionButtons from '../../components/TableActionButtons.vue'
import TableToolbar from '../../components/TableToolbar.vue'
import AdminForm from './AdminForm.vue'
import { useListPage } from '../../composables/useListPage'
import { usePermission } from '../../composables/usePermission'
import { useCrud } from '../../composables/useCrud'
import { useColumnSetting } from '../../composables/useColumnSetting'
import { getStatusOptions } from '../../utils/fieldOptions'
import {
  getAdminList,
  deleteAdmin,
  updateAdmin,
  exportAdmin,
  resetPassword,
  kickOutUser,
  unbindAdminGoogleAuth,
  resetAdminGoogleAuth
} from '../../api/admin'
import logger from '../../utils/logger'
import ErrorHandler from '../../utils/errorHandler'
import { uniqBy, compact, map as lodashMap } from 'lodash-es'

const PlusIcon = markRaw(Plus)

// 权限控制
const { getButtonState } = usePermission()

const { t } = useI18n()
const router = useRouter()
const tableRef = ref(null)
const adminFormRef = ref(null)
const isExporting = ref(false) // 导出中状态，防止重复点击

const {
  dialogVisible,
  editId,
  handleAdd,
  handleClose,
  handleDelete: handleDeleteCrud
} = useCrud({
  deleteApi: deleteAdmin
})

const {
  pagination,
  tableData,
  loading,
  searchForm,
  loadData,
  handleSearch,
  handleReset,
  handleSortChange,
  initDefaultSort
} = useListPage({
  fetchApi: getAdminList,
  initialSearchForm: {
    username: '',
    status: '',
    role_id: '',
    department_id: '',
    position_id: '',
    is_2fa_bound: ''
  },
  fieldMapping: {},
  defaultSort: 'id:desc',
  tableRef: computed(() => tableRef.value?.tableRef)
})

// 初始搜索表单（用于 SearchForm 的 initial-values）
const initialSearchForm = {
  username: '',
  status: '',
  role_id: '',
  department_id: '',
  position_id: '',
  is_2fa_bound: ''
}

// 表格列配置（使用 vxe-table columns）
const allTableColumns = computed(() => [
  {
    field: 'id',
    title: t('table.id'),
    width: 80,
    sortable: true,
    key: 'id'
  },
  {
    field: 'username',
    title: t('table.username'),
    sortable: false,
    key: 'username'
  },
  {
    field: 'nickname',
    title: t('table.nickname'),
    sortable: false,
    key: 'nickname'
  },
  {
    field: 'email',
    title: t('table.email'),
    sortable: false,
    key: 'email'
  },
  {
    field: 'phone',
    title: t('table.phone'),
    sortable: false,
    key: 'phone'
  },
  {
    field: 'status',
    title: t('table.status'),
    width: 100,
    sortable: false,
    slot: 'status',
    key: 'status'
  },
  {
    field: 'is_2fa_bound',
    title: t('admin.google_auth_status'),
    width: 120,
    sortable: false,
    slot: 'is_2fa_bound',
    key: 'is_2fa_bound'
  },
  {
    field: 'department',
    title: t('table.department'),
    slot: 'department',
    sortable: false,
    key: 'department'
  },
  {
    field: 'position',
    title: t('table.position'),
    slot: 'position',
    sortable: false,
    key: 'position',
    required: true
  },
  {
    field: 'roles',
    title: t('table.roles'),
    slot: 'roles',
    sortable: false,
    key: 'roles'
  },
  {
    field: 'created_at',
    title: t('table.created_at'),
    sortable: true,
    key: 'created_at',
    width: 160,
  },
  {
    title: t('table.operation'),
    width: 220,
    fixed: 'right',
    slot: 'operation',
    key: 'operation'
  }
])

// 使用列设置 composable
const {
  tableColumns,
  visibleColumns,
  allColumns,
  defaultVisibleColumns,
  columnOrder,
  fixedColumns,
  handleColumnSettingConfirm
} = useColumnSetting('admin', allTableColumns, {
  adjacentPairs: [['department', 'position']]
})

// 处理刷新
const handleRefresh = () => {
  loadData()
}

// 搜索表单字段配置
const searchFields = computed(() => [
  {
    prop: 'username',
    label: t('table.username'),
    type: 'input',
    width: '200px',
    advanced: false
  },
  {
    prop: 'status',
    label: t('table.status'),
    type: 'select',
    width: '150px',
    options: getStatusOptions(t),
    advanced: false
  },
  {
    prop: 'is_2fa_bound',
    label: t('admin.google_auth_status'),
    type: 'select',
    width: '150px',
    options: [
      { label: t('admin.google_auth_bound'), value: '1' },
      { label: t('admin.google_auth_not_bound'), value: '0' }
    ],
    advanced: false
  },
  {
    prop: 'role_id',
    label: t('menu.role'),
    type: 'select',
    width: '150px',
    filterable: true,
    apiUrl: '/options?type=role', 
    //  apiUrl: '/options?type=dictionary&dictionary_type=status', 
    advanced: false
  },
  {
    prop: 'department_id',
    label: t('table.department'),
    type: 'tree-select',
    width: '200px',
    filterable: true,
    apiUrl: '/options?type=department', 
    treeProps: { label: 'name', children: 'children', value: 'id' },
    advanced: false
  },
  {
    prop: 'position_id',
    label: t('table.position'),
    type: 'select',
    width: '180px',
    filterable: true,
    apiUrl: '/options?type=position',
    advanced: false
  }
])

const protectedAdminIds = ref([1, 2])

// handleSearch, handleReset, handlePageChange 已由 useListPage 提供
// handleAdd, handleDelete 已由 useCrud 提供

// 获取去重后的角色列表
const getUniqueRoles = (roles) => {
  if (!roles || !Array.isArray(roles)) return []
  return uniqBy(roles.filter(role => {
    const roleId = role.id || role.ID
    return roleId
  }), role => role.id || role.ID)
}

const getDepartmentDisplayName = (department) => {
  if (!department) return '-'
  return department.Name || department.name || '-'
}

const getPositionDisplayName = (position) => {
  if (!position) return '-'
  const name = position.Name || position.name
  const id = position.ID ?? position.id
  if (!name && (!id || id === 0)) return '-'
  return name || '-'
}

const handleEdit = async (row) => {
  // 先打开对话框，让表单组件显示loading
  editId.value = row.id
  dialogVisible.value = true
  
  // 等待对话框打开后再设置数据
  await new Promise(resolve => setTimeout(resolve, 100))
  
  // 处理字段映射，支持 PascalCase 和 snake_case
  const adminRoles = row.Roles || row.roles
  
  // 去重角色ID
  const uniqueRoleIds = adminRoles ? [...new Set(compact(lodashMap(adminRoles, r => r.id || r.ID)))] : []
  
  // 设置表单数据（setFormData内部会处理loading）
  if (adminFormRef.value) {
    adminFormRef.value.setFormData({
      id: row.id,
      username: row.Username || row.username || '',
      password: '',
      nickname: row.Nickname || row.nickname || '',
      email: row.Email || row.email || '',
      phone: row.Phone || row.phone || '',
      department_id: row.DepartmentID !== undefined ? row.DepartmentID : (row.department_id !== undefined ? row.department_id : null),
      position_id: row.PositionID !== undefined ? row.PositionID : (row.position_id !== undefined ? row.position_id : 0),
      role_ids: uniqueRoleIds,
      status: row.Status !== undefined ? row.Status : (row.status !== undefined ? row.status : 1),
      is_super_admin: row.is_super_admin === true || row.IsSuperAdmin === true
    })
  }
}

const handleFormSuccess = () => {
  loadData()
}

const isProtectedAdmin = (adminId) => {
  return protectedAdminIds.value.includes(adminId)
}

const handleStatusChange = async (row, newStatus) => {
  // 检查是否是受保护管理员
  if (isProtectedAdmin(row.id) && !newStatus) {
    ElMessage.warning(t('admin.protected_cannot_disable'))
    // 恢复开关状态
    loadData()
    return
  }

  try {
    const statusValue = newStatus ? 1 : 0
    await updateAdmin(row.id, {
      status: statusValue
    })
    ElMessage.success(newStatus ? t('admin.enable_success') : t('admin.disable_success'))
    // 更新本地数据
    const admin = tableData.value.find(a => a.id === row.id)
    if (admin) {
      admin.status = statusValue
      admin.Status = statusValue
    }
  } catch (error) {
    logger.error('Status change error:', error)
    // 恢复开关状态
    loadData()
    // 如果错误已经在响应拦截器中处理过，就不再重复显示
    if (!error.__handled) {
      const errorMessage = error.response?.data?.message || error.message || t('common.operation_failed')
      ElMessage.error(errorMessage)
    }
  }
}

const handleDelete = (row) => handleDeleteCrud(row, loadData)

const handleResetPassword = async (row) => {
  try {
    const { value: password } = await ElMessageBox.prompt(t('admin.new_password'), t('admin.reset_password'), {
      confirmButtonText: t('common.confirm'),
      cancelButtonText: t('common.cancel'),
      inputType: 'password'
    })
    await resetPassword(row.id, { password })
    ElMessage.success(t('admin.reset_password_success'))
  } catch (error) {
    if (error !== 'cancel') {
      logger.error('Reset password error:', error)
      ErrorHandler.handle(error, { silent: true })
    }
  }
}

const handleKickOut = async (row) => {
  try {
    await ElMessageBox.confirm(
      t('admin.kick_out_confirm', { username: row.username || row.Username }),
      t('form.tip'),
      {
        confirmButtonText: t('common.confirm'),
        cancelButtonText: t('common.cancel'),
        type: 'warning'
      }
    )
    await kickOutUser(row.id)
    ElMessage.success(t('admin.kick_out_success'))
  } catch (error) {
    if (error !== 'cancel') {
      logger.error('Kick out error:', error)
      ErrorHandler.handle(error, { silent: true })
    }
  }
}

// 获取主要操作按钮配置
const getPrimaryActions = (row) => {
  return [
    {
      key: 'edit',
      label: t('common.edit'),
      type: 'primary',
      permission: 'admin.update',
      handler: handleEdit
    },
    {
      key: 'delete',
      label: t('common.delete'),
      type: 'danger',
      permission: 'admin.destroy',
      show: () => !isProtectedAdmin(row.id),
      handler: handleDelete
    }
  ]
}

// 获取更多操作按钮配置
const getMoreActions = (row) => {
  return [
    {
      key: 'resetPassword',
      command: 'resetPassword',
      label: t('admin.reset_password'),
      permission: 'admin.password',
      handler: handleResetPassword
    },
    {
      key: 'kickOut',
      command: 'kickOut',
      label: t('admin.kick_out'),
      permission: 'admin.kick_out',
      handler: handleKickOut
    },
    {
      key: 'unbindGoogleAuth',
      command: 'unbindGoogleAuth',
      label: t('admin.unbind_google_auth'),
      permission: 'admin.unbind_google_auth',
      divided: true,
      show: () => (row.is_2fa_bound || row.Is2FABound) && !isProtectedAdmin(row.id),
      handler: handleUnbindGoogleAuth
    },
    {
      key: 'resetGoogleAuth',
      command: 'resetGoogleAuth',
      label: t('admin.reset_google_auth'),
      permission: 'admin.reset_google_auth',
      show: () => (row.is_2fa_bound || row.Is2FABound) && !isProtectedAdmin(row.id),
      handler: handleResetGoogleAuth
    }
  ]
}

// 处理操作事件
const handleAction = (command, row) => {
  switch (command) {
    case 'edit':
      handleEdit(row)
      break
    case 'delete':
      handleDelete(row)
      break
    case 'resetPassword':
      handleResetPassword(row)
      break
    case 'kickOut':
      handleKickOut(row)
      break
    case 'unbindGoogleAuth':
      handleUnbindGoogleAuth(row)
      break
    case 'resetGoogleAuth':
      handleResetGoogleAuth(row)
      break
  }
}

const handleUnbindGoogleAuth = async (row) => {
  try {
    const { value: code } = await ElMessageBox.prompt(
      t('admin.unbind_google_auth_confirm', { username: row.username || row.Username }),
      t('admin.unbind_google_auth'),
      {
        confirmButtonText: t('common.confirm'),
        cancelButtonText: t('common.cancel'),
        inputPlaceholder: t('profile.enter_6_digit_code'),
        inputType: 'text',
        inputPattern: /^\d{6}$/,
        inputErrorMessage: t('profile.google_code_format')
      }
    )
    
    await unbindAdminGoogleAuth(row.id, { code })
    ElMessage.success(t('admin.unbind_google_auth_success'))
    loadData()
  } catch (error) {
    if (error !== 'cancel') {
      logger.error('Unbind google auth error:', error)
      if (!error?.__handled) {
        const errorMessage = error.response?.data?.message || error.translatedMessage || error.message || t('common.operation_failed')
        ElMessage.error(errorMessage)
      }
    }
  }
}

const handleResetGoogleAuth = async (row) => {
  try {
    await ElMessageBox.confirm(
      t('admin.reset_google_auth_confirm', { username: row.username || row.Username }),
      t('admin.reset_google_auth'),
      {
        confirmButtonText: t('common.confirm'),
        cancelButtonText: t('common.cancel'),
        type: 'warning'
      }
    )
    await resetAdminGoogleAuth(row.id)
    ElMessage.success(t('admin.reset_google_auth_success'))
    loadData()
  } catch (error) {
    if (error !== 'cancel') {
      logger.error('Reset google auth error:', error)
      if (!error?.__handled) {
        const errorMessage = error.response?.data?.message || error.translatedMessage || error.message || t('common.operation_failed')
        ElMessage.error(errorMessage)
      }
    }
  }
}

const handleExport = async () => {
  // 防止重复点击
  if (isExporting.value) {
    return
  }

  isExporting.value = true

  try {
    await exportAdmin(searchForm)
    // 不再直接触发下载，导出记录会写入导出管理列表，由用户在导出管理中查看和下载
    ElMessage.success(t('common.queued'))
    // 导出完成后跳转到导出管理列表
    router.push('/exports')
  } catch (error) {
    logger.error('Export error:', error)
    // 检查是否是重复提交错误
    if (error.response?.status === 429) {
      // 429 错误由业务代码处理，显示友好的提示
      ElMessage.warning(t('common.already_queued'))
    } else if (!error.__handled) {
      // 其他错误，如果未处理则显示
      ErrorHandler.handle(error, { silent: true })
    }
  } finally {
    // 无论成功还是失败，都要重置导出状态
    isExporting.value = false
  }
}

onMounted(async () => {
  try {
    initDefaultSort()
    await loadData()
  } catch (error) {
    logger.error('AdminList onMounted error:', error)
    ErrorHandler.handle(error)
  }
})
</script>

<style scoped>



</style>
