// html-react/src/pages/onlineAdmin/OnlineAdminList.tsx
﻿import { useState } from 'react'
import { Avatar, Button, Space, Table } from 'antd'
import type { ColumnsType, TablePaginationConfig } from 'antd/es/table'
import { useTranslation } from 'react-i18next'
import { SettingOutlined } from '@ant-design/icons'
import { App } from 'antd'
import {
  batchKickOutOnlineAdmins,
  getOnlineAdminList,
  kickOutOnlineAdmin,
} from '@/api/onlineAdmin'
import { useListPage } from '@/hooks/useListPage'
import { useCrudActions } from '@/hooks/useCrudActions'
import { usePermission } from '@/hooks/usePermission'
import { useUnhandledError } from '@/hooks/useUnhandledError'
import { useColumnSetting } from '@/hooks/useColumnSetting'
import PageContainer from '@/components/PageContainer'
import ColumnSettingDialog from '@/components/ColumnSettingDialog'
import SearchForm from '@/components/SearchForm'
import PermissionButton from '@/components/PermissionButton'
import { entityField } from '@/utils/normalize'

interface OnlineAdminRow {
  id: number | string
  username?: string
  nickname?: string
  avatar?: string
  browser?: string
  ip?: string
  os?: string
  session_id?: string
  last_active?: string
  name?: string
}

function formatOnlineTime(time?: string) {
  if (!time) return '-'
  const date = new Date(time)
  if (Number.isNaN(date.getTime())) return time
  return date.toLocaleString().replace(/\//g, '-')
}

export default function OnlineAdminList() {
  const { t } = useTranslation()
  const { modal, message } = App.useApp()
  const showError = useUnhandledError()
  const { getButtonState } = usePermission()
  const [selectedRowKeys, setSelectedRowKeys] = useState<Array<string | number>>([])

  const {
    tableData,
    loading,
    pagination,
    searchForm,
    onSearchFormChange,
    loadData,
    handleSearch,
    handleReset,
    handleSortChange,
    refresh,
  } = useListPage<OnlineAdminRow>({
    fetchApi: getOnlineAdminList,
    initialSearchForm: { username: '', ip: '', browser: '', os: '' },
    fieldMapping: { last_active: 'last_used_at' },
    defaultSort: 'last_used_at:desc',
    normalizeRows: false,
    transformData: (row) => {
      const record = row
      return {
        id: entityField(record, 'id', '')!,
        username: String(entityField(record, 'username', '') ?? ''),
        nickname: String(entityField(record, 'nickname', '') ?? ''),
        avatar: String(entityField(record, 'avatar', '') ?? ''),
        browser: String(entityField(record, 'browser', '') ?? ''),
        ip: String(entityField(record, 'ip', '') ?? ''),
        os: String(entityField(record, 'os', '') ?? ''),
        session_id: String(entityField(record, 'session_id', '') ?? ''),
        last_active: String(
          entityField(record, 'last_active', '') ?? entityField(record, 'last_used_at', '') ?? '',
        ),
        name: String(entityField(record, 'username', '') ?? ''),
      }
    },
  })

  const { toolbar } = useCrudActions({ onRefresh: refresh })

  const handleKickOut = (row: OnlineAdminRow) => {
    modal.confirm({
      title: t('common.confirm'),
      content: t('online_admin.kick_out_confirm', { username: row.username }),
      okType: 'danger',
      onOk: async () => {
        try {
          await kickOutOnlineAdmin(row.id)
          message.success(t('online_admin.kick_out_success'))
          await refresh()
        } catch (error) {
          showError(error, t('online_admin.kick_out_failed'))
        }
      },
    })
  }

  const handleBatchKickOut = () => {
    if (!selectedRowKeys.length) return
    modal.confirm({
      title: t('common.confirm'),
      content: t('online_admin.batch_kick_out_confirm', { count: selectedRowKeys.length }),
      okType: 'danger',
      onOk: async () => {
        try {
          await batchKickOutOnlineAdmins(selectedRowKeys)
          message.success(t('online_admin.batch_kick_out_success'))
          setSelectedRowKeys([])
          await refresh()
        } catch (error) {
          showError(error, t('online_admin.batch_kick_out_failed'))
        }
      },
    })
  }

  const columns: ColumnsType<OnlineAdminRow> = [
    { title: t('online_admin.username'), dataIndex: 'username', width: 120 },
    { title: t('online_admin.nickname'), dataIndex: 'nickname', width: 120 },
    {
      title: t('online_admin.avatar'),
      dataIndex: 'avatar',
      width: 80,
      render: (_, row) => (
        <Avatar src={row.avatar || undefined} size={32}>
          {row.nickname?.charAt(0) || row.username?.charAt(0) || 'U'}
        </Avatar>
      ),
    },
    { title: t('online_admin.browser'), dataIndex: 'browser', width: 150 },
    { title: t('online_admin.ip'), dataIndex: 'ip', width: 150 },
    { title: t('online_admin.os'), dataIndex: 'os', width: 150 },
    { title: t('online_admin.session_id'), dataIndex: 'session_id', width: 200, ellipsis: true },
    {
      title: t('online_admin.last_active'),
      dataIndex: 'last_active',
      width: 180,
      sorter: true,
      render: (time: string) => formatOnlineTime(time),
    },
    {
      title: t('common.operation'),
      key: 'operation',
      width: 120,
      fixed: 'right',
      render: (_, row) =>
        getButtonState('admin.kick_out').show ? (
          <PermissionButton permission="admin.kick_out" type="link" danger onClick={() => handleKickOut(row)}>
            {t('online_admin.kick_out')}
          </PermissionButton>
        ) : null,
    },
  ]

  const {
    filteredColumns,
    open: columnSettingOpen,
    openColumnSetting,
    closeColumnSetting,
    allColumns,
    visibleColumns,
    columnOrder,
    fixedColumns,
    handleConfirm: handleColumnSettingConfirm,
  } = useColumnSetting('online_admin', columns)

  return (
    <PageContainer
      title={t('menu.online_admin')}
      extra={
        <Space>
          {selectedRowKeys.length > 0 && getButtonState('admin.kick_out').show ? (
            <Button danger onClick={handleBatchKickOut}>
              {t('online_admin.batch_kick_out')} ({selectedRowKeys.length})
            </Button>
          ) : null}
          {toolbar}
          <Button icon={<SettingOutlined />} onClick={openColumnSetting}>
            {t('common.column_setting')}
          </Button>
        </Space>
      }
    >
      <SearchForm
        fields={[
          { name: 'username', label: t('online_admin.username') },
          { name: 'ip', label: t('online_admin.ip') },
          { name: 'browser', label: t('online_admin.browser') },
          { name: 'os', label: t('online_admin.os') },
        ]}
        values={searchForm}
        onChange={onSearchFormChange}
        onSearch={handleSearch}
        onReset={handleReset}
      />
      <Table<OnlineAdminRow>
        rowKey="id"
        loading={loading}
        columns={filteredColumns}
        dataSource={tableData}
        scroll={{ x: 1200 }}
        rowSelection={{
          selectedRowKeys,
          onChange: (keys) => setSelectedRowKeys(keys as Array<string | number>),
        }}
        pagination={{
          current: pagination.page,
          pageSize: pagination.pageSize,
          total: pagination.total,
          showSizeChanger: true,
          showTotal: (total) => t('common.total', { total }),
        }}
        onChange={(pager: TablePaginationConfig, _f, sorter) => {
          const sort = Array.isArray(sorter) ? sorter[0] : sorter
          const sortObj = sort as { field?: string; order?: 'ascend' | 'descend' | null; column?: unknown }
          if (sortObj?.column && sortObj.field) {
            handleSortChange(String(sortObj.field), sortObj.order)
            return
          }
          void loadData({
            currentPage: pager.current || 1,
            pageSize: pager.pageSize || pagination.pageSize,
          })
        }}
      />
      <ColumnSettingDialog
        open={columnSettingOpen}
        onClose={closeColumnSetting}
        allColumns={allColumns}
        visibleColumns={visibleColumns}
        columnOrder={columnOrder}
        fixedColumns={fixedColumns}
        onConfirm={handleColumnSettingConfirm}
      />
    </PageContainer>
  )
}

// html/src/views/onlineAdmin/OnlineAdminList.vue
<template>
  <div class="online-admin-list">
    <el-card>
      <template #header>
        <div class="card-header">
          <span>{{ t('menu.online_admin') }}</span>
        </div>
      </template>

      <!-- 搜索 -->
      <SearchForm
        :model="searchForm"
        :fields="searchFields"
        :initial-values="initialSearchForm"
        i18n-prefix="online_admin"
        @search="handleSearch"
        @reset="handleReset"
      />

      <!-- 表格工具栏 -->
      <TableToolbar
        :on-refresh="handleRefresh"
        :visible-columns="visibleColumns"
        :all-columns="allColumns"
        :default-visible-columns="defaultVisibleColumns"
        :column-order="columnOrder"
        :fixed-columns="fixedColumns"
        :on-column-setting-confirm="handleColumnSettingConfirm"
      >
        <template #left>
          <el-button
            type="danger"
            :disabled="selectedRows.length === 0 || getButtonState('admin.kick_out').disabled"
            @click="handleBatchKickOut"
          >
            <el-icon><Delete /></el-icon>
            {{ t('online_admin.batch_kick_out') }}
          </el-button>
        </template>
      </TableToolbar>

      <!-- 表格 -->
      <VxeTable
        ref="tableRef"
        :key="`table-${tableColumns.length}-${JSON.stringify(tableColumns.map(c => c.field || c.slot || c.key))}`"
        :data="tableData"
        :loading="loading"
        :columns="tableColumns"
        :height="600"
        @sort-change="handleSortChange"
        @checkbox-change="handleCheckboxChange"
        @checkbox-all="handleCheckboxAll"
      >
        <template #avatar="{ row }">
          <el-avatar :size="32" :src="row.avatar">
            {{ row.nickname ? row.nickname.charAt(0) : (row.username ? row.username.charAt(0) : 'U') }}
          </el-avatar>
        </template>

        <template #last_active="{ row }">
          {{ formatTime(row.last_active) }}
        </template>

        <template #operation="{ row }">
          <el-button 
            type="danger" 
            link 
            :disabled="getButtonState('admin.kick_out').disabled"
            @click="handleKickOut(row)"
          >
            {{ $t('online_admin.kick_out') }}
          </el-button>
        </template>
      </VxeTable>

      <!-- 分页 -->
      <Pagination
        v-model="pagination"
        :auto-load="true"
        :on-page-change="loadData"
      />
    </el-card>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Delete } from '@element-plus/icons-vue'
import { useI18n } from 'vue-i18n'

import SearchForm from '@/components/SearchForm.vue'
import Pagination from '@/components/Pagination.vue'
import VxeTable from '@/components/VxeTable.vue'
import TableToolbar from '@/components/TableToolbar.vue'
import { useColumnSetting } from '@/composables/useColumnSetting'
import { usePermission } from '@/composables/usePermission'
import { useListPage } from '@/composables/useListPage'
import {
  getOnlineAdminList,
  kickOutOnlineAdmin,
  batchKickOutOnlineAdmins
} from '@/api/onlineAdmin'

/* ================= 基础 ================= */

const { t } = useI18n()
const { getButtonState } = usePermission()

const tableRef = ref(null)
const selectedRows = ref([])

/* ================= 列表逻辑 ================= */

const {
  pagination,
  tableData,
  loading,
  searchForm,
  loadData,
  handleSearch,
  handleReset,
  handleSortChange,
  initDefaultSort
} = useListPage({
  fetchApi: getOnlineAdminList,
  initialSearchForm: {
    username: '',
    ip: '',
    browser: '',
    os: ''
  },
  fieldMapping: {
    last_active: 'last_used_at'
  },
  defaultSort: 'last_used_at:desc',
  tableRef: computed(() => tableRef.value)
})

/* ================= 搜索 ================= */

const initialSearchForm = {
  username: '',
  ip: '',
  browser: '',
  os: ''
}

const searchFields = computed(() => [
  { prop: 'username', label: t('online_admin.username'), type: 'input', width: '200px' },
  { prop: 'ip', label: t('online_admin.ip'), type: 'input', width: '200px' },
  { prop: 'browser', label: t('online_admin.browser'), type: 'input', width: '200px' },
  { prop: 'os', label: t('online_admin.os'), type: 'input', width: '200px' }
])

/* ================= 表格列 ================= */

// 所有列的完整配置（用于列设置）
const allTableColumns = computed(() => [
  { type: 'checkbox', width: 50, fixed: 'left', key: 'checkbox' },
  {
    field: 'username',
    title: t('online_admin.username'),
    width: 120,
    sortable: false,
    key: 'username'
  },
  {
    field: 'nickname',
    title: t('online_admin.nickname'),
    width: 120,
    sortable: false,
    key: 'nickname'
  },
  {
    field: 'avatar',
    title: t('online_admin.avatar'),
    width: 80,
    slot: 'avatar',
    key: 'avatar'
  },
  {
    field: 'browser',
    title: t('online_admin.browser'),
    width: 150,
    sortable: false,
    key: 'browser'
  },
  {
    field: 'ip',
    title: t('online_admin.ip'),
    width: 150,
    sortable: false,
    key: 'ip'
  },
  {
    field: 'os',
    title: t('online_admin.os'),
    width: 150,
    sortable: false,
    key: 'os'
  },
  {
    field: 'session_id',
    title: t('online_admin.session_id'),
    width: 200,
    key: 'session_id'
  },
  {
    field: 'last_active',
    title: t('online_admin.last_active'),
    width: 180,
    sortable: true,
    slot: 'last_active',
    key: 'last_active'
  },
  {
    title: t('common.operation'),
    width: 120,
    fixed: 'right',
    slot: 'operation',
    key: 'operation'
  }
])

// 使用列设置 composable
const {
  tableColumns,
  visibleColumns,
  allColumns,
  defaultVisibleColumns,
  columnOrder,
  fixedColumns,
  handleColumnSettingConfirm
} = useColumnSetting('online_admin', allTableColumns)

/* ================= 勾选 ================= */

const handleCheckboxChange = ({ records }) => {
  selectedRows.value = records || []
}

const handleCheckboxAll = ({ records }) => {
  selectedRows.value = records || []
}

/* ================= 操作 ================= */

const handleKickOut = async (row) => {
  try {
    await ElMessageBox.confirm(
      t('online_admin.kick_out_confirm', { username: row.username }),
      t('common.confirm'),
      { type: 'warning' }
    )
    await kickOutOnlineAdmin(row.id)
    ElMessage.success(t('online_admin.kick_out_success'))
    loadData()
  } catch {}
}

const handleBatchKickOut = async () => {
  if (!selectedRows.value.length) return
  try {
    await ElMessageBox.confirm(
      t('online_admin.batch_kick_out_confirm', {
        count: selectedRows.value.length
      }),
      t('common.confirm'),
      { type: 'warning' }
    )
    await batchKickOutOnlineAdmins(selectedRows.value.map(i => i.id))
    ElMessage.success(t('online_admin.batch_kick_out_success'))
    selectedRows.value = []
    loadData()
  } catch {}
}

/* ================= 工具 ================= */

const formatTime = (time) => {
  if (!time) return '-'
  const d = new Date(time)
  if (isNaN(d.getTime())) return time
  return d.toLocaleString().replace(/\//g, '-')
}

// 处理刷新
const handleRefresh = () => {
  loadData()
}

onMounted(() => {
  initDefaultSort()
  loadData()
})
</script>

<style scoped>
.online-admin-list {
  padding: 20px;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}
</style>
