// html/src/views/profile/Profile.vue
<template>
  <div class="profile-container">
    <el-row :gutter="20">
      <el-col :span="8">
        <el-card class="profile-card">
          <template #header>
            <div class="card-header">
              <span>{{ $t('profile.basic_info') }}</span>
            </div>
          </template>
          <div class="avatar-section">
            <el-avatar :size="100" :src="adminInfo.avatar" class="avatar">
              <el-icon><User /></el-icon>
            </el-avatar>
            <div class="avatar-actions">
              <el-button type="primary" link @click="handleOpenAvatarDialog">
                {{ $t('profile.change_avatar') }}
              </el-button>
            </div>
          </div>
          <el-descriptions :column="1" border class="info-descriptions">
            <el-descriptions-item :label="$t('profile.username')">
              {{ adminInfo.username }}
            </el-descriptions-item>
            <el-descriptions-item :label="$t('profile.nickname')">
              {{ adminInfo.nickname || '-' }}
            </el-descriptions-item>
            <el-descriptions-item :label="$t('profile.email')">
              {{ adminInfo.email || '-' }}
            </el-descriptions-item>
            <el-descriptions-item :label="$t('profile.phone')">
              {{ adminInfo.phone || '-' }}
            </el-descriptions-item>
            <el-descriptions-item :label="$t('profile.department')">
              {{ (adminInfo.department && adminInfo.department.name) ? adminInfo.department.name : '-' }}
            </el-descriptions-item>
            <el-descriptions-item :label="$t('profile.roles')">
              <template v-if="adminInfo.roles && adminInfo.roles.length > 0">
                <el-tag
                  v-for="role in adminInfo.roles"
                  :key="role.id"
                  style="margin-right: 5px;"
                >
                  {{ role.name }}
                </el-tag>
              </template>
              <span v-else>-</span>
            </el-descriptions-item>
          </el-descriptions>
        </el-card>
      </el-col>

      <el-col :span="16">
        <el-card>
          <el-tabs v-model="activeTab">
            <el-tab-pane :label="$t('profile.edit_info')" name="info">
              <el-form
                ref="infoFormRef"
                :model="infoForm"
                :rules="infoRules"
                label-width="120px"
                style="max-width: 600px;"
              >
                <el-form-item :label="$t('profile.nickname')" prop="nickname">
                  <el-input v-model="infoForm.nickname" />
                </el-form-item>
                <el-form-item :label="$t('profile.email')" prop="email">
                  <el-input v-model="infoForm.email" type="email" />
                </el-form-item>
                <el-form-item :label="$t('profile.phone')" prop="phone">
                  <el-input v-model="infoForm.phone" />
                </el-form-item>
                <el-form-item>
                  <el-button type="primary" @click="handleUpdateInfo" :loading="infoSubmitting">
                    {{ $t('common.save') }}
                  </el-button>
                  <el-button @click="handleResetInfo">{{ $t('common.reset') }}</el-button>
                </el-form-item>
              </el-form>
            </el-tab-pane>

            <el-tab-pane :label="$t('profile.change_password')" name="password">
              <el-form
                ref="passwordFormRef"
                :model="passwordForm"
                :rules="passwordRules"
                label-width="120px"
                style="max-width: 600px;"
              >
                <el-form-item :label="$t('profile.old_password')" prop="old_password">
                  <el-input
                    v-model="passwordForm.old_password"
                    type="password"
                    show-password
                  />
                </el-form-item>
                <el-form-item :label="$t('profile.new_password')" prop="new_password">
                  <el-input
                    v-model="passwordForm.new_password"
                    type="password"
                    show-password
                  />
                </el-form-item>
                <el-form-item :label="$t('profile.confirm_password')" prop="confirm_password">
                  <el-input
                    v-model="passwordForm.confirm_password"
                    type="password"
                    show-password
                  />
                </el-form-item>
                <el-form-item>
                  <el-button type="primary" @click="handleUpdatePassword" :loading="passwordSubmitting">
                    {{ $t('common.save') }}
                  </el-button>
                  <el-button @click="handleResetPassword">{{ $t('common.reset') }}</el-button>
                </el-form-item>
              </el-form>
            </el-tab-pane>

            <el-tab-pane :label="$t('profile.google_authenticator')" name="2fa">
              <div class="google-authenticator-section">
                <el-alert
                  v-if="!googleAuthStatus.is_bound"
                  :title="$t('profile.google_auth_not_bound')"
                  type="info"
                  :closable="false"
                  show-icon
                  style="margin-bottom: 20px;"
                />
                <el-alert
                  v-else
                  :title="$t('profile.google_auth_bound')"
                  type="success"
                  :closable="false"
                  show-icon
                  style="margin-bottom: 20px;"
                />

                <div v-if="!googleAuthStatus.is_bound" class="bind-section">
                  <el-steps :active="bindStep" finish-status="success" style="margin-bottom: 30px;">
                    <el-step :title="$t('profile.step1_scan_qr')" />
                    <el-step :title="$t('profile.step2_verify')" />
                  </el-steps>

                  <div v-if="bindStep === 0" class="qr-code-section">
                    <el-alert
                      :title="$t('profile.scan_qr_tip')"
                      type="warning"
                      :closable="false"
                      show-icon
                      style="margin-bottom: 20px;"
                    />
                    <div class="qr-code-container">
                      <div v-if="qrCodeLoading" class="loading-container">
                        <el-icon class="is-loading"><Loading /></el-icon>
                        <span>{{ $t('common.loading') }}</span>
                      </div>
                      <div v-else-if="qrCodeData.qr_code_image" class="qr-code-wrapper">
                        <img :src="qrCodeData.qr_code_image" alt="QR Code" class="qr-code-image" />
                        <div class="qr-code-info">
                          <p><strong>{{ $t('profile.secret_key') }}:</strong> {{ qrCodeData.secret }}</p>
                          <p class="tip-text">{{ $t('profile.save_secret_tip') }}</p>
                        </div>
                      </div>
                    </div>
                    <el-button type="primary" @click="bindStep = 1" :disabled="!qrCodeData.secret">
                      {{ $t('profile.next_step') }}
                    </el-button>
                  </div>

                  <div v-if="bindStep === 1" class="verify-section">
                    <el-form
                      ref="bindFormRef"
                      :model="bindForm"
                      :rules="bindRules"
                      label-width="120px"
                      style="max-width: 400px;"
                    >
                      <el-form-item :label="$t('profile.verification_code')" prop="code">
                        <el-input
                          v-model="bindForm.code"
                          :placeholder="$t('profile.enter_6_digit_code')"
                          maxlength="6"
                          style="width: 200px;"
                        />
                      </el-form-item>
                      <el-form-item>
                        <el-button @click="bindStep = 0">{{ $t('common.back') }}</el-button>
                        <el-button type="primary" @click="handleBindGoogleAuth" :loading="bindSubmitting">
                          {{ $t('profile.bind') }}
                        </el-button>
                      </el-form-item>
                    </el-form>
                  </div>
                </div>

                <div v-else class="unbind-section">
                  <el-form
                    ref="unbindFormRef"
                    :model="unbindForm"
                    :rules="unbindRules"
                    label-width="120px"
                    style="max-width: 400px;"
                  >
                    <el-form-item :label="$t('profile.verification_code')" prop="code">
                      <el-input
                        v-model="unbindForm.code"
                        :placeholder="$t('profile.enter_6_digit_code')"
                        maxlength="6"
                        style="width: 200px;"
                      />
                    </el-form-item>
                    <el-form-item>
                      <el-button type="danger" @click="handleUnbindGoogleAuth" :loading="unbindSubmitting">
                        {{ $t('profile.unbind') }}
                      </el-button>
                    </el-form-item>
                  </el-form>
                </div>
              </div>
            </el-tab-pane>
          </el-tabs>
        </el-card>
      </el-col>
    </el-row>

    <!-- 头像选择对话框 -->
    <el-dialog
      v-model="showAvatarDialog"
      :title="$t('profile.change_avatar')"
      width="500px"
    >
      <div class="avatar-selector">
        <div class="avatar-grid">
          <div
            v-for="avatar in defaultAvatars"
            :key="avatar"
            class="avatar-item"
            :class="{ active: selectedAvatar === avatar }"
            @click="selectedAvatar = avatar"
          >
            <el-avatar :size="60" :src="avatar">
              <el-icon><User /></el-icon>
            </el-avatar>
          </div>
        </div>
      </div>
      <template #footer>
        <el-button @click="showAvatarDialog = false">{{ $t('common.cancel') }}</el-button>
        <el-button type="primary" @click="handleSaveAvatar" :loading="avatarSubmitting" :disabled="!selectedAvatar">
          {{ $t('common.confirm') }}
        </el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { ref, reactive, onMounted, computed, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { ElMessage, ElMessageBox } from 'element-plus'
import { User, Plus, Loading } from '@element-plus/icons-vue'
import { getProfile, updateProfile, updatePassword } from '../../api/profile'
import { 
  getGoogleAuthenticatorStatus, 
  getGoogleAuthenticatorQRCode, 
  bindGoogleAuthenticator, 
  unbindGoogleAuthenticator 
} from '../../api/auth'
import { useUserStore } from '../../store/user'

const { t } = useI18n()
const userStore = useUserStore()

const activeTab = ref('info')
const infoFormRef = ref(null)
const passwordFormRef = ref(null)
const infoSubmitting = ref(false)
const passwordSubmitting = ref(false)
const showAvatarDialog = ref(false)
const selectedAvatar = ref('')
const avatarSubmitting = ref(false)

// 谷歌验证码相关
const googleAuthStatus = ref({ is_bound: false })
const qrCodeLoading = ref(false)
const qrCodeData = ref({ secret: '', qr_code_image: '' })
const bindStep = ref(0)
const bindSubmitting = ref(false)
const unbindSubmitting = ref(false)
const bindFormRef = ref(null)
const unbindFormRef = ref(null)

const bindForm = reactive({
  code: ''
})

const unbindForm = reactive({
  code: ''
})

// 系统默认头像列表（使用UI Avatars服务生成）
const defaultAvatars = [
  'https://ui-avatars.com/api/?name=A&background=409EFF&color=fff&size=128', // 蓝色
  'https://ui-avatars.com/api/?name=B&background=67C23A&color=fff&size=128', // 绿色
  'https://ui-avatars.com/api/?name=C&background=E6A23C&color=fff&size=128', // 橙色
  'https://ui-avatars.com/api/?name=D&background=F56C6C&color=fff&size=128', // 红色
  'https://ui-avatars.com/api/?name=E&background=9C27B0&color=fff&size=128', // 紫色
  'https://ui-avatars.com/api/?name=F&background=00BCD4&color=fff&size=128', // 青色
  'https://ui-avatars.com/api/?name=G&background=FF9800&color=fff&size=128', // 深橙色
  'https://ui-avatars.com/api/?name=H&background=4CAF50&color=fff&size=128', // 深绿色
  'https://ui-avatars.com/api/?name=I&background=2196F3&color=fff&size=128', // 亮蓝色
  'https://ui-avatars.com/api/?name=J&background=FF5722&color=fff&size=128', // 深红色
  'https://ui-avatars.com/api/?name=K&background=795548&color=fff&size=128', // 棕色
  'https://ui-avatars.com/api/?name=L&background=607D8B&color=fff&size=128', // 蓝灰色
  'https://ui-avatars.com/api/?name=M&background=3F51B5&color=fff&size=128', // 靛蓝色
  'https://ui-avatars.com/api/?name=N&background=009688&color=fff&size=128', // 青绿色
  'https://ui-avatars.com/api/?name=O&background=FFC107&color=fff&size=128', // 琥珀色
  'https://ui-avatars.com/api/?name=P&background=E91E63&color=fff&size=128', // 粉红色
  'https://ui-avatars.com/api/?name=Q&background=8BC34A&color=fff&size=128', // 浅绿色
  'https://ui-avatars.com/api/?name=R&background=CDDC39&color=fff&size=128', // 黄绿色
  'https://ui-avatars.com/api/?name=S&background=FFEB3B&color=333&size=128', // 黄色
  'https://ui-avatars.com/api/?name=T&background=FF9800&color=fff&size=128', // 橙色
  'https://ui-avatars.com/api/?name=U&background=9E9E9E&color=fff&size=128', // 灰色
  'https://ui-avatars.com/api/?name=V&background=673AB7&color=fff&size=128', // 深紫色
  'https://ui-avatars.com/api/?name=W&background=00ACC1&color=fff&size=128', // 深青色
  'https://ui-avatars.com/api/?name=X&background=5C6BC0&color=fff&size=128', // 蓝紫色
  'https://ui-avatars.com/api/?name=Y&background=F44336&color=fff&size=128', // 亮红色
  'https://ui-avatars.com/api/?name=Z&background=26A69A&color=fff&size=128', // 青蓝色
]

const adminInfo = computed(() => userStore.adminInfo || {})

const infoForm = reactive({
  nickname: '',
  email: '',
  phone: ''
})

const passwordForm = reactive({
  old_password: '',
  new_password: '',
  confirm_password: ''
})

const validateConfirmPassword = (rule, value, callback) => {
  if (value !== passwordForm.new_password) {
    callback(new Error(t('profile.password_not_match')))
  } else {
    callback()
  }
}

const validateEmail = (rule, value, callback) => {
  if (value && value.trim() !== '') {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
    if (!emailRegex.test(value)) {
      callback(new Error(t('profile.email_invalid')))
    } else {
      callback()
    }
  } else {
    callback()
  }
}

const validatePhone = (rule, value, callback) => {
  if (value && value.trim() !== '') {
    const phoneRegex = /^1[3-9]\d{9}$/
    if (!phoneRegex.test(value)) {
      callback(new Error(t('profile.phone_invalid')))
    } else {
      callback()
    }
  } else {
    callback()
  }
}

const infoRules = {
  email: [
    { validator: validateEmail, trigger: 'blur' }
  ],
  phone: [
    { validator: validatePhone, trigger: 'blur' }
  ]
}

const passwordRules = {
  old_password: [
    { required: true, message: t('profile.old_password_required'), trigger: 'blur' }
  ],
  new_password: [
    { required: true, message: t('profile.new_password_required'), trigger: 'blur' },
    { min: 6, message: t('profile.password_length_error'), trigger: 'blur' }
  ],
  confirm_password: [
    { required: true, message: t('profile.confirm_password_required'), trigger: 'blur' },
    { validator: validateConfirmPassword, trigger: 'blur' }
  ]
}

const validateGoogleCode = (rule, value, callback) => {
  if (!value || value.trim() === '') {
    callback(new Error(t('profile.google_code_required')))
  } else if (!/^\d{6}$/.test(value)) {
    callback(new Error(t('profile.google_code_format')))
  } else {
    callback()
  }
}

const bindRules = {
  code: [
    { validator: validateGoogleCode, trigger: 'blur' }
  ]
}

const unbindRules = {
  code: [
    { validator: validateGoogleCode, trigger: 'blur' }
  ]
}

const loadProfile = async () => {
  try {
    const res = await getProfile()
    if (res.data && res.data.admin) {
      const admin = res.data.admin
      
      let department = null
      const dept = admin.Department || admin.department
      
      if (dept) {
        const deptId = dept.ID || dept.id || dept.Id || (dept.ID !== undefined ? dept.ID : null)
        const deptName = dept.Name || dept.name || dept.Name || ''
        
        if (deptId && deptId > 0) {
          department = {
            id: deptId,
            name: deptName || '-'
          }
        } else if (deptName && deptName !== '') {
          department = {
            id: 0,
            name: deptName
          }
        }
      }
      
      if (!department && (admin.DepartmentID || admin.department_id)) {
        const deptId = admin.DepartmentID || admin.department_id
        if (deptId && deptId > 0) {
          department = {
            id: deptId,
            name: '-'
          }
        }
      }
      
      const rolesArray = admin.Roles || admin.roles || []
      const roleMap = new Map()
      rolesArray.forEach(role => {
        const roleId = role.ID || role.id
        if (roleId && !roleMap.has(roleId)) {
          roleMap.set(roleId, {
            id: roleId,
            name: role.Name || role.name,
            slug: role.Slug || role.slug
          })
        }
      })
      const uniqueRoles = Array.from(roleMap.values())
      
      const transformedAdmin = {
        id: admin.ID || admin.id,
        username: admin.Username || admin.username,
        nickname: admin.Nickname || admin.nickname,
        email: admin.Email || admin.email,
        phone: admin.Phone || admin.phone,
        avatar: admin.Avatar || admin.avatar,
        department_id: admin.DepartmentID || admin.department_id,
        department: department,
        roles: uniqueRoles
      }
      
      infoForm.nickname = transformedAdmin.nickname || ''
      infoForm.email = transformedAdmin.email || ''
      infoForm.phone = transformedAdmin.phone || ''
      userStore.setAdminInfo(transformedAdmin)
    }
  } catch (error) {
    console.error('Load profile error:', error)
    // 如果错误已经在响应拦截器中处理过，就不再重复显示
    if (!error.__handled) {
      const errorMessage = error.response?.data?.message || error.message || t('common.operation_failed')
      ElMessage.error(errorMessage)
    }
  }
}

const handleUpdateInfo = async () => {
  if (!infoFormRef.value) return

  await infoFormRef.value.validate(async (valid) => {
    if (valid) {
      infoSubmitting.value = true
      try {
        const res = await updateProfile(infoForm)
        if (res.data && res.data.admin) {
          const admin = res.data.admin
          
          // 处理部门数据
          let department = null
          const dept = admin.Department || admin.department
          if (dept) {
            const deptId = dept.ID || dept.id || dept.Id
            const deptName = dept.Name || dept.name || dept.Name
            if (deptId && deptId > 0) {
              department = {
                id: deptId,
                name: deptName || '-'
              }
            }
          }
          
          // 如果部门数据为空，但 department_id 存在，尝试从 department_id 获取
          if (!department && (admin.DepartmentID || admin.department_id)) {
            const deptId = admin.DepartmentID || admin.department_id
            if (deptId && deptId > 0) {
              department = {
                id: deptId,
                name: '-' // 暂时显示 '-'，后续可以从部门列表获取名称
              }
            }
          }
          
          // 处理角色数据（去重）
          const rolesArray = admin.Roles || admin.roles || []
          const roleMap = new Map()
          rolesArray.forEach(role => {
            const roleId = role.ID || role.id
            if (roleId && !roleMap.has(roleId)) {
              roleMap.set(roleId, {
                id: roleId,
                name: role.Name || role.name,
                slug: role.Slug || role.slug
              })
            }
          })
          const uniqueRoles = Array.from(roleMap.values())
          
          // 转换数据格式（PascalCase -> snake_case）
          const transformedAdmin = {
            id: admin.ID || admin.id,
            username: admin.Username || admin.username,
            nickname: admin.Nickname || admin.nickname,
            email: admin.Email || admin.email,
            phone: admin.Phone || admin.phone,
            avatar: admin.Avatar || admin.avatar,
            department_id: admin.DepartmentID || admin.department_id,
            department: department,
            roles: uniqueRoles
          }
          
          userStore.setAdminInfo(transformedAdmin)
          ElMessage.success(t('profile.update_success'))
          // 重新获取用户信息（包括权限），确保权限信息不会丢失
          await userStore.fetchUserInfo(true)
        }
      } catch (error) {
        console.error('Update info error:', error)
        // 如果错误已经在响应拦截器中处理过，就不再重复显示
        if (!error.__handled) {
          const errorMessage = error.response?.data?.message || error.message || t('common.operation_failed')
          ElMessage.error(errorMessage)
        }
      } finally {
        infoSubmitting.value = false
      }
    }
  })
}

const handleResetInfo = () => {
  loadProfile()
  infoFormRef.value?.resetFields()
}

const handleUpdatePassword = async () => {
  if (!passwordFormRef.value) return

  await passwordFormRef.value.validate(async (valid) => {
    if (valid) {
      passwordSubmitting.value = true
      try {
        await updatePassword(passwordForm)
        ElMessage.success(t('profile.password_update_success'))
        handleResetPassword()
        // 重新获取用户信息（包括权限），确保权限信息不会丢失
        await userStore.fetchUserInfo(true)
      } catch (error) {
        console.error('Update password error:', error)
        // 如果错误已经在响应拦截器中处理过，就不再重复显示
        if (!error.__handled) {
          const errorMessage = error.response?.data?.message || error.message || t('common.operation_failed')
          ElMessage.error(errorMessage)
        }
      } finally {
        passwordSubmitting.value = false
      }
    }
  })
}

const handleResetPassword = () => {
  passwordForm.old_password = ''
  passwordForm.new_password = ''
  passwordForm.confirm_password = ''
  passwordFormRef.value?.resetFields()
}

const handleOpenAvatarDialog = () => {
  // 打开对话框时，如果已有头像，设置为选中状态
  selectedAvatar.value = adminInfo.value.avatar || ''
  showAvatarDialog.value = true
}

const handleSaveAvatar = async () => {
  if (!selectedAvatar.value) {
    ElMessage.warning(t('profile.please_select_avatar'))
    return
  }

  avatarSubmitting.value = true
  try {
    await updateProfile({ avatar: selectedAvatar.value })
    await loadProfile()
    ElMessage.success(t('profile.avatar_update_success'))
    showAvatarDialog.value = false
    selectedAvatar.value = ''
    // 重新获取用户信息（包括权限），确保权限信息不会丢失
    await userStore.fetchUserInfo(true)
  } catch (error) {
    console.error('Update avatar error:', error)
    // 如果错误已经在响应拦截器中处理过，就不再重复显示
    if (!error.__handled) {
      const errorMessage = error.response?.data?.message || error.message || t('common.operation_failed')
      ElMessage.error(errorMessage)
    }
  } finally {
    avatarSubmitting.value = false
  }
}

// 加载谷歌验证码状态
const loadGoogleAuthStatus = async () => {
  try {
    const res = await getGoogleAuthenticatorStatus()
    if (res.data) {
      googleAuthStatus.value = res.data
    }
  } catch (error) {
    console.error('Load google auth status error:', error)
    // 如果错误已经在响应拦截器中处理过，就不再重复显示
    if (!error.__handled) {
      const errorMessage = error.response?.data?.message || error.message || t('common.operation_failed')
      ElMessage.error(errorMessage)
    }
  }
}

// 加载二维码
const loadQRCode = async () => {
  qrCodeLoading.value = true
  try {
    const res = await getGoogleAuthenticatorQRCode()
    if (res.data) {
      qrCodeData.value = res.data
    }
  } catch (error) {
    console.error('Load QR code error:', error)
    // 如果错误已经在拦截器中处理过，不再重复显示
    if (!error?.__handled) {
      const errorMessage = error.response?.data?.message || error.translatedMessage || error.message || t('common.operation_failed')
      ElMessage.error(errorMessage)
    }
  } finally {
    qrCodeLoading.value = false
  }
}

// 绑定谷歌验证码
const handleBindGoogleAuth = async () => {
  if (!bindFormRef.value) return

  await bindFormRef.value.validate(async (valid) => {
    if (valid) {
      bindSubmitting.value = true
      try {
        await bindGoogleAuthenticator({
          secret: qrCodeData.value.secret,
          code: bindForm.code
        })
        ElMessage.success(t('profile.bind_success'))
        bindForm.code = ''
        bindStep.value = 0
        await loadGoogleAuthStatus()
      } catch (error) {
        console.error('Bind google auth error:', error)
        // 如果错误已经在拦截器中处理过，不再重复显示
        if (!error?.__handled) {
          const errorMessage = error.response?.data?.message || error.translatedMessage || error.message || t('common.operation_failed')
          ElMessage.error(errorMessage)
        }
      } finally {
        bindSubmitting.value = false
      }
    }
  })
}

// 解绑谷歌验证码
const handleUnbindGoogleAuth = async () => {
  if (!unbindFormRef.value) return

  await unbindFormRef.value.validate(async (valid) => {
    if (valid) {
      try {
        await ElMessageBox.confirm(
          t('profile.unbind_confirm'),
          t('common.confirm'),
          {
            confirmButtonText: t('common.confirm'),
            cancelButtonText: t('common.cancel'),
            type: 'warning'
          }
        )
        
        unbindSubmitting.value = true
        try {
          await unbindGoogleAuthenticator({
            code: unbindForm.code
          })
          ElMessage.success(t('profile.unbind_success'))
          unbindForm.code = ''
          await loadGoogleAuthStatus()
        } catch (error) {
          console.error('Unbind google auth error:', error)
          // 如果错误已经在拦截器中处理过，不再重复显示
          if (!error?.__handled) {
            const errorMessage = error.response?.data?.message || error.translatedMessage || error.message || t('common.operation_failed')
            ElMessage.error(errorMessage)
          }
        } finally {
          unbindSubmitting.value = false
        }
      } catch (error) {
        // 用户取消
      }
    }
  })
}

// 监听标签页切换
watch(activeTab, (newTab) => {
  if (newTab === '2fa') {
    loadGoogleAuthStatus()
    if (!googleAuthStatus.value.is_bound && !qrCodeData.value.secret) {
      loadQRCode()
    }
  }
})

onMounted(() => {
  loadProfile()
  loadGoogleAuthStatus()
})
</script>

<style scoped>
.profile-container {
  padding: 0;
}

.profile-card {
  height: 100%;
}

.card-header {
  font-weight: 500;
  font-size: 16px;
}

.avatar-section {
  text-align: center;
  margin-bottom: 20px;
}

.avatar {
  margin-bottom: 10px;
}

.avatar-actions {
  margin-top: 10px;
}

.info-descriptions {
  margin-top: 20px;
}

.avatar-selector {
  padding: 20px 0;
}

.avatar-grid {
  display: grid;
  grid-template-columns: repeat(6, 1fr);
  gap: 15px;
  max-height: 400px;
  overflow-y: auto;
}

.avatar-item {
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 8px;
  border: 2px solid #e4e7ed;
  border-radius: 8px;
  cursor: pointer;
  transition: all 0.3s;
}

.avatar-item:hover {
  border-color: #409EFF;
  transform: scale(1.05);
}

.avatar-item.active {
  border-color: #409EFF;
  background-color: #ecf5ff;
}

.google-authenticator-section {
  padding: 20px 0;
}

.bind-section,
.unbind-section {
  max-width: 600px;
}

.qr-code-section {
  text-align: center;
}

.qr-code-container {
  margin: 30px 0;
}

.loading-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 40px;
  gap: 10px;
}

.qr-code-wrapper {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 20px;
  padding: 20px;
  background: #f5f7fa;
  border-radius: 8px;
  margin-bottom: 20px;
}

.qr-code-image {
  width: 200px;
  height: 200px;
  border: 1px solid #e4e7ed;
  border-radius: 8px;
  background: white;
  padding: 10px;
}

.qr-code-info {
  text-align: left;
  width: 100%;
  max-width: 400px;
}

.qr-code-info p {
  margin: 8px 0;
  word-break: break-all;
}

.tip-text {
  color: #909399;
  font-size: 12px;
  margin-top: 10px !important;
}

.verify-section {
  padding: 20px 0;
}
</style>

<style>
/* 个人中心谷歌验证码设置页夜间模式适配 - 需要非 scoped 样式来覆盖组件内部样式 */
.dark-mode .qr-code-wrapper {
  background-color: var(--bg-color-tertiary) !important;
}

.dark-mode .qr-code-image {
  background-color: var(--card-bg) !important;
  border-color: var(--border-color-light) !important;
}

.dark-mode .qr-code-info {
  color: var(--text-color-primary) !important;
}

.dark-mode .qr-code-info p {
  color: var(--text-color-primary) !important;
}

.dark-mode .qr-code-info strong {
  color: var(--text-color-primary) !important;
}

.dark-mode .tip-text {
  color: var(--text-color-secondary) !important;
}
</style>

// html-react/src/pages/profile/Profile.tsx
import { useEffect, useState } from 'react'
import { App, Alert, Avatar, Button, Card, Form, Input, Modal, Space, Spin, Steps, Tabs, Typography } from 'antd'
import { LoadingOutlined, UserOutlined } from '@ant-design/icons'
import { useTranslation } from 'react-i18next'
import { updatePassword, updateProfile } from '@/api/profile'
import {
  bindGoogleAuthenticator,
  getGoogleAuthenticatorQRCode,
  getGoogleAuthenticatorStatus,
  unbindGoogleAuthenticator,
} from '@/api/auth'
import { useUserStore } from '@/stores/user'
import { useUnhandledError } from '@/hooks/useUnhandledError'
import PageContainer from '@/components/PageContainer'
import './Profile.scss'

type GoogleAuthQrData = {
  secret?: string
  qrCodeImage?: string
}

const DEFAULT_AVATARS = [
  'https://ui-avatars.com/api/?name=A&background=409EFF&color=fff&size=128',
  'https://ui-avatars.com/api/?name=B&background=67C23A&color=fff&size=128',
  'https://ui-avatars.com/api/?name=C&background=E6A23C&color=fff&size=128',
  'https://ui-avatars.com/api/?name=D&background=F56C6C&color=fff&size=128',
  'https://ui-avatars.com/api/?name=E&background=9C27B0&color=fff&size=128',
  'https://ui-avatars.com/api/?name=F&background=00BCD4&color=fff&size=128',
  'https://ui-avatars.com/api/?name=G&background=FF9800&color=fff&size=128',
  'https://ui-avatars.com/api/?name=H&background=4CAF50&color=fff&size=128',
  'https://ui-avatars.com/api/?name=I&background=2196F3&color=fff&size=128',
  'https://ui-avatars.com/api/?name=J&background=FF5722&color=fff&size=128',
  'https://ui-avatars.com/api/?name=K&background=795548&color=fff&size=128',
  'https://ui-avatars.com/api/?name=L&background=607D8B&color=fff&size=128',
  'https://ui-avatars.com/api/?name=M&background=3F51B5&color=fff&size=128',
  'https://ui-avatars.com/api/?name=N&background=009688&color=fff&size=128',
  'https://ui-avatars.com/api/?name=O&background=FFC107&color=333&size=128',
  'https://ui-avatars.com/api/?name=P&background=E91E63&color=fff&size=128',
  'https://ui-avatars.com/api/?name=Q&background=8BC34A&color=fff&size=128',
  'https://ui-avatars.com/api/?name=R&background=CDDC39&color=fff&size=128',
  'https://ui-avatars.com/api/?name=S&background=FFEB3B&color=333&size=128',
  'https://ui-avatars.com/api/?name=T&background=FF9800&color=fff&size=128',
  'https://ui-avatars.com/api/?name=U&background=9E9E9E&color=fff&size=128',
  'https://ui-avatars.com/api/?name=V&background=673AB7&color=fff&size=128',
  'https://ui-avatars.com/api/?name=W&background=00ACC1&color=fff&size=128',
  'https://ui-avatars.com/api/?name=X&background=5C6BC0&color=fff&size=128',
  'https://ui-avatars.com/api/?name=Y&background=F44336&color=fff&size=128',
  'https://ui-avatars.com/api/?name=Z&background=26A69A&color=fff&size=128',
]

export default function ProfilePage() {
  const { t } = useTranslation()
  const { message } = App.useApp()
  const showError = useUnhandledError()
  const adminInfo = useUserStore((s) => s.adminInfo)
  const fetchUserInfo = useUserStore((s) => s.fetchUserInfo)
  const [profileForm] = Form.useForm()
  const [passwordForm] = Form.useForm()
  const [bindForm] = Form.useForm()
  const [unbindForm] = Form.useForm()
  const [savingProfile, setSavingProfile] = useState(false)
  const [savingPassword, setSavingPassword] = useState(false)
  const [bound, setBound] = useState(false)
  const [qr, setQr] = useState<GoogleAuthQrData>({})
  const [loading2fa, setLoading2fa] = useState(false)
  const [bindStep, setBindStep] = useState(0)
  const [binding, setBinding] = useState(false)
  const [unbinding, setUnbinding] = useState(false)
  const [avatarOpen, setAvatarOpen] = useState(false)
  const [selectedAvatar, setSelectedAvatar] = useState('')
  const [savingAvatar, setSavingAvatar] = useState(false)

  useEffect(() => {
    profileForm.setFieldsValue({
      nickname: adminInfo?.nickname || '',
      email: adminInfo?.email || '',
      phone: adminInfo?.phone || '',
    })
  }, [adminInfo, profileForm])

  const load2fa = async () => {
    setLoading2fa(true)
    try {
      const statusRes = await getGoogleAuthenticatorStatus()
      const isBound = !!(statusRes.data as { is_bound?: boolean } | undefined)?.is_bound
      setBound(isBound)
      if (!isBound) {
        const qrRes = await getGoogleAuthenticatorQRCode()
        const data = qrRes.data as {
          secret?: string
          qr_code_image?: string
          qr_code_url?: string
        }
        setQr({
          secret: data?.secret,
          qrCodeImage: data?.qr_code_image,
        })
        setBindStep(0)
      } else {
        setQr({})
        setBindStep(0)
      }
    } catch (error) {
      showError(error, t('common.query_failed'))
    } finally {
      setLoading2fa(false)
    }
  }

  const handleProfileSave = async () => {
    try {
      const values = await profileForm.validateFields()
      setSavingProfile(true)
      await updateProfile(values)
      message.success(t('common.update_success'))
      await fetchUserInfo(true)
    } catch (error) {
      if ((error as { errorFields?: unknown })?.errorFields) return
      showError(error, t('common.operation_failed'))
    } finally {
      setSavingProfile(false)
    }
  }

  const handlePasswordSave = async () => {
    try {
      const values = await passwordForm.validateFields()
      setSavingPassword(true)
      await updatePassword({
        old_password: values.old_password,
        password: values.password,
        password_confirmation: values.password_confirmation,
      })
      message.success(t('common.update_success'))
      passwordForm.resetFields()
    } catch (error) {
      if ((error as { errorFields?: unknown })?.errorFields) return
      showError(error, t('common.operation_failed'))
    } finally {
      setSavingPassword(false)
    }
  }

  const handleBind = async () => {
    if (!qr.secret) {
      message.warning(t('profile.save_secret_tip'))
      return
    }
    try {
      const values = await bindForm.validateFields()
      setBinding(true)
      await bindGoogleAuthenticator({ secret: qr.secret, code: values.code })
      message.success(t('profile.bind_success'))
      bindForm.resetFields()
      setBindStep(0)
      await load2fa()
    } catch (error) {
      if ((error as { errorFields?: unknown })?.errorFields) return
      showError(error, t('profile.bind_failed'))
    } finally {
      setBinding(false)
    }
  }

  const handleUnbind = async () => {
    try {
      const values = await unbindForm.validateFields()
      setUnbinding(true)
      await unbindGoogleAuthenticator({ code: values.code })
      message.success(t('profile.unbind_success'))
      unbindForm.resetFields()
      await load2fa()
    } catch (error) {
      if ((error as { errorFields?: unknown })?.errorFields) return
      showError(error, t('profile.unbind_failed'))
    } finally {
      setUnbinding(false)
    }
  }

  const openAvatarDialog = () => {
    setSelectedAvatar(adminInfo?.avatar || '')
    setAvatarOpen(true)
  }

  const handleSaveAvatar = async () => {
    if (!selectedAvatar) {
      message.warning(t('profile.please_select_avatar'))
      return
    }
    setSavingAvatar(true)
    try {
      await updateProfile({ avatar: selectedAvatar })
      message.success(t('profile.avatar_update_success'))
      setAvatarOpen(false)
      await fetchUserInfo(true)
    } catch (error) {
      showError(error, t('common.operation_failed'))
    } finally {
      setSavingAvatar(false)
    }
  }

  return (
    <PageContainer title={t('menu.profile')}>
      <Card>
        <Tabs
          onChange={(key) => {
            if (key === '2fa') void load2fa()
          }}
          items={[
            {
              key: 'basic',
              label: t('common.basic_info'),
              children: (
                <div style={{ maxWidth: 520 }}>
                  <div style={{ textAlign: 'center', marginBottom: 24 }}>
                    <Avatar size={100} src={adminInfo?.avatar} icon={<UserOutlined />} />
                    <div style={{ marginTop: 12 }}>
                      <Button type="link" onClick={openAvatarDialog}>
                        {t('profile.change_avatar')}
                      </Button>
                    </div>
                  </div>
                  <Form
                    form={profileForm}
                    layout="vertical"
                    onFinish={() => void handleProfileSave()}
                  >
                    <Form.Item label={t('table.username')}>
                      <Input value={adminInfo?.username || ''} disabled />
                    </Form.Item>
                    <Form.Item name="nickname" label={t('table.nickname')}>
                      <Input />
                    </Form.Item>
                    <Form.Item name="email" label={t('table.email')}>
                      <Input />
                    </Form.Item>
                    <Form.Item name="phone" label={t('table.phone')}>
                      <Input />
                    </Form.Item>
                    <Form.Item>
                      <Button type="primary" htmlType="submit" loading={savingProfile}>
                        {t('common.save')}
                      </Button>
                    </Form.Item>
                  </Form>
                </div>
              ),
            },
            {
              key: 'password',
              label: t('common.change_password'),
              children: (
                <Form
                  form={passwordForm}
                  layout="vertical"
                  style={{ maxWidth: 480 }}
                  onFinish={() => void handlePasswordSave()}
                >
                  <Form.Item name="old_password" label={t('common.old_password')} rules={[{ required: true }]}>
                    <Input.Password />
                  </Form.Item>
                  <Form.Item name="password" label={t('common.new_password')} rules={[{ required: true }]}>
                    <Input.Password />
                  </Form.Item>
                  <Form.Item
                    name="password_confirmation"
                    label={t('common.confirm_password')}
                    dependencies={['password']}
                    rules={[
                      { required: true },
                      ({ getFieldValue }) => ({
                        validator(_, value) {
                          if (!value || getFieldValue('password') === value) return Promise.resolve()
                          return Promise.reject(new Error(t('common.password_mismatch')))
                        },
                      }),
                    ]}
                  >
                    <Input.Password />
                  </Form.Item>
                  <Form.Item>
                    <Button type="primary" htmlType="submit" loading={savingPassword}>
                      {t('common.save')}
                    </Button>
                  </Form.Item>
                </Form>
              ),
            },
            {
              key: '2fa',
              label: t('profile.google_authenticator', { defaultValue: '谷歌验证器' }),
              children: (
                <div className="profile-google-auth">
                  {bound ? (
                    <Space direction="vertical" style={{ width: '100%' }} size="middle">
                      <Alert
                        type="success"
                        showIcon
                        message={t('profile.google_auth_bound', { defaultValue: '已绑定谷歌验证器' })}
                      />
                      <Form
                        form={unbindForm}
                        layout="vertical"
                        className="profile-google-auth__verify-form"
                        onFinish={() => void handleUnbind()}
                      >
                        <Form.Item
                          name="code"
                          label={t('profile.verification_code')}
                          rules={[
                            { required: true, message: t('profile.enter_6_digit_code') },
                            { pattern: /^\d{6}$/, message: t('login.google_code_format') },
                          ]}
                        >
                          <Input maxLength={6} placeholder={t('profile.enter_6_digit_code')} />
                        </Form.Item>
                        <Button danger htmlType="submit" loading={unbinding}>
                          {t('profile.unbind')}
                        </Button>
                      </Form>
                    </Space>
                  ) : (
                    <Space direction="vertical" style={{ width: '100%' }} size="middle">
                      <Alert
                        type="info"
                        showIcon
                        message={t('profile.google_auth_not_bound', { defaultValue: '尚未绑定谷歌验证器' })}
                      />
                      <Steps
                        className="profile-google-auth__steps"
                        current={bindStep}
                        items={[
                          { title: t('profile.step1_scan_qr') },
                          { title: t('profile.step2_verify') },
                        ]}
                      />
                      {bindStep === 0 ? (
                        <>
                          <Alert
                            className="profile-google-auth__tip"
                            type="warning"
                            showIcon
                            message={t('profile.scan_qr_tip')}
                          />
                          <div className="profile-google-auth__qr-container">
                            {loading2fa ? (
                              <div className="profile-google-auth__loading">
                                <Spin indicator={<LoadingOutlined spin />} />
                                <span>{t('common.loading')}</span>
                              </div>
                            ) : qr.qrCodeImage ? (
                              <div className="profile-google-auth__qr-wrapper">
                                <img
                                  src={qr.qrCodeImage}
                                  alt="QR Code"
                                  className="profile-google-auth__qr-image"
                                />
                                <div className="profile-google-auth__qr-info">
                                  <p>
                                    <strong>{t('profile.secret_key')}:</strong>{' '}
                                    <Typography.Text code copyable>
                                      {qr.secret}
                                    </Typography.Text>
                                  </p>
                                  <p>{t('profile.save_secret_tip')}</p>
                                </div>
                              </div>
                            ) : (
                              <Typography.Text type="secondary">{t('common.no_data')}</Typography.Text>
                            )}
                          </div>
                          <Space>
                            <Button type="primary" disabled={!qr.secret} onClick={() => setBindStep(1)}>
                              {t('profile.next_step')}
                            </Button>
                            <Button onClick={() => void load2fa()} loading={loading2fa}>
                              {t('common.refresh')}
                            </Button>
                          </Space>
                        </>
                      ) : (
                        <Form
                          form={bindForm}
                          layout="vertical"
                          className="profile-google-auth__verify-form"
                          onFinish={() => void handleBind()}
                        >
                          <Form.Item
                            name="code"
                            label={t('profile.verification_code')}
                            rules={[
                              { required: true, message: t('profile.enter_6_digit_code') },
                              { pattern: /^\d{6}$/, message: t('login.google_code_format') },
                            ]}
                          >
                            <Input maxLength={6} placeholder={t('profile.enter_6_digit_code')} />
                          </Form.Item>
                          <Space>
                            <Button onClick={() => setBindStep(0)}>{t('common.back')}</Button>
                            <Button type="primary" htmlType="submit" loading={binding}>
                              {t('profile.bind')}
                            </Button>
                          </Space>
                        </Form>
                      )}
                    </Space>
                  )}
                </div>
              ),
            },
          ]}
        />
      </Card>

      <Modal
        open={avatarOpen}
        title={t('profile.change_avatar')}
        onCancel={() => setAvatarOpen(false)}
        onOk={() => void handleSaveAvatar()}
        confirmLoading={savingAvatar}
        okButtonProps={{ disabled: !selectedAvatar }}
        width={560}
        destroyOnHidden
      >
        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(6, 1fr)',
            gap: 12,
            maxHeight: 400,
            overflowY: 'auto',
            padding: '8px 0',
          }}
        >
          {DEFAULT_AVATARS.map((avatar) => {
            const active = selectedAvatar === avatar
            return (
              <button
                key={avatar}
                type="button"
                onClick={() => setSelectedAvatar(avatar)}
                style={{
                  padding: 8,
                  borderRadius: 8,
                  border: `2px solid ${active ? 'var(--ant-color-primary)' : 'var(--ant-color-border)'}`,
                  background: active ? 'var(--ant-color-primary-bg)' : 'transparent',
                  cursor: 'pointer',
                }}
              >
                <Avatar size={56} src={avatar} icon={<UserOutlined />} />
              </button>
            )
          })}
        </div>
      </Modal>
    </PageContainer>
  )
}
