// html/src/layouts/components/LayoutLockScreen.vue
<template>
  <el-dialog
    :model-value="lockDialogVisible"
    :title="$t('header.lock_screen')"
    width="420px"
    :close-on-click-modal="false"
    :close-on-press-escape="false"
    append-to-body
    @update:model-value="$emit('update:lockDialogVisible', $event)"
  >
    <el-input
      :model-value="pendingLockPassword"
      type="password"
      show-password
      :name="lockDialogInputName"
      autocomplete="new-password"
      autocorrect="off"
      spellcheck="false"
      :placeholder="$t('header.lock_password_placeholder')"
      @update:model-value="$emit('update:pendingLockPassword', $event)"
      @keyup.enter="$emit('confirm-lock')"
    />
    <div v-if="lockDialogError" class="lock-screen-error">{{ lockDialogError }}</div>
    <template #footer>
      <el-button @click="$emit('update:lockDialogVisible', false)">{{ $t('common.cancel') }}</el-button>
      <el-button type="primary" @click="$emit('confirm-lock')">{{ $t('common.confirm') }}</el-button>
    </template>
  </el-dialog>

  <div v-if="isScreenLocked" class="lock-screen-overlay">
    <div class="lock-screen-card">
      <div class="lock-screen-avatar-wrap">
        <el-avatar
          v-if="userStore.adminInfo?.avatar"
          :size="68"
          :src="userStore.adminInfo.avatar"
        />
        <el-avatar v-else :size="68">
          <el-icon><User /></el-icon>
        </el-avatar>
      </div>
      <div class="lock-screen-title">{{ $t('header.lock_screen_title') }}</div>
      <div class="lock-screen-user">{{ userStore.adminInfo?.nickname || userStore.adminInfo?.username }}</div>
      <el-input
        :model-value="unlockPassword"
        type="password"
        show-password
        class="lock-screen-input"
        autocomplete="new-password"
        :name="lockInputName"
        autocorrect="off"
        spellcheck="false"
        :placeholder="$t('header.lock_password_placeholder')"
        @update:model-value="$emit('update:unlockPassword', $event)"
        @input="$emit('unlock-input')"
        @keyup.enter="$emit('unlock')"
      />
      <div v-if="unlockError" class="lock-screen-error">{{ unlockError }}</div>
      <div class="lock-screen-actions">
        <el-button type="primary" @click="$emit('unlock')">{{ $t('header.unlock') }}</el-button>
        <el-button @click="$emit('go-login')">{{ $t('header.back_to_login') }}</el-button>
      </div>
    </div>
  </div>
</template>

<script setup>
import { User } from '@element-plus/icons-vue'
import { useUserStore } from '@/store/user'

defineProps({
  isScreenLocked: { type: Boolean, default: false },
  lockDialogVisible: { type: Boolean, default: false },
  pendingLockPassword: { type: String, default: '' },
  lockDialogError: { type: String, default: '' },
  unlockPassword: { type: String, default: '' },
  unlockError: { type: String, default: '' },
  lockInputName: { type: String, default: '' },
  lockDialogInputName: { type: String, default: '' }
})

defineEmits([
  'update:lockDialogVisible',
  'update:pendingLockPassword',
  'update:unlockPassword',
  'confirm-lock',
  'unlock-input',
  'unlock',
  'go-login'
])

const userStore = useUserStore()
</script>

// html-react/src/layouts/components/LayoutLockScreen.tsx
import { Avatar, Button, Input, Modal } from 'antd'
import { UserOutlined } from '@ant-design/icons'
import { useTranslation } from 'react-i18next'
import { useUserStore } from '@/stores/user'
import type { UseLayoutLockScreenReturn } from '@/hooks/useLayoutLockScreen'
import './LayoutLockScreen.scss'

interface LayoutLockScreenProps {
  lockScreen: UseLayoutLockScreenReturn
}

export default function LayoutLockScreen({ lockScreen }: LayoutLockScreenProps) {
  const { t } = useTranslation()
  const adminInfo = useUserStore((s) => s.adminInfo)

  const {
    isScreenLocked,
    lockDialogVisible,
    pendingLockPassword,
    setPendingLockPassword,
    lockDialogError,
    unlockPassword,
    unlockError,
    lockInputName,
    lockDialogInputName,
    cancelLockDialog,
    confirmLockScreen,
    handleUnlockInput,
    handleUnlockScreen,
    goToLogin,
  } = lockScreen

  const displayName = adminInfo?.nickname || adminInfo?.username

  return (
    <>
      <Modal
        title={t('header.lock_screen')}
        open={lockDialogVisible}
        width={420}
        maskClosable={false}
        keyboard={false}
        onCancel={cancelLockDialog}
        onOk={confirmLockScreen}
        okText={t('common.confirm')}
        cancelText={t('common.cancel')}
        destroyOnHidden
      >
        <Input.Password
          value={pendingLockPassword}
          name={lockDialogInputName}
          autoComplete="new-password"
          autoCorrect="off"
          spellCheck={false}
          placeholder={t('header.lock_password_placeholder')}
          onChange={(e) => setPendingLockPassword(e.target.value)}
          onPressEnter={confirmLockScreen}
        />
        {lockDialogError && <div className="lock-screen-error">{lockDialogError}</div>}
      </Modal>

      {isScreenLocked && (
        <div className="lock-screen-overlay">
          <div className="lock-screen-card">
            <div className="lock-screen-avatar-wrap">
              <Avatar size={68} src={adminInfo?.avatar} icon={<UserOutlined />} />
            </div>
            <div className="lock-screen-title">{t('header.lock_screen_title')}</div>
            <div className="lock-screen-user">{displayName}</div>
            <Input.Password
              className="lock-screen-input"
              value={unlockPassword}
              name={lockInputName}
              autoComplete="new-password"
              autoCorrect="off"
              spellCheck={false}
              placeholder={t('header.lock_password_placeholder')}
              onChange={(e) => handleUnlockInput(e.target.value)}
              onPressEnter={handleUnlockScreen}
            />
            {unlockError && <div className="lock-screen-error">{unlockError}</div>}
            <div className="lock-screen-actions">
              <Button type="primary" onClick={handleUnlockScreen}>
                {t('header.unlock')}
              </Button>
              <Button onClick={() => void goToLogin()}>{t('header.back_to_login')}</Button>
            </div>
          </div>
        </div>
      )}
    </>
  )
}
