// html-react/src/pages/attachment/AttachmentList.tsx
﻿import { useEffect, useState } from 'react'
import {
  App,
  Button,
  Image,
  Input,
  Modal,
  Progress,
  Select,
  Space,
  Switch,
  Table,
  Tag,
  Upload,
} from 'antd'
import type { ColumnsType, TablePaginationConfig } from 'antd/es/table'
import {
  DeleteOutlined,
  PictureOutlined,
  ScissorOutlined,
  SettingOutlined,
  UploadOutlined,
} from '@ant-design/icons'
import { useTranslation } from 'react-i18next'
import {
  batchDeleteAttachments,
  deleteAttachment,
  getAttachmentDownloadUrl,
  getAttachmentList,
  updateCategory,
  updateDisplayName,
  updateVisibility,
  uploadAttachment,
} from '@/api/attachment'
import { useListPage } from '@/hooks/useListPage'
import { useCrudActions } from '@/hooks/useCrudActions'
import { usePermission } from '@/hooks/usePermission'
import { useUnhandledError } from '@/hooks/useUnhandledError'
import { useOptions } from '@/hooks/useOptions'
import { useAttachmentChunkUpload } from '@/hooks/useAttachmentChunkUpload'
import { useAttachmentImagePreview } from '@/hooks/useAttachmentImagePreview'
import { useColumnSetting } from '@/hooks/useColumnSetting'
import PageContainer from '@/components/PageContainer'
import ColumnSettingDialog from '@/components/ColumnSettingDialog'
import SearchForm from '@/components/SearchForm'
import PermissionButton from '@/components/PermissionButton'
import Storage from '@/utils/storage'
import i18n from '@/i18n'
import AttachmentCategoryModal from './AttachmentCategoryModal'
import CropUploadModal from './CropUploadModal'
import {
  ATTACHMENT_LARGE_FILE_THRESHOLD,
  attachmentInitialSearchForm,
  formatAttachmentAdmin,
  formatAttachmentFileSize,
  getAttachmentFileTypeColor,
  getAttachmentFileTypeLabel,
  transformAttachmentRow,
  type AttachmentRow,
} from './attachment.config'

export default function AttachmentList() {
  const { t } = useTranslation()
  const { message, modal } = App.useApp()
  const showError = useUnhandledError()
  const { getButtonState } = usePermission()
  const [uploading, setUploading] = useState(false)
  const [downloadingIds, setDownloadingIds] = useState<Set<string | number>>(new Set())
  const [selectedRowKeys, setSelectedRowKeys] = useState<Array<string | number>>([])
  const [categoryModalOpen, setCategoryModalOpen] = useState(false)
  const [cropModalOpen, setCropModalOpen] = useState(false)
  const [, bump] = useState(0)
  const forceRender = () => bump((n) => n + 1)
  const { selectOptions: categoryOptions, reload: reloadCategories } = useOptions('attachment_category')
  const { loadImageAsBlob, getImageUrl, getImageLoadingState } = useAttachmentImagePreview()

  const {
    tableData,
    loading,
    pagination,
    searchForm,
    onSearchFormChange,
    loadData,
    handleSearch,
    handleReset,
    handleSortChange,
    refresh,
  } = useListPage<AttachmentRow>({
    fetchApi: getAttachmentList,
    initialSearchForm: { ...attachmentInitialSearchForm },
    defaultSort: 'id:desc',
    normalizeRows: false,
    transformData: (row) => transformAttachmentRow(row as unknown as Record<string, unknown>),
    onLoadSuccess: (rows) => {
      rows.forEach((row) => {
        if (row.file_type === 'image') {
          void loadImageAsBlob(row)
        }
      })
    },
  })

  const chunk = useAttachmentChunkUpload(refresh)

  const { toolbar, confirmDelete } = useCrudActions({
    onRefresh: refresh,
    deleteApi: deleteAttachment,
  })

  useEffect(() => {
    void reloadCategories()
  }, [reloadCategories])

  const handleUploadFile = async (file: File) => {
    const maxSize = 100 * 1024 * 1024
    if (file.size > maxSize) {
      message.error(t('attachment.file_too_large'))
      return
    }
    if (file.size > ATTACHMENT_LARGE_FILE_THRESHOLD) {
      void chunk.startChunkUpload(file)
      return
    }
    setUploading(true)
    try {
      await uploadAttachment(file)
      message.success(t('attachment.upload_success'))
      await refresh()
    } catch (error) {
      showError(error, t('attachment.upload_failed'))
    } finally {
      setUploading(false)
    }
  }

  const handleUpdateDisplayName = async (row: AttachmentRow, value: string) => {
    if (!row.id) return
    const next = value || ''
    if (next === (row.display_name || '')) return
    try {
      await updateDisplayName(row.id, next)
      row.display_name = next
      forceRender()
      message.success(t('attachment.update_success'))
    } catch (error) {
      showError(error, t('attachment.update_failed'))
      await refresh()
    }
  }

  const handleUpdateCategory = async (row: AttachmentRow, categoryId: string | number) => {
    if (!row.id || !categoryId) return
    const prev = row.category_id
    row.category_id = categoryId
    forceRender()
    try {
      await updateCategory(row.id, categoryId)
      message.success(t('attachment.update_success'))
    } catch (error) {
      row.category_id = prev
      forceRender()
      showError(error, t('attachment.update_failed'))
      await refresh()
    }
  }

  const handleUpdateVisibility = async (row: AttachmentRow, checked: boolean) => {
    if (!row.id) return
    const prev = row.is_public
    row.is_public = checked ? 1 : 0
    forceRender()
    try {
      const res = await updateVisibility(row.id, checked)
      const data = res?.data as { file_url?: string } | undefined
      if (data?.file_url) {
        row.file_url = data.file_url
        if (row.file_type === 'image') {
          void loadImageAsBlob(row)
        }
      }
      message.success(t('attachment.update_success'))
    } catch (error) {
      row.is_public = prev
      forceRender()
      showError(error, t('attachment.update_failed'))
      await refresh()
    }
  }

  const handleDownload = async (row: AttachmentRow) => {
    const attachmentId = row.id
    if (downloadingIds.has(attachmentId)) return

    setDownloadingIds((prev) => new Set(prev).add(attachmentId))

    try {
      const downloadUrl = getAttachmentDownloadUrl(attachmentId)
      const token = String(Storage.getItem('token', '') ?? '').trim()
      const currentLocale = i18n.language || Storage.getItem('language', 'zh-CN') || 'zh-CN'
      const acceptLanguage = currentLocale === 'en-US' ? 'en-US' : 'zh-CN'

      const response = await fetch(downloadUrl, {
        method: 'GET',
        headers: {
          Authorization: `Bearer ${token}`,
          'Accept-Language': acceptLanguage,
        },
      })

      if (!response.ok) {
        if (response.status === 401) {
          message.error(t('error.unauthorized'))
        } else {
          throw new Error(`HTTP error! status: ${response.status}`)
        }
        return
      }

      const contentType = response.headers.get('content-type') || ''
      if (contentType.includes('text/html')) {
        message.error(t('attachment.download_failed'))
        return
      }

      const blob = await response.blob()
      const contentDisposition = response.headers.get('content-disposition') || ''
      let filename = row.filename || 'attachment'
      const filenameMatch = contentDisposition.match(/filename[^;=\n]*=((['"]).*?\2|[^;\n]*)/)
      if (filenameMatch?.[1]) {
        filename = filenameMatch[1].replace(/['"]/g, '')
        try {
          filename = decodeURIComponent(filename)
        } catch {
          // keep original
        }
      }

      const objectUrl = window.URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = objectUrl
      link.download = filename
      link.style.display = 'none'
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      window.URL.revokeObjectURL(objectUrl)
      message.success(t('attachment.download_success'))
    } catch (error) {
      showError(error, t('attachment.download_failed'))
    } finally {
      setTimeout(() => {
        setDownloadingIds((prev) => {
          const next = new Set(prev)
          next.delete(attachmentId)
          return next
        })
      }, 2000)
    }
  }

  const handleBatchDelete = () => {
    if (!selectedRowKeys.length) return
    modal.confirm({
      title: t('common.confirm'),
      content: t('attachment.batch_delete_confirm', { count: selectedRowKeys.length }),
      okType: 'danger',
      onOk: async () => {
        try {
          await batchDeleteAttachments(selectedRowKeys)
          message.success(t('common.delete_success'))
          setSelectedRowKeys([])
          await refresh()
        } catch (error) {
          showError(error, t('common.operation_failed'))
        }
      },
    })
  }

  const columns: ColumnsType<AttachmentRow> = [
    { title: t('table.id'), dataIndex: 'id', width: 80, sorter: true },
    {
      title: t('attachment.filename'),
      dataIndex: 'filename',
      minWidth: 200,
      render: (_, row) => {
        const previewUrl = getImageUrl(row)
        const loadingState = getImageLoadingState(row)
        return (
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            {row.file_type === 'image' ? (
              previewUrl ? (
                <Image
                  src={previewUrl}
                  width={50}
                  height={50}
                  style={{ objectFit: 'cover', borderRadius: 4, border: '1px solid #f0f0f0' }}
                  preview={{ src: previewUrl }}
                />
              ) : loadingState === 'error' ? (
                <div
                  style={{
                    width: 50,
                    height: 50,
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    background: '#fef0f0',
                    borderRadius: 4,
                    border: '1px solid #fde2e2',
                    color: '#f56c6c',
                  }}
                >
                  <PictureOutlined />
                </div>
              ) : (
                <div
                  style={{
                    width: 50,
                    height: 50,
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    background: '#fafafa',
                    borderRadius: 4,
                    border: '1px solid #f0f0f0',
                    color: '#999',
                  }}
                >
                  ...
                </div>
              )
            ) : null}
            <span style={{ wordBreak: 'break-all' }}>{row.filename}</span>
          </div>
        )
      },
    },
    {
      title: t('attachment.display_name'),
      dataIndex: 'display_name',
      minWidth: 180,
      render: (_, row) => (
        <Input
          key={`${row.id}-${row.display_name}`}
          size="small"
          defaultValue={row.display_name}
          placeholder={t('attachment.display_name_placeholder')}
          onBlur={(e) => void handleUpdateDisplayName(row, e.target.value)}
          onPressEnter={(e) => {
            ;(e.target as HTMLInputElement).blur()
          }}
        />
      ),
    },
    {
      title: t('attachment.category'),
      dataIndex: 'category_id',
      width: 160,
      render: (_, row) => (
        <Select
          size="small"
          style={{ width: 140 }}
          value={row.category_id ?? undefined}
          options={categoryOptions}
          disabled={getButtonState('attachment.update_category').disabled}
          onChange={(value) => void handleUpdateCategory(row, value)}
        />
      ),
    },
    {
      title: t('attachment.visibility'),
      dataIndex: 'is_public',
      width: 110,
      render: (_, row) => (
        <Switch
          size="small"
          checked={Number(row.is_public) === 1}
          checkedChildren={t('attachment.visibility_public_short')}
          unCheckedChildren={t('attachment.visibility_private_short')}
          disabled={getButtonState('attachment.update_visibility').disabled}
          onChange={(checked) => void handleUpdateVisibility(row, checked)}
        />
      ),
    },
    {
      title: t('attachment.file_type'),
      dataIndex: 'file_type',
      width: 100,
      render: (v: string) => (
        <Tag color={getAttachmentFileTypeColor(v)}>{getAttachmentFileTypeLabel(t, v)}</Tag>
      ),
    },
    {
      title: t('attachment.disk'),
      dataIndex: 'disk',
      width: 100,
      render: (v: string) => <Tag>{v || '-'}</Tag>,
    },
    { title: t('attachment.extension'), dataIndex: 'extension', width: 90 },
    {
      title: t('attachment.size'),
      dataIndex: 'size',
      width: 120,
      render: (v: number) => formatAttachmentFileSize(v),
    },
    { title: t('attachment.mime_type'), dataIndex: 'mime_type', width: 140, ellipsis: true },
    {
      title: t('log.admin'),
      dataIndex: 'admin',
      width: 120,
      render: (_, row) => formatAttachmentAdmin(row),
    },
    { title: t('table.created_at'), dataIndex: 'created_at', width: 180, sorter: true },
    {
      title: t('common.operation'),
      key: 'operation',
      width: 160,
      fixed: 'right',
      render: (_, row) => (
        <Space>
          <Button
            type="link"
            loading={downloadingIds.has(row.id)}
            onClick={() => void handleDownload(row)}
          >
            {t('common.download')}
          </Button>
          {getButtonState('attachment.destroy').show ? (
            <PermissionButton
              permission="attachment.destroy"
              type="link"
              danger
              onClick={() => confirmDelete(row.id, row.filename)}
            >
              {t('common.delete')}
            </PermissionButton>
          ) : null}
        </Space>
      ),
    },
  ]

  const {
    filteredColumns,
    open: columnSettingOpen,
    openColumnSetting,
    closeColumnSetting,
    allColumns,
    visibleColumns,
    columnOrder,
    fixedColumns,
    handleConfirm: handleColumnSettingConfirm,
  } = useColumnSetting('attachment', columns)

  return (
    <PageContainer
      title={t('menu.attachment')}
      extra={
        <Space wrap>
          {getButtonState('attachment.upload').show ? (
            <Upload
              showUploadList={false}
              beforeUpload={(file) => {
                void handleUploadFile(file as File)
                return false
              }}
            >
              <PermissionButton
                permission="attachment.upload"
                type="primary"
                icon={<UploadOutlined />}
                loading={uploading}
              >
                {t('attachment.upload')}
              </PermissionButton>
            </Upload>
          ) : null}
          {getButtonState('attachment.upload').show ? (
            <PermissionButton
              permission="attachment.upload"
              icon={<ScissorOutlined />}
              onClick={() => setCropModalOpen(true)}
            >
              {t('attachment.crop_upload')}
            </PermissionButton>
          ) : null}
          {getButtonState('attachment.chunk').show ? (
            <PermissionButton
              permission="attachment.chunk"
              icon={<UploadOutlined />}
              onClick={chunk.handleLargeFileUpload}
            >
              {t('attachment.large_file_upload')}
            </PermissionButton>
          ) : null}
          {getButtonState('attachment_category.index').show ? (
            <PermissionButton
              permission="attachment_category.index"
              onClick={() => setCategoryModalOpen(true)}
            >
              {t('attachment.category_manage')}
            </PermissionButton>
          ) : null}
          {selectedRowKeys.length > 0 && getButtonState('attachment.destroy').show ? (
            <Button danger icon={<DeleteOutlined />} onClick={handleBatchDelete}>
              {t('common.delete_selected')} ({selectedRowKeys.length})
            </Button>
          ) : null}
          {toolbar}
          <Button icon={<SettingOutlined />} onClick={openColumnSetting}>
            {t('common.column_setting')}
          </Button>
        </Space>
      }
    >
      <SearchForm
        fields={[
          { name: 'filename', label: t('attachment.filename') },
          { name: 'display_name', label: t('attachment.display_name') },
          {
            name: 'category_id',
            label: t('attachment.category'),
            type: 'select',
            options: categoryOptions,
          },
          {
            name: 'is_public',
            label: t('attachment.visibility'),
            type: 'select',
            advanced: true,
            options: [
              { label: t('attachment.visibility_public'), value: '1' },
              { label: t('attachment.visibility_private'), value: '0' },
            ],
          },
          {
            name: 'file_type',
            label: t('attachment.file_type'),
            type: 'select',
            advanced: true,
            options: [
              { label: t('attachment.file_type_image'), value: 'image' },
              { label: t('attachment.file_type_video'), value: 'video' },
              { label: t('attachment.file_type_document'), value: 'document' },
              { label: t('attachment.file_type_other'), value: 'other' },
            ],
          },
          { name: 'extension', label: t('attachment.extension'), advanced: true },
          { name: 'start_time', label: t('log.start_time'), type: 'datetime', advanced: true },
          { name: 'end_time', label: t('log.end_time'), type: 'datetime', advanced: true },
        ]}
        values={searchForm}
        onChange={onSearchFormChange}
        onSearch={handleSearch}
        onReset={handleReset}
      />
      <Table<AttachmentRow>
        rowKey="id"
        loading={loading}
        columns={filteredColumns}
        dataSource={tableData}
        scroll={{ x: 1800 }}
        rowSelection={{
          selectedRowKeys,
          onChange: (keys) => setSelectedRowKeys(keys as Array<string | number>),
        }}
        pagination={{
          current: pagination.page,
          pageSize: pagination.pageSize,
          total: pagination.total,
          showSizeChanger: true,
          showTotal: (total) => t('common.total', { total }),
        }}
        onChange={(pager: TablePaginationConfig, _f, sorter) => {
          const sort = Array.isArray(sorter) ? sorter[0] : sorter
          const sortObj = sort as {
            field?: string
            order?: 'ascend' | 'descend' | null
            column?: unknown
          }
          if (sortObj?.column && sortObj.field) {
            handleSortChange(String(sortObj.field), sortObj.order)
            return
          }
          void loadData({
            currentPage: pager.current || 1,
            pageSize: pager.pageSize || pagination.pageSize,
          })
        }}
      />

      <AttachmentCategoryModal
        open={categoryModalOpen}
        onClose={() => setCategoryModalOpen(false)}
        onChanged={() => {
          void reloadCategories()
          void refresh()
        }}
      />

      <CropUploadModal
        open={cropModalOpen}
        onClose={() => setCropModalOpen(false)}
        onSuccess={() => void refresh()}
      />

      <Modal
        open={chunk.visible}
        title={t('attachment.chunk_upload')}
        width={600}
        closable={false}
        maskClosable={false}
        keyboard={false}
        footer={
          chunk.status === 'success' ? (
            <Button type="primary" onClick={() => void chunk.handleClose()}>
              {t('common.confirm')}
            </Button>
          ) : chunk.status === 'exception' ? (
            <Space>
              <Button onClick={chunk.handleCancel}>{t('common.cancel')}</Button>
              <Button type="primary" onClick={chunk.handleRetry}>
                {t('common.retry')}
              </Button>
            </Space>
          ) : (
            <Button onClick={chunk.handleCancel}>{t('common.cancel')}</Button>
          )
        }
      >
        {chunk.file ? (
          <div>
            <p>
              <strong>{t('attachment.filename')}:</strong> {chunk.file.name}
            </p>
            <p>
              <strong>{t('attachment.size')}:</strong> {formatAttachmentFileSize(chunk.file.size)}
            </p>
            <Progress
              percent={Math.round(chunk.progress)}
              status={
                chunk.status === 'success'
                  ? 'success'
                  : chunk.status === 'exception'
                    ? 'exception'
                    : 'active'
              }
            />
            <div style={{ marginTop: 12, textAlign: 'center', color: '#666' }}>
              {chunk.status === 'success'
                ? t('attachment.upload_success')
                : chunk.status === 'exception'
                  ? t('attachment.upload_failed')
                  : `${t('attachment.uploading')}: ${Math.round(chunk.progress)}%`}
            </div>
          </div>
        ) : null}
      </Modal>
      <ColumnSettingDialog
        open={columnSettingOpen}
        onClose={closeColumnSetting}
        allColumns={allColumns}
        visibleColumns={visibleColumns}
        columnOrder={columnOrder}
        fixedColumns={fixedColumns}
        onConfirm={handleColumnSettingConfirm}
      />
    </PageContainer>
  )
}

// html/src/views/attachment/AttachmentList.vue
<template>
  <div class="attachment-list">
    <ListPage
      ref="listPageRef"
      page-class="attachment"
      :title="$t('menu.attachment')"
      :show-add-button="false"
      :search-form="searchForm"
      :search-fields="searchFields"
      :initial-search-values="attachmentInitialSearchForm"
      :table-data="tableData"
      :loading="loading"
      :table-columns="tableColumns"
      :table-key="`table-${tableColumns.length}-${JSON.stringify(columnOrder)}`"
      :pagination="pagination"
      show-toolbar
      show-column-setting
      :visible-columns="visibleColumns"
      :all-columns="allColumns"
      :default-visible-columns="defaultVisibleColumns"
      :column-order="columnOrder"
      :fixed-columns="fixedColumns"
      :on-column-setting-confirm="handleColumnSettingConfirm"
      @search="handleSearch"
      @reset="handleReset"
      @refresh="loadData"
      @page-change="loadData"
      @sort-change="handleSortChange"
      @selection-change="handleSelectionChange"
    >
      <template #header-actions>
        <el-upload
          ref="uploadRef"
          :action="uploadAction"
          :headers="uploadHeaders"
          :data="uploadData"
          :before-upload="beforeUpload"
          :on-success="handleUploadSuccess"
          :on-error="handleUploadError"
          :show-file-list="false"
          :multiple="false"
        >
          <template #trigger>
            <el-button type="primary" :disabled="getButtonState('attachment.upload').disabled">
              <el-icon><UploadIcon /></el-icon>
              {{ $t('attachment.upload') }}
            </el-button>
          </template>
        </el-upload>
        <el-button
          type="warning"
          :disabled="getButtonState('attachment.upload').disabled"
          @click="handleCropUpload"
        >
          <el-icon><CropIcon /></el-icon>
          {{ $t('attachment.crop_upload') }}
        </el-button>
        <el-button
          type="success"
          :disabled="getButtonState('attachment.chunk').disabled"
          @click="handleLargeFileUpload"
        >
          <el-icon><UploadIcon /></el-icon>
          {{ $t('attachment.large_file_upload') }}
        </el-button>
        <el-button
          type="danger"
          :disabled="selectedRows.length === 0 || getButtonState('attachment.destroy').disabled"
          @click="handleBatchDelete"
        >
          <el-icon><DeleteIcon /></el-icon>
          {{ $t('common.delete_selected') }} ({{ selectedRows.length }})
        </el-button>
      </template>

      <template #filename="{ row }">
          <div class="filename-cell">
            <el-image
              v-if="row.file_type === 'image' && getImageUrl(row)"
              :src="getImageUrl(row)"
              :preview-src-list="[getImageUrl(row)]"
              fit="cover"
              class="filename-thumbnail"
              :preview-teleported="true"
              :lazy="true"
              @load="handleImageLoad(row)"
              @error="handleImageError(row)"
            >
              <template #placeholder>
                <div class="image-placeholder">
                  <el-icon class="is-loading"><Loading /></el-icon>
                </div>
              </template>
              <template #error>
                <div class="image-error">
                  <el-icon><Picture /></el-icon>
                </div>
              </template>
            </el-image>
            <div
              v-else-if="row.file_type === 'image' && getImageLoadingState(row) === 'loading'"
              class="image-placeholder"
            >
              <el-icon class="is-loading"><Loading /></el-icon>
            </div>
            <div
              v-else-if="row.file_type === 'image' && getImageLoadingState(row) === 'error'"
              class="image-error"
            >
              <el-icon><Picture /></el-icon>
            </div>
            <span class="filename-text">{{ row.filename }}</span>
          </div>
        </template>

        <template #display_name="{ row }">
          <el-input
            v-model="row.display_name"
            :placeholder="$t('attachment.display_name_placeholder')"
            size="small"
            @blur="handleUpdateDisplayName(row)"
            @keyup.enter="handleUpdateDisplayName(row)"
          />
        </template>

        <template #file_type="{ row }">
          <el-tag :type="getFileTypeTagType(row.file_type)">
            {{ getFileTypeLabel(row.file_type) }}
          </el-tag>
        </template>

        <template #disk="{ row }">
          <el-tag size="small" type="info">
            {{ row.disk || '-' }}
          </el-tag>
        </template>

        <template #operation="{ row }">
          <el-button
            type="success"
            link
            :disabled="downloadingIds.has(row.id)"
            :loading="downloadingIds.has(row.id)"
            @click="handleDownload(row)"
          >
            {{ $t('common.download') }}
          </el-button>
          <el-button
            type="danger"
            link
            :disabled="getButtonState('attachment.destroy').disabled"
            @click="handleDelete(row)"
          >
            {{ $t('common.delete') }}
          </el-button>
        </template>
    </ListPage>

    <!-- 大文件上传对话框 -->
    <el-dialog
      v-model="chunkUploadVisible"
      :title="$t('attachment.chunk_upload')"
      width="600px"
      :close-on-click-modal="false"
      :close-on-press-escape="false"
    >
      <div v-if="chunkUploadFile" class="chunk-upload-container">
        <div class="upload-info">
          <p><strong>{{ $t('attachment.filename') }}:</strong> {{ chunkUploadFile.name }}</p>
          <p><strong>{{ $t('attachment.size') }}:</strong> {{ formatFileSize(chunkUploadFile.size) }}</p>
        </div>
        <el-progress 
          :percentage="Math.round(chunkUploadProgress)" 
          :status="chunkUploadStatus"
          :stroke-width="20"
        />
        <div class="upload-status">
          <p v-if="chunkUploadStatus === 'success'">{{ $t('attachment.upload_success') }}</p>
          <p v-else-if="chunkUploadStatus === 'exception'">{{ $t('attachment.upload_failed') }}</p>
          <p v-else>{{ $t('attachment.uploading') }}: {{ Math.round(chunkUploadProgress) }}%</p>
        </div>
        <div class="upload-actions" style="margin-top: 20px; text-align: right;">
          <el-button 
            v-if="chunkUploadStatus !== 'success' && chunkUploadStatus !== 'exception'"
            @click="handleCancelChunkUpload"
          >
            {{ $t('common.cancel') }}
          </el-button>
          <el-button 
            v-if="chunkUploadStatus === 'success'"
            type="primary"
            @click="handleChunkUploadClose"
          >
            {{ $t('common.confirm') }}
          </el-button>
          <el-button 
            v-if="chunkUploadStatus === 'exception'"
            type="primary"
            @click="handleRetryChunkUpload"
          >
            {{ $t('common.retry') }}
          </el-button>
        </div>
      </div>
    </el-dialog>
    <!-- 图片裁剪对话框 -->
    <el-dialog
      v-model="cropDialogVisible"
      :title="$t('attachment.crop_upload')"
      width="800px"
      :close-on-click-modal="false"
      destroy-on-close
    >
      <div class="crop-container" style="height: 500px;">
        <vue-cropper
          ref="cropperRef"
          :img="cropOption.img"
          :output-size="cropOption.size"
          :output-type="cropOption.outputType"
          :info="true"
          :full="cropOption.full"
          :can-move="cropOption.canMove"
          :can-move-box="cropOption.canMoveBox"
          :fixed-box="cropOption.fixedBox"
          :original="cropOption.original"
          :auto-crop="cropOption.autoCrop"
          :auto-crop-width="cropOption.autoCropWidth"
          :auto-crop-height="cropOption.autoCropHeight"
          :center-box="cropOption.centerBox"
          :high="cropOption.high"
          :mode="cropOption.mode"
        />
      </div>
      <template #footer>
        <div class="dialog-footer">
          <el-upload
            action=""
            :auto-upload="false"
            :show-file-list="false"
            accept="image/*"
            :on-change="onCropFileChange"
            style="display: inline-block; margin-right: 10px;"
          >
            <el-button>{{ $t('attachment.select_image') }}</el-button>
          </el-upload>
          <el-button @click="cropDialogVisible = false">{{ $t('common.cancel') }}</el-button>
          <el-button type="primary" :loading="cropUploading" @click="handleCropConfirm">
            {{ $t('common.confirm') }}
          </el-button>
        </div>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { ref, reactive, computed, onMounted, markRaw, nextTick } from 'vue'
import { useI18n } from 'vue-i18n'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Upload, Delete, Loading, Picture, Crop } from '@element-plus/icons-vue'
import ListPage from '@/components/ListPage.vue'
import { useListPage } from '@/composables/useListPage'
import { usePermission } from '@/composables/usePermission'
import { useCrud } from '@/composables/useCrud'
import { useColumnSetting } from '@/composables/useColumnSetting'
import { useAttachmentImagePreview } from '@/composables/useAttachmentImagePreview'
import { useAttachmentChunkUpload, useAttachmentUploadConfig } from '@/composables/useAttachmentChunkUpload'
import axios from 'axios'
import {
  getAttachmentList,
  deleteAttachment,
  batchDeleteAttachments,
  updateDisplayName
} from '@/api/attachment'
import i18n from '@/i18n'
import Storage from '@/utils/storage'
import 'vue-cropper/dist/index.css'
import { VueCropper } from 'vue-cropper'
import {
  attachmentInitialSearchForm,
  transformAttachmentRow,
  createAttachmentSearchFields,
  createAttachmentTableColumns,
  formatAttachmentFileSize,
  getAttachmentFileTypeTagType,
  getAttachmentFileTypeLabel
} from './attachment.config'

const UploadIcon = markRaw(Upload)
const DeleteIcon = markRaw(Delete)
const CropIcon = markRaw(Crop)

const { t, locale } = useI18n()
const { getButtonState } = usePermission()

const { handleDelete: handleDeleteCrud, handleBatchDelete: handleBatchDeleteCrud } = useCrud({
  deleteApi: deleteAttachment,
  batchDeleteApi: batchDeleteAttachments
})

const listPageRef = ref(null)
const uploadRef = ref(null)
const downloadingIds = ref(new Set())
// 裁剪上传相关
const cropDialogVisible = ref(false)
const cropperRef = ref(null)
const cropUploading = ref(false)
const cropFileName = ref('')
const cropOption = reactive({
  img: '',
  size: 1,
  full: false,
  outputType: 'png',
  canMove: true,
  fixedBox: false,
  original: false,
  canMoveBox: true,
  autoCrop: true,
  // 只有自动截图开启 宽度高度才生效
  autoCropWidth: 200,
  autoCropHeight: 200,
  centerBox: false,
  high: true,
  max: 99999,
  mode: 'contain'
})

// 图片预览
const {
  loadImageAsBlob,
  getImageUrl,
  getImageLoadingState,
  handleImageLoad,
  handleImageError
} = useAttachmentImagePreview()

const {
  pagination,
  tableData,
  loading,
  searchForm,
  selectedRows,
  loadData,
  handleSearch,
  handleReset,
  handleSortChange,
  handleSelectionChange,
  initDefaultSort
} = useListPage({
  fetchApi: getAttachmentList,
  initialSearchForm: attachmentInitialSearchForm,
  defaultSort: 'id:desc',
  normalizeRows: false,
  transformData: transformAttachmentRow,
  tableRef: computed(() => listPageRef.value?.tableRef?.tableRef),
  onLoadSuccess: () => {
    tableData.value.forEach((row) => {
      if (row.file_type === 'image') {
        nextTick(() => loadImageAsBlob(row))
      }
    })
  }
})

const searchFields = computed(() => createAttachmentSearchFields(t))
const allTableColumns = computed(() => createAttachmentTableColumns(t))

const {
  tableColumns,
  visibleColumns,
  allColumns,
  defaultVisibleColumns,
  columnOrder,
  fixedColumns,
  handleColumnSettingConfirm
} = useColumnSetting('attachment', allTableColumns)

const formatFileSize = formatAttachmentFileSize
const getFileTypeTagType = getAttachmentFileTypeTagType
const getFileTypeLabel = (fileType) => getAttachmentFileTypeLabel(t, fileType)

const { uploadAction, uploadHeaders, uploadData } = useAttachmentUploadConfig(locale)

const {
  chunkUploadVisible,
  chunkUploadFile,
  chunkUploadProgress,
  chunkUploadStatus,
  beforeUpload,
  handleLargeFileUpload,
  handleCancelChunkUpload,
  handleChunkUploadClose,
  handleRetryChunkUpload
} = useAttachmentChunkUpload({ onUploaded: loadData })

const handleUploadSuccess = () => {
  ElMessage.success(t('attachment.upload_success'))
  loadData()
}

const handleUploadError = () => {
  ElMessage.error(t('attachment.upload_failed'))
}

// 裁剪上传相关方法
const handleCropUpload = () => {
  cropDialogVisible.value = true
  cropOption.img = ''
  cropFileName.value = ''
}

const onCropFileChange = (file) => {
  const isImage = file.raw.type.startsWith('image/')
  if (!isImage) {
    ElMessage.error(t('attachment.only_image_allowed'))
    return
  }
  
  // 检查文件大小（限制10MB）
  const maxSize = 10 * 1024 * 1024
  if (file.size > maxSize) {
    ElMessage.error(t('attachment.file_too_large'))
    return
  }

  cropFileName.value = file.name
  // 读取图片
  const reader = new FileReader()
  reader.onload = (e) => {
    cropOption.img = e.target.result
  }
  reader.readAsDataURL(file.raw)
}

const handleCropConfirm = () => {
  if (!cropOption.img) {
    ElMessage.warning(t('attachment.please_select_image'))
    return
  }

  cropUploading.value = true
  cropperRef.value.getCropBlob((blob) => {
    if (!blob) {
      cropUploading.value = false
      return
    }

    // 创建 File 对象
    const file = new File([blob], cropFileName.value || 'cropped-image.png', {
      type: blob.type
    })

    const formData = new FormData()
    formData.append('file', file)

    // 获取上传 URL 和 Headers
    const action = uploadAction.value
    const headers = uploadHeaders.value
    
    // 使用 axios 上传
    axios.post(action, formData, {
      headers: {
        ...headers,
        'Content-Type': 'multipart/form-data'
      }
    }).then(() => {
      ElMessage.success(t('attachment.upload_success'))
      cropDialogVisible.value = false
      loadData()
    }).catch((error) => {
      console.error('Crop upload error:', error)
      ElMessage.error(t('attachment.upload_failed'))
    }).finally(() => {
      cropUploading.value = false
    })
  })
}

const handleUpdateDisplayName = async (row) => {
  const attachmentId = row.id
  if (!attachmentId) return
  
  const displayName = row.display_name || ''
  
  try {
    await updateDisplayName(attachmentId, displayName)
    ElMessage.success(t('attachment.update_success'))
  } catch (error) {
    console.error('Update display name error:', error)
    if (!error.__handled) {
      const errorMessage = error.response?.data?.message || error.message || t('attachment.update_failed')
      ElMessage.error(errorMessage)
    }
    // 重新加载数据以恢复原值
    loadData()
  }
}

const handleDownload = async (row) => {
  // 防止重复点击
  const attachmentId = row.id
  if (downloadingIds.value.has(attachmentId)) {
    return // 如果正在下载，直接返回
  }
  
  // 标记为正在下载
  downloadingIds.value.add(attachmentId)
  
  try {
    // 构建下载 URL
    const apiBaseURL = import.meta.env.VITE_API_BASE_URL
    const apiPrefix = import.meta.env.VITE_API_PREFIX || '/api/admin'
    
    let downloadUrl = `${apiPrefix}/attachments/${attachmentId}/download`
    
    if (apiBaseURL) {
      const base = apiBaseURL.replace(/\/+$/, '')
      downloadUrl = `${base}${downloadUrl}`
    }
    
    // 获取 token
    const token = Storage.getItem('token', '') || ''
    const tokenStr = typeof token === 'string' ? token.trim() : ''
    
    // 获取当前语言设置
    const currentLocale = locale.value || i18n.global.locale.value || Storage.getItem('language', 'zh-CN') || 'zh-CN'
    const acceptLanguage = currentLocale === 'en-US' ? 'en-US' : 'zh-CN'
    
    // 使用 fetch 请求下载文件，这样可以携带认证 token
    const response = await fetch(downloadUrl, {
      method: 'GET',
      headers: {
        'Authorization': `Bearer ${tokenStr}`,
        'Accept-Language': acceptLanguage
      }
    })
    
    if (!response.ok) {
      if (response.status === 401) {
        ElMessage.error(t('error.unauthorized') || '未授权，请重新登录')
      } else {
        const errorText = await response.text()
        console.error('Download error response:', errorText)
        throw new Error(`HTTP error! status: ${response.status}`)
      }
      return
    }
    
    // 检查响应类型，确保是文件而不是 HTML
    const contentType = response.headers.get('content-type') || ''
    if (contentType.includes('text/html')) {
      const htmlContent = await response.text()
      console.error('Received HTML instead of file:', htmlContent.substring(0, 200))
      ElMessage.error(t('attachment.download_failed') || '下载失败：服务器返回了错误内容')
      return
    }
    
    // 获取文件内容
    const blob = await response.blob()
    
    // 从响应头获取文件名，如果没有则使用记录中的文件名
    const contentDisposition = response.headers.get('content-disposition') || ''
    let filename = row.filename || row.Filename || 'attachment'
    
    // 尝试从 Content-Disposition 头中提取文件名
    const filenameMatch = contentDisposition.match(/filename[^;=\n]*=((['"]).*?\2|[^;\n]*)/)
    if (filenameMatch && filenameMatch[1]) {
      filename = filenameMatch[1].replace(/['"]/g, '')
      // 处理 URL 编码的文件名
      try {
        filename = decodeURIComponent(filename)
      } catch (e) {
        // 如果解码失败，使用原始文件名
      }
    }
    
    // 创建下载链接
    const downloadUrlObj = window.URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = downloadUrlObj
    link.download = filename
    link.style.display = 'none'
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    
    // 释放 URL 对象
    window.URL.revokeObjectURL(downloadUrlObj)
    
    ElMessage.success(t('attachment.download_success') || '下载成功')
  } catch (error) {
    console.error('Download error:', error)
    if (!error.__handled) {
      const errorMessage = error.response?.data?.message || error.message || t('attachment.download_failed') || '下载失败'
      ElMessage.error(errorMessage)
    }
  } finally {
    // 下载完成或失败后，延迟移除标记（防止短时间内重复点击）
    setTimeout(() => {
      downloadingIds.value.delete(attachmentId)
    }, 2000) // 2秒内不允许重复点击
  }
}

const handleDelete = (row) => handleDeleteCrud(row, loadData)

const handleBatchDelete = () => {
  handleBatchDeleteCrud(selectedRows.value, () => {
    handleSelectionChange([])
    loadData()
  })
}

onMounted(() => {
  initDefaultSort()
  loadData()
})

// 刷新由菜单的「是否缓存」设置控制：no_cache=1 时每次进入会 remount 触发 onMounted 刷新
</script>

<style scoped>


.preview-container {
  text-align: center;
}

.preview-image img {
  border-radius: var(--border-radius-sm);
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.1);
}

.preview-video video {
  border-radius: var(--border-radius-sm);
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.1);
}

.preview-document iframe {
  border-radius: var(--border-radius-sm);
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.1);
}

.chunk-upload-container {
  padding: 20px;
}

.upload-info {
  margin-bottom: 20px;
}

.upload-info p {
  margin: 8px 0;
}

.upload-status {
  margin-top: var(--space-sm);
  text-align: center;
  color: var(--text-color-regular);
}

.upload-actions {
  margin-top: 20px;
}

.filename-cell {
  display: flex;
  align-items: center;
  gap: var(--space-sm);
}

.filename-thumbnail {
  width: 50px;
  height: 50px;
  cursor: pointer;
  border-radius: var(--border-radius-sm);
  flex-shrink: 0;
  border: 1px solid var(--border-color-light);
}

.image-placeholder {
  width: 50px;
  height: 50px;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: var(--bg-color-tertiary);
  border-radius: var(--border-radius-sm);
  border: 1px solid var(--border-color-light);
}

.image-placeholder .el-icon {
  font-size: 20px;
  color: var(--text-color-secondary);
}

.image-error {
  width: 50px;
  height: 50px;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #fef0f0;
  border-radius: var(--border-radius-sm);
  border: 1px solid #fde2e2;
}

.image-error .el-icon {
  font-size: 20px;
  color: #f56c6c;
}

.filename-text {
  flex: 1;
  word-break: break-all;
}
</style>
