// html-react/src/pages/log/SystemLogList.tsx
﻿import { useEffect, useMemo, useState } from 'react'
import { App, Descriptions, Drawer, Space, Spin, Table, Tag, Tooltip } from 'antd'
import type { ColumnsType, TablePaginationConfig } from 'antd/es/table'
import { EyeOutlined } from '@ant-design/icons'
import { useTranslation } from 'react-i18next'
import {
  batchDeleteSystemLogs,
  cleanSystemLogs,
  deleteSystemLog,
  getSystemLogDetail,
  getSystemLogList,
  getSystemLogModuleOptions,
} from '@/api/log'
import { useListPage } from '@/hooks/useListPage'
import { useCrudActions } from '@/hooks/useCrudActions'
import { usePermission } from '@/hooks/usePermission'
import { useUnhandledError } from '@/hooks/useUnhandledError'
import PageContainer from '@/components/PageContainer'
import SearchForm from '@/components/SearchForm'
import PermissionButton from '@/components/PermissionButton'
import LogCleanModal from './LogCleanModal'
import {
  createSystemLogSearchFields,
  extractLogDetail,
  formatSystemLogContext,
  formatSystemLogContextPreview,
  getSystemLogLevelColor,
  getSystemLogLevelLabel,
  getSystemLogModuleLabel,
  systemLogInitialSearchForm,
  transformSystemLogRow,
  type SystemLogRow,
} from './systemLog.config'

export default function SystemLogList() {
  const { t } = useTranslation()
  const { message, modal } = App.useApp()
  const showError = useUnhandledError()
  const { getButtonState } = usePermission()
  const [selectedRowKeys, setSelectedRowKeys] = useState<Array<string | number>>([])
  const [detailOpen, setDetailOpen] = useState(false)
  const [detailLoading, setDetailLoading] = useState(false)
  const [logDetail, setLogDetail] = useState<SystemLogRow | null>(null)
  const [moduleOptions, setModuleOptions] = useState<Array<{ label: string; value: string }>>([])
  const [cleanOpen, setCleanOpen] = useState(false)
  const [cleanLoading, setCleanLoading] = useState(false)

  const getModuleLabel = (module?: string) => getSystemLogModuleLabel(t, module)

  const {
    tableData,
    loading,
    pagination,
    searchForm,
    onSearchFormChange,
    loadData,
    handleSearch,
    handleReset,
    refresh,
  } = useListPage<SystemLogRow>({
    fetchApi: getSystemLogList,
    initialSearchForm: { ...systemLogInitialSearchForm },
    defaultSort: 'id:desc',
    normalizeRows: false,
    transformData: (row) => transformSystemLogRow(row as unknown as Record<string, unknown>),
    onSearch: () => setSelectedRowKeys([]),
    onReset: () => setSelectedRowKeys([]),
  })

  const { toolbar, confirmDelete } = useCrudActions({
    onRefresh: refresh,
    deleteApi: deleteSystemLog,
  })

  useEffect(() => {
    void (async () => {
      try {
        const res = await getSystemLogModuleOptions()
        const data = res.data as Record<string, unknown> | undefined
        const modules = Array.isArray(data?.modules) ? (data.modules as string[]) : []
        setModuleOptions(
          modules.map((module) => ({
            label: getModuleLabel(module),
            value: module,
          })),
        )
      } catch {
        setModuleOptions([])
      }
    })()
  }, [t])

  const handleView = async (row: SystemLogRow) => {
    setDetailOpen(true)
    setDetailLoading(true)
    setLogDetail(null)
    try {
      const res = await getSystemLogDetail(row.id)
      const raw = extractLogDetail<Record<string, unknown>>(res.data as Record<string, unknown>, [
        'system_log',
        'log',
      ])
      if (raw) {
        setLogDetail(transformSystemLogRow(raw))
      }
    } catch (error) {
      showError(error, t('common.operation_failed'))
      setDetailOpen(false)
    } finally {
      setDetailLoading(false)
    }
  }

  const handleBatchDelete = () => {
    if (!selectedRowKeys.length) return
    modal.confirm({
      title: t('common.delete_confirm'),
      content: t('log.batch_delete_confirm', { count: selectedRowKeys.length }),
      okType: 'danger',
      onOk: async () => {
        try {
          await batchDeleteSystemLogs(selectedRowKeys)
          message.success(t('common.delete_success'))
          setSelectedRowKeys([])
          await refresh()
        } catch (error) {
          showError(error, t('common.operation_failed'))
        }
      },
    })
  }

  const handleClean = async (days: number) => {
    setCleanLoading(true)
    try {
      await cleanSystemLogs({ days })
      message.success(t('log.clean_success'))
      setCleanOpen(false)
      setSelectedRowKeys([])
      await refresh()
    } catch (error) {
      showError(error, t('common.operation_failed'))
    } finally {
      setCleanLoading(false)
    }
  }

  const searchFields = useMemo(
    () => createSystemLogSearchFields(t, moduleOptions),
    [t, moduleOptions],
  )

  const columns: ColumnsType<SystemLogRow> = [
    { title: t('table.id'), dataIndex: 'id', width: 80, sorter: true },
    {
      title: t('log.level'),
      dataIndex: 'level',
      width: 100,
      render: (level: string) => (
        <Tag color={getSystemLogLevelColor(level)}>{getSystemLogLevelLabel(t, level)}</Tag>
      ),
    },
    {
      title: t('log.module'),
      dataIndex: 'module',
      width: 120,
      render: (module: string) => getModuleLabel(module),
    },
    {
      title: t('log.trace_id'),
      dataIndex: 'trace_id',
      width: 220,
      ellipsis: true,
      render: (traceId: string) => traceId || '-',
    },
    { title: t('log.message'), dataIndex: 'message', ellipsis: true },
    {
      title: t('log.context'),
      dataIndex: 'context',
      width: 200,
      ellipsis: true,
      render: (context: unknown) =>
        context ? (
          <Tooltip title={<pre style={{ margin: 0, maxWidth: 500, whiteSpace: 'pre-wrap' }}>{formatSystemLogContext(context)}</pre>}>
            <span style={{ cursor: 'pointer', color: '#1677ff' }}>{formatSystemLogContextPreview(context)}</span>
          </Tooltip>
        ) : (
          '-'
        ),
    },
    { title: t('log.time'), dataIndex: 'created_at', width: 180, sorter: true },
    {
      title: t('common.operation'),
      key: 'operation',
      width: 140,
      fixed: 'right',
      render: (_, row) => (
        <Space>
          {getButtonState('system_log.show').show ? (
            <PermissionButton
              permission="system_log.show"
              type="link"
              icon={<EyeOutlined />}
              onClick={() => void handleView(row)}
            >
              {t('common.view')}
            </PermissionButton>
          ) : null}
          {getButtonState('system_log.destroy').show ? (
            <PermissionButton
              permission="system_log.destroy"
              type="link"
              danger
              onClick={() => confirmDelete(row.id, getModuleLabel(row.module))}
            >
              {t('common.delete')}
            </PermissionButton>
          ) : null}
        </Space>
      ),
    },
  ]

  return (
    <PageContainer
      title={t('menu.system_log')}
      extra={
        <Space>
          {selectedRowKeys.length > 0 && getButtonState('system_log.batch_delete').show ? (
            <PermissionButton permission="system_log.batch_delete" danger onClick={handleBatchDelete}>
              {t('common.delete_selected')} ({selectedRowKeys.length})
            </PermissionButton>
          ) : null}
          {getButtonState('system_log.clean').show ? (
            <PermissionButton permission="system_log.clean" onClick={() => setCleanOpen(true)}>
              {t('log.clean')}
            </PermissionButton>
          ) : null}
          {toolbar}
        </Space>
      }
    >
      <SearchForm
        fields={searchFields}
        values={searchForm}
        onChange={onSearchFormChange}
        onSearch={handleSearch}
        onReset={handleReset}
      />
      <Table<SystemLogRow>
        rowKey="id"
        loading={loading}
        columns={columns}
        dataSource={tableData}
        scroll={{ x: 1300 }}
        rowSelection={
          getButtonState('system_log.batch_delete').show
            ? {
                selectedRowKeys,
                onChange: (keys) => setSelectedRowKeys(keys as Array<string | number>),
              }
            : undefined
        }
        pagination={{
          current: pagination.page,
          pageSize: pagination.pageSize,
          total: pagination.total,
          showSizeChanger: true,
          showTotal: (total) => t('common.total', { total }),
        }}
        onChange={(pager: TablePaginationConfig) => {
          void loadData({
            currentPage: pager.current || 1,
            pageSize: pager.pageSize || pagination.pageSize,
          })
        }}
      />

      <Drawer open={detailOpen} title={t('log.detail')} width={1100} onClose={() => setDetailOpen(false)}>
        <Spin spinning={detailLoading}>
          {logDetail ? (
            <Descriptions bordered column={2} size="small">
              <Descriptions.Item label={t('table.id')}>{logDetail.id}</Descriptions.Item>
              <Descriptions.Item label={t('log.level')}>
                <Tag color={getSystemLogLevelColor(logDetail.level)}>
                  {getSystemLogLevelLabel(t, logDetail.level)}
                </Tag>
              </Descriptions.Item>
              <Descriptions.Item label={t('log.module')}>{getModuleLabel(logDetail.module)}</Descriptions.Item>
              <Descriptions.Item label={t('log.trace_id')} span={2}>
                {logDetail.trace_id || '-'}
              </Descriptions.Item>
              <Descriptions.Item label={t('log.message')} span={2}>
                {logDetail.message}
              </Descriptions.Item>
              <Descriptions.Item label={t('log.context')} span={2}>
                {logDetail.context ? (
                  <pre style={{ margin: 0, maxHeight: 400, overflow: 'auto', fontSize: 12 }}>
                    {formatSystemLogContext(logDetail.context)}
                  </pre>
                ) : (
                  '-'
                )}
              </Descriptions.Item>
              <Descriptions.Item label={t('log.time')} span={2}>
                {logDetail.created_at}
              </Descriptions.Item>
            </Descriptions>
          ) : null}
        </Spin>
      </Drawer>

      <LogCleanModal
        open={cleanOpen}
        loading={cleanLoading}
        onClose={() => setCleanOpen(false)}
        onConfirm={handleClean}
      />
    </PageContainer>
  )
}

// html/src/views/log/SystemLogList.vue
<template>
  <div class="log-list">
    <el-card>
      <template #header>
        <div class="card-header">
          <span>{{ $t('log.system_log') }}</span>
          <div class="header-actions">
            <el-button 
              type="danger" 
              :disabled="selectedRows.length === 0"
              @click="handleBatchDelete"
            >
              <el-icon><Delete /></el-icon>
              {{ $t('common.delete_selected') }} ({{ selectedRows.length }})
            </el-button>
            <!-- <el-button type="danger" @click="handleClean">
              <el-icon><Delete /></el-icon>
              清空日志
            </el-button> -->
          </div>
        </div>
      </template>

      <vxe-table
        ref="tableRef"
        :data="tableData"
        :loading="loading"
        border
        resizable
        height="600"
        @checkbox-change="handleSelectionChange"
        @checkbox-all="handleSelectionChange"
      >
        <vxe-column type="checkbox" width="60" />
        <vxe-column type="seq" width="60" :title="$t('table.seq')" />
        <vxe-column field="id" :title="$t('table.id')" width="80" />
        <vxe-column field="level" :title="$t('log.level')" width="100">
          <template #default="{ row }">
            <el-tag :type="getLevelType(row.level)">
              {{ row.level }}
            </el-tag>
          </template>
        </vxe-column>
        <vxe-column field="message" :title="$t('log.message')" />
        <vxe-column field="context" :title="$t('log.context')" />
        <vxe-column field="created_at" :title="$t('log.time')" width="180" />
        <vxe-column :title="$t('table.operation')" width="100" fixed="right">
          <template #default="{ row }">
            <el-button type="primary" link @click="handleView(row)">{{ $t('common.view') }}</el-button>
            <el-button type="danger" link @click="handleDelete(row)">{{ $t('common.delete') }}</el-button>
          </template>
        </vxe-column>
      </vxe-table>

      <vxe-pager
        v-model:current-page="pagination.page"
        v-model:page-size="pagination.pageSize"
        :total="pagination.total"
        :page-sizes="[10, 20, 50, 100]"
        @page-change="handlePageChange"
      />
    </el-card>

    <el-dialog v-model="detailVisible" :title="$t('log.detail')" width="800px">
      <el-descriptions :column="2" border v-if="logDetail">
        <el-descriptions-item :label="$t('table.id')">{{ logDetail.id }}</el-descriptions-item>
        <el-descriptions-item :label="$t('log.level')">
          <el-tag :type="getLevelType(logDetail.level)">
            {{ logDetail.level }}
          </el-tag>
        </el-descriptions-item>
        <el-descriptions-item :label="$t('log.message')" :span="2">{{ logDetail.message }}</el-descriptions-item>
        <el-descriptions-item :label="$t('log.context')" :span="2">
          <pre>{{ JSON.stringify(logDetail.context, null, 2) }}</pre>
        </el-descriptions-item>
        <el-descriptions-item :label="$t('log.time')" :span="2">{{ logDetail.created_at }}</el-descriptions-item>
      </el-descriptions>
    </el-dialog>
  </div>
</template>

<script setup>
import { ref, reactive, onMounted } from 'vue'
import { useI18n } from 'vue-i18n'
import { ElMessage, ElMessageBox } from 'element-plus'
import {
  getSystemLogList,
  getSystemLogDetail,
  deleteSystemLog,
  batchDeleteSystemLogs,
  cleanSystemLogs
} from '../../api/log'

const { t } = useI18n()

const tableRef = ref(null)
const loading = ref(false)
const detailVisible = ref(false)
const logDetail = ref(null)
const selectedRows = ref([])

const pagination = reactive({
  page: 1,
  pageSize: 10,
  total: 0
})

const tableData = ref([])

const getLevelType = (level) => {
  const levelMap = {
    'error': 'danger',
    'warning': 'warning',
    'info': 'success',
    'debug': 'info'
  }
  return levelMap[level?.toLowerCase()] || 'info'
}

const loadData = async () => {
  loading.value = true
  try {
    const params = {
      page: pagination.page,
      page_size: pagination.pageSize
    }
    const res = await getSystemLogList(params)
    if (res.data) {
      tableData.value = res.data.list || []
      pagination.total = res.data.total || 0
    }
  } catch (error) {
    console.error('Load system log list error:', error)
  } finally {
    loading.value = false
  }
}

const handlePageChange = ({ currentPage, pageSize }) => {
  pagination.page = currentPage
  pagination.pageSize = pageSize
  loadData()
}

const handleView = async (row) => {
  try {
    const res = await getSystemLogDetail(row.id)
    if (res.data && res.data.system_log) {
      logDetail.value = res.data.system_log
      detailVisible.value = true
    }
  } catch (error) {
    console.error('Load system log detail error:', error)
  }
}

const handleDelete = async (row) => {
  try {
    await ElMessageBox.confirm(t('log.delete_confirm'), t('form.tip'), {
      confirmButtonText: t('common.confirm'),
      cancelButtonText: t('common.cancel'),
      type: 'warning'
    })
    await deleteSystemLog(row.id)
    ElMessage.success(t('log.delete_success'))
    loadData()
  } catch (error) {
    if (error !== 'cancel') {
      console.error('Delete error:', error)
    }
  }
}

const handleSelectionChange = () => {
  selectedRows.value = tableRef.value?.getCheckboxRecords() || []
}

const handleBatchDelete = async () => {
  if (selectedRows.value.length === 0) {
    ElMessage.warning(t('common.please_select_items'))
    return
  }

  try {
    await ElMessageBox.confirm(t('log.batch_delete_confirm', { count: selectedRows.value.length }), t('form.tip'), {
      confirmButtonText: t('common.confirm'),
      cancelButtonText: t('common.cancel'),
      type: 'warning'
    })
    const ids = selectedRows.value.map(row => row.id)
    await batchDeleteSystemLogs(ids)
    ElMessage.success(t('log.delete_success'))
    selectedRows.value = []
    loadData()
  } catch (error) {
    if (error !== 'cancel') {
      console.error('Batch delete error:', error)
    }
  }
}

const handleClean = async () => {
  try {
    await ElMessageBox.confirm(t('log.clean_confirm'), t('form.warning'), {
      confirmButtonText: t('common.confirm'),
      cancelButtonText: t('common.cancel'),
      type: 'warning'
    })
    await cleanSystemLogs()
    ElMessage.success(t('log.clean_success'))
    selectedRows.value = []
    loadData()
  } catch (error) {
    if (error !== 'cancel') {
      console.error('Clean error:', error)
    }
  }
}

onMounted(() => {
  loadData()
})
</script>

<style scoped>
.log-list {
  background: white;
  border-radius: 4px;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.header-actions {
  display: flex;
  gap: 10px;
}

pre {
  margin: 0;
  padding: 10px;
  background: #f5f5f5;
  border-radius: 4px;
  overflow-x: auto;
}
</style>
