// html/src/views/user/UserBalanceLogList.vue
<template>
  <div class="user-balance-log-list">
    <el-card>
      <template #header>
        <div class="card-header">
          <div class="header-left">
            <el-button 
              type="primary" 
              link 
              :icon="ArrowLeft" 
              @click="handleBack"
              style="margin-right: 10px;"
            >
              {{ $t('user.back') }}
            </el-button>
            <span>{{ $t('user.balance_logs') }}</span>
            <span v-if="searchForm.user_id" class="user-id-display">({{ $t('user.user_id') }}: {{ searchForm.user_id }})</span>
          </div>
        </div>
      </template>

      <!-- 搜索表单 -->
      <SearchForm
        :model="searchForm"
        :fields="searchFields"
        :initial-values="initialSearchValues"
        i18n-prefix="user"
        :loading="loading"
        @search="handleSearch"
        @reset="handleReset"
      />

      <!-- 统计信息 -->
      <el-card v-if="statistics" class="statistics-card" shadow="never">
        <div class="statistics">
          <div class="stat-item">
            <span class="label">{{ $t('user.total_income') }}:</span>
            <span class="value income">¥{{ formatMoney(statistics.total_income) }}</span>
          </div>
          <div class="stat-item">
            <span class="label">{{ $t('user.total_expense') }}:</span>
            <span class="value expense">¥{{ formatMoney(statistics.total_expense) }}</span>
          </div>
          <div class="stat-item">
            <span class="label">{{ $t('user.total_refund') }}:</span>
            <span class="value refund">¥{{ formatMoney(statistics.total_refund) }}</span>
          </div>
          <div class="stat-item">
            <span class="label">{{ $t('user.current_balance') }}:</span>
            <span class="value balance">¥{{ formatMoney(statistics.current_balance) }}</span>
          </div>
        </div>
      </el-card>

      <VxeTable
        :data="tableData"
        :loading="loading"
        :columns="tableColumns"
        :height="500"
      >
        <template #type="{ row }">
          <el-tag v-if="row.type === 'income'" type="success">{{ $t('user.balance_income') }}</el-tag>
          <el-tag v-else-if="row.type === 'expense'" type="danger">{{ $t('user.balance_expense') }}</el-tag>
          <el-tag v-else-if="row.type === 'refund'" type="warning">{{ $t('user.balance_refund') }}</el-tag>
        </template>

        <template #amount="{ row }">
          <span :style="{ color: row.type === 'expense' ? '#f56c6c' : '#67c23a' }">
            {{ row.type === 'expense' ? '-' : '+' }}¥{{ formatMoney(row.amount) }}
          </span>
        </template>

        <template #balance="{ row }">
          <span style="color: var(--el-color-primary); font-weight: bold;">¥{{ formatMoney(row.balance) }}</span>
        </template>

        <template #source="{ row }">
          <span v-if="row.source === 'order'">{{ $t('user.source_order') }}</span>
          <span v-else-if="row.source === 'recharge'">{{ $t('user.source_recharge') }}</span>
          <span v-else-if="row.source === 'withdraw'">{{ $t('user.source_withdraw') }}</span>
          <span v-else-if="row.source === 'manual'">{{ $t('user.source_manual') }}</span>
          <span v-else>{{ row.source }}</span>
        </template>
      </VxeTable>

      <Pagination
        v-model="pagination"
        :auto-load="true"
        :on-page-change="loadData"
      />
    </el-card>
  </div>
</template>

<script setup>
import { ref, reactive, onMounted, computed } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRoute, useRouter } from 'vue-router'
import { ArrowLeft } from '@element-plus/icons-vue'
import SearchForm from '../../components/SearchForm.vue'
import Pagination from '../../components/Pagination.vue'
import VxeTable from '../../components/VxeTable.vue'
import { useListPage } from '../../composables/useListPage'
import { getUserBalanceLogList, getUserBalanceStatistics } from '../../api/userBalanceLog'
import ErrorHandler from '../../utils/errorHandler'
import { forOwn } from 'lodash-es'

const { t } = useI18n()
const route = useRoute()
const router = useRouter()

const userId = route.query.user_id || ''

// 初始搜索值
const initialSearchValues = {
  user_id: userId,
  type: '',
  source: '',
  start_time: '',
  end_time: ''
}

const {
  pagination,
  tableData,
  loading,
  searchForm
} = useListPage({
  fetchApi: getUserBalanceLogList,
  initialSearchForm: initialSearchValues,
  fieldMapping: {},
  defaultSort: 'id:desc',
  tableRef: computed(() => null)
})

// 重写 loadData 以支持自定义参数构建
const loadData = async () => {
  const params = {
    page: pagination.page,
    page_size: pagination.pageSize,
    user_id: searchForm.user_id
  }
  
  // 只添加有值的搜索条件
  if (searchForm.type) params.type = searchForm.type
  if (searchForm.source) params.source = searchForm.source
  if (searchForm.start_time) params.start_time = searchForm.start_time
  if (searchForm.end_time) params.end_time = searchForm.end_time
  
  loading.value = true
  try {
    const res = await getUserBalanceLogList(params)
    if (res.data) {
      tableData.value = res.data.list || []
      pagination.total = res.data.total || 0
    }
  } catch (error) {
    ErrorHandler.handle(error)
  } finally {
    loading.value = false
  }
}

// 设置初始分页大小
pagination.pageSize = 20

// 统计信息
const statistics = ref(null)

// 表格列配置
const tableColumns = computed(() => [
  { field: 'id', title: t('table.id'), width: 180 },
  { field: 'type', title: t('user.type'), width: 100, slot: 'type' },
  { field: 'amount', title: t('user.amount'), width: 120, slot: 'amount' },
  { field: 'balance', title: t('user.balance'), width: 120, slot: 'balance' },
  { field: 'source', title: t('user.source'), width: 100, slot: 'source' },
  { field: 'description', title: t('user.description'), minWidth: 200 },
  { field: 'created_at', title: t('table.created_at'), width: 180 }
])

// 搜索表单字段配置
const searchFields = computed(() => [
  {
    prop: 'type',
    label: t('user.type'),
    type: 'select',
    width: '150px',
    options: [
      { label: t('user.balance_income'), value: 'income' },
      { label: t('user.balance_expense'), value: 'expense' },
      { label: t('user.balance_refund'), value: 'refund' }
    ],
    clearable: true,
    advanced: false
  },
  {
    prop: 'source',
    label: t('user.source'),
    type: 'select',
    width: '150px',
    options: [
      { label: t('user.source_order'), value: 'order' },
      { label: t('user.source_recharge'), value: 'recharge' },
      { label: t('user.source_withdraw'), value: 'withdraw' },
      { label: t('user.source_manual'), value: 'manual' }
    ],
    clearable: true,
    advanced: false
  }
])

// 加载统计数据
const loadStatistics = async () => {
  if (!searchForm.user_id) {
    return
  }

  try {
    const params = {
      user_id: searchForm.user_id,
      start_time: searchForm.start_time,
      end_time: searchForm.end_time
    }
    const res = await getUserBalanceStatistics(params)
    if (res.code === 200) {
      statistics.value = res.data.statistics
    }
  } catch (error) {
    ErrorHandler.handle(error)
  }
}

// 搜索处理（同时加载列表和统计）
const handleSearch = () => {
  pagination.page = 1
  loadData()
  loadStatistics()
}

// 重置处理（同时加载列表和统计）
const handleReset = () => {
  // 重置搜索表单
  forOwn(searchForm, (value, key) => {
    searchForm[key] = initialSearchValues[key] !== undefined ? initialSearchValues[key] : ''
  })
  pagination.page = 1
  loadData()
  loadStatistics()
}

// 返回按钮处理
const handleBack = () => {
  // 返回上一页，如果没有历史记录则返回用户列表
  if (window.history.length > 1) {
    router.go(-1)
  } else {
    router.push('/users')
  }
}

// 格式化金额
const formatMoney = (amount) => {
  return Number(amount || 0).toFixed(2)
}

onMounted(() => {
  if (searchForm.user_id) {
    loadData()
    loadStatistics()
  }
})
</script>

<style scoped>
.user-balance-log-list {
  padding: 20px;
}

.header-left {
  display: flex;
  align-items: center;
}

.user-id-display {
  margin-left: 10px;
  color: #909399;
  font-size: 14px;
}

.search-form {
  margin-bottom: 20px;
}

.statistics-card {
  margin-bottom: 20px;
}

.statistics {
  display: flex;
  gap: 30px;
  flex-wrap: wrap;
}

.stat-item {
  display: flex;
  align-items: center;
  gap: 10px;
}

.stat-item .label {
  font-weight: 500;
}

.stat-item .value {
  font-size: 18px;
  font-weight: bold;
}

.stat-item .value.income {
  color: #67c23a;
}

.stat-item .value.expense {
  color: #f56c6c;
}

.stat-item .value.refund {
  color: #e6a23c;
}

.stat-item .value.balance {
  color: var(--el-color-primary);
}
</style>

// html-react/src/pages/user/UserBalanceLogList.tsx
import { useEffect, useMemo, useState } from 'react'
import { Button, Card, Col, Row, Space, Statistic, Table, Tag } from 'antd'
import type { ColumnsType, TablePaginationConfig } from 'antd/es/table'
import { ArrowLeftOutlined } from '@ant-design/icons'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { getUserBalanceLogList, getUserBalanceStatistics } from '@/api/userBalanceLog'
import { useListPage } from '@/hooks/useListPage'
import { useUnhandledError } from '@/hooks/useUnhandledError'
import PageContainer from '@/components/PageContainer'
import SearchForm from '@/components/SearchForm'
import { entityField } from '@/utils/normalize'

interface LogRow {
  id: number | string
  type?: string
  amount?: number | string
  balance?: number | string
  source?: string
  description?: string
  created_at?: string
}

function formatMoney(amount: number | string | undefined) {
  return Number(amount || 0).toFixed(2)
}

export default function UserBalanceLogList() {
  const { t } = useTranslation()
  const navigate = useNavigate()
  const [searchParams] = useSearchParams()
  const showError = useUnhandledError()
  const userId = searchParams.get('user_id') || ''
  const [stats, setStats] = useState<{
    total_income?: number | string
    total_expense?: number | string
    total_refund?: number | string
    current_balance?: number | string
  } | null>(null)

  const {
    tableData,
    loading,
    pagination,
    searchForm,
    setSearchForm,
    loadData,
    handleSearch,
    handleReset,
    refresh,
  } = useListPage<LogRow, Record<string, unknown>>({
    fetchApi: getUserBalanceLogList as never,
    initialSearchForm: { user_id: userId, type: '', source: '' },
    defaultSort: 'id:desc',
    normalizeRows: true,
    transformData: (row) => {
      const record = row as unknown as Record<string, unknown>
      return {
        id: entityField(record, 'id', '')!,
        type: String(entityField(record, 'type', '') ?? ''),
        amount: entityField(record, 'amount', 0) as number | string,
        balance: entityField(record, 'balance', 0) as number | string,
        source: String(entityField(record, 'source', '') ?? ''),
        description: String(entityField(record, 'description', '') ?? ''),
        created_at: String(entityField(record, 'created_at', '') ?? ''),
      }
    },
  })

  const loadStats = async (uid = String(searchForm.user_id || userId || '')) => {
    if (!uid) {
      setStats(null)
      return
    }
    try {
      const res = await getUserBalanceStatistics({ user_id: uid })
      setStats((res.data as typeof stats) || null)
    } catch (error) {
      showError(error, t('common.query_failed'))
    }
  }

  useEffect(() => {
    if (userId && String(searchForm.user_id || '') !== userId) {
      setSearchForm({ ...searchForm, user_id: userId })
    }
    void loadStats(userId)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [userId])

  const columns: ColumnsType<LogRow> = useMemo(() => {
    const typeTag = (type?: string) => {
      if (type === 'income') return <Tag color="success">{t('user.balance_income')}</Tag>
      if (type === 'expense') return <Tag color="error">{t('user.balance_expense')}</Tag>
      if (type === 'refund') return <Tag color="warning">{t('user.balance_refund')}</Tag>
      return type || '-'
    }
    const sourceLabel = (source?: string) => {
      const map: Record<string, string> = {
        order: t('user.source_order'),
        recharge: t('user.source_recharge'),
        withdraw: t('user.source_withdraw'),
        manual: t('user.source_manual'),
      }
      return (source && map[source]) || source || '-'
    }
    return [
      { title: t('table.id'), dataIndex: 'id', width: 80 },
      { title: t('user.type'), dataIndex: 'type', width: 100, render: (v: string) => typeTag(v) },
      {
        title: t('user.amount'),
        dataIndex: 'amount',
        width: 120,
        render: (amount, row) => (
          <span style={{ color: row.type === 'expense' ? '#ff4d4f' : '#52c41a' }}>
            {row.type === 'expense' ? '-' : '+'}¥{formatMoney(amount)}
          </span>
        ),
      },
      {
        title: t('user.balance'),
        dataIndex: 'balance',
        width: 120,
        render: (balance) => <span style={{ fontWeight: 600 }}>¥{formatMoney(balance)}</span>,
      },
      { title: t('user.source'), dataIndex: 'source', width: 100, render: (v: string) => sourceLabel(v) },
      { title: t('user.description'), dataIndex: 'description', ellipsis: true },
      { title: t('table.created_at'), dataIndex: 'created_at', width: 180 },
    ]
  }, [t])

  return (
    <PageContainer
      title={
        <Space>
          <Button type="link" icon={<ArrowLeftOutlined />} onClick={() => navigate(-1)}>
            {t('user.back')}
          </Button>
          <span>
            {t('user.balance_logs')}
            {searchForm.user_id ? ` (${t('user.user_id')}: ${String(searchForm.user_id)})` : ''}
          </span>
        </Space>
      }
      extra={
        <Button
          onClick={() => {
            void refresh()
            void loadStats()
          }}
        >
          {t('common.refresh')}
        </Button>
      }
    >
      {stats && (
        <Card style={{ marginBottom: 16 }}>
          <Row gutter={16}>
            <Col span={6}>
              <Statistic title={t('user.total_income')} value={formatMoney(stats.total_income)} prefix="¥" />
            </Col>
            <Col span={6}>
              <Statistic title={t('user.total_expense')} value={formatMoney(stats.total_expense)} prefix="¥" />
            </Col>
            <Col span={6}>
              <Statistic title={t('user.total_refund')} value={formatMoney(stats.total_refund)} prefix="¥" />
            </Col>
            <Col span={6}>
              <Statistic title={t('user.current_balance')} value={formatMoney(stats.current_balance)} prefix="¥" />
            </Col>
          </Row>
        </Card>
      )}

      <SearchForm
        fields={[
          { name: 'user_id', label: t('user.user_id') },
          {
            name: 'type',
            label: t('user.type'),
            type: 'select',
            options: [
              { label: t('user.balance_income'), value: 'income' },
              { label: t('user.balance_expense'), value: 'expense' },
              { label: t('user.balance_refund'), value: 'refund' },
            ],
          },
          {
            name: 'source',
            label: t('user.source'),
            type: 'select',
            options: [
              { label: t('user.source_order'), value: 'order' },
              { label: t('user.source_recharge'), value: 'recharge' },
              { label: t('user.source_withdraw'), value: 'withdraw' },
              { label: t('user.source_manual'), value: 'manual' },
            ],
          },
        ]}
        values={searchForm}
        onChange={(values) => setSearchForm(values as typeof searchForm)}
        onSearch={() => {
          handleSearch()
          void loadStats(String(searchForm.user_id || ''))
        }}
        onReset={() => {
          handleReset()
          void loadStats(userId)
        }}
      />

      <Table<LogRow>
        rowKey="id"
        loading={loading}
        columns={columns}
        dataSource={tableData}
        scroll={{ x: 1000 }}
        pagination={{
          current: pagination.page,
          pageSize: pagination.pageSize,
          total: pagination.total,
          showSizeChanger: true,
          showTotal: (total) => t('common.total', { total }),
        }}
        onChange={(pager: TablePaginationConfig) => {
          void loadData({
            currentPage: pager.current || 1,
            pageSize: pager.pageSize || pagination.pageSize,
          })
        }}
      />
    </PageContainer>
  )
}
