// html-react/src/pages/dev/FormDemo.tsx
import { useState } from 'react'
import {
  App,
  Button,
  Card,
  Cascader,
  Checkbox,
  ColorPicker,
  Col,
  DatePicker,
  Form,
  Input,
  InputNumber,
  Radio,
  Rate,
  Row,
  Select,
  Slider,
  Space,
  Switch,
} from 'antd'
import { useTranslation } from 'react-i18next'
import PageContainer from '@/components/PageContainer'
import WangEditor from '@/components/WangEditor'
import MarkdownEditor from '@/components/MarkdownEditor'
import request from '@/utils/request'

export default function FormDemo() {
  const { t } = useTranslation()
  const { message } = App.useApp()
  const [form] = Form.useForm()
  const [preview, setPreview] = useState<Record<string, unknown>>({})
  const [loadingApi, setLoadingApi] = useState(false)

  const regionOptions = [
    {
      value: 'china',
      label: t('form_demo.country_china'),
      children: [
        {
          value: 'guangdong',
          label: t('form_demo.province_guangdong'),
          children: [{ value: 'guangzhou', label: t('form_demo.city_guangzhou') }],
        },
      ],
    },
  ]

  const fillSample = () => {
    form.setFieldsValue({
      username: 'demo_user',
      password: '123456',
      intro: t('form_demo.intro'),
      gender: 'male',
      hobbies: ['reading', 'music'],
      role: 'admin',
      birthday: undefined,
      meeting_at: undefined,
      active_days: undefined,
      score: 88,
      satisfaction: 4,
      volume: 60,
      enabled: true,
      color: '#1677ff',
      region: ['china', 'guangdong', 'guangzhou'],
      rich_content_wang: '<p>WangEditor demo content</p>',
      rich_content_markdown: '**Markdown** demo content',
    })
    setPreview(form.getFieldsValue(true))
  }

  const loadApiData = async () => {
    setLoadingApi(true)
    try {
      const res = await request({ url: '/form-demo/data', method: 'get' })
      const data = (res.data || {}) as Record<string, unknown>
      form.setFieldsValue(data)
      setPreview(form.getFieldsValue(true))
      message.success(t('form_demo.loaded_from_api'))
    } catch {
      message.warning(t('common.query_failed'))
    } finally {
      setLoadingApi(false)
    }
  }

  return (
    <PageContainer title={t('form_demo.title', { defaultValue: t('menu.form_demo') })}>
      <Row gutter={[16, 16]}>
        <Col xs={24} lg={14}>
          <Card>
            <Form
              form={form}
              layout="vertical"
              initialValues={{
                gender: 'male',
                hobbies: ['reading'],
                role: 'viewer',
                score: 60,
                satisfaction: 3,
                volume: 40,
                enabled: true,
                color: '#1677ff',
                rich_content_wang: '',
                rich_content_markdown: '',
              }}
              onValuesChange={(_, all) => setPreview(all)}
              onFinish={(values) => {
                setPreview(values)
                message.success(t('common.success'))
              }}
            >
              <Form.Item name="username" label={t('form_demo.username')} rules={[{ required: true }]}>
                <Input />
              </Form.Item>
              <Form.Item name="password" label={t('common.password')}>
                <Input.Password />
              </Form.Item>
              <Form.Item name="intro" label={t('form_demo.intro')}>
                <Input.TextArea rows={3} />
              </Form.Item>
              <Form.Item
                name="gender"
                label={t('form_demo.gender')}
                rules={[{ required: true, message: t('form_demo.gender_required') }]}
              >
                <Radio.Group
                  options={[
                    { label: t('form_demo.gender_male'), value: 'male' },
                    { label: t('form_demo.gender_female'), value: 'female' },
                  ]}
                />
              </Form.Item>
              <Form.Item name="hobbies" label={t('form_demo.hobbies')}>
                <Checkbox.Group
                  options={[
                    { label: t('form_demo.hobby_reading'), value: 'reading' },
                    { label: t('form_demo.hobby_sports'), value: 'sports' },
                    { label: t('form_demo.hobby_music'), value: 'music' },
                  ]}
                />
              </Form.Item>
              <Form.Item name="role" label={t('form_demo.role')}>
                <Select
                  options={[
                    { label: t('form_demo.role_admin'), value: 'admin' },
                    { label: t('form_demo.role_editor'), value: 'editor' },
                    { label: t('form_demo.role_viewer'), value: 'viewer' },
                  ]}
                />
              </Form.Item>
              <Form.Item name="birthday" label={t('form_demo.birthday')}>
                <DatePicker style={{ width: '100%' }} />
              </Form.Item>
              <Form.Item name="meeting_at" label={t('form_demo.meeting_at')}>
                <DatePicker showTime style={{ width: '100%' }} />
              </Form.Item>
              <Form.Item name="active_days" label={t('form_demo.active_days')}>
                <DatePicker.RangePicker style={{ width: '100%' }} />
              </Form.Item>
              <Form.Item name="score" label={t('form_demo.score_input_number')}>
                <InputNumber min={0} max={100} style={{ width: '100%' }} />
              </Form.Item>
              <Form.Item name="satisfaction" label={t('form_demo.satisfaction')}>
                <Rate />
              </Form.Item>
              <Form.Item name="volume" label={t('form_demo.volume')}>
                <Slider />
              </Form.Item>
              <Form.Item name="enabled" label={t('common.status')} valuePropName="checked">
                <Switch />
              </Form.Item>
              <Form.Item
                name="color"
                label={t('form_demo.color')}
                getValueFromEvent={(color) => (typeof color === 'string' ? color : color?.toHexString?.())}
              >
                <ColorPicker showText />
              </Form.Item>
              <Form.Item name="region" label={t('form_demo.region')}>
                <Cascader options={regionOptions} />
              </Form.Item>
              <Form.Item name="rich_content_wang" label={t('form_demo.rich_content_wang')}>
                <WangEditor height={280} placeholder={t('form_demo.rich_content_wang_placeholder')} />
              </Form.Item>
              <Form.Item name="rich_content_markdown" label={t('form_demo.rich_content_markdown')}>
                <MarkdownEditor height={280} placeholder={t('form_demo.rich_content_markdown_placeholder')} />
              </Form.Item>
              <Form.Item>
                <Space wrap>
                  <Button type="primary" htmlType="submit">
                    {t('common.submit')}
                  </Button>
                  <Button onClick={() => form.resetFields()}>{t('common.reset')}</Button>
                  <Button onClick={fillSample}>{t('form_demo.fill_sample')}</Button>
                  <Button loading={loadingApi} onClick={() => void loadApiData()}>
                    {t('form_demo.load_api_data')}
                  </Button>
                </Space>
              </Form.Item>
            </Form>
          </Card>
        </Col>
        <Col xs={24} lg={10}>
          <Card title={t('form_demo.preview')}>
            <pre style={{ margin: 0, whiteSpace: 'pre-wrap', wordBreak: 'break-word' }}>
              {JSON.stringify(preview, null, 2)}
            </pre>
          </Card>
        </Col>
      </Row>
    </PageContainer>
  )
}

// html/src/views/dev/FormDemo.vue
<template>
  <div class="form-demo-page">
    <el-card>
      <template #header>
        <div class="card-header">
          <span>{{ t('form_demo.title') }}</span>
          <div class="header-actions">
            <el-button @click="loadFromApi">{{ t('form_demo.load_api_data') }}</el-button>
            <el-button @click="fillSampleData">{{ t('form_demo.fill_sample') }}</el-button>
            <el-button @click="resetForm">{{ t('common.reset') }}</el-button>
          </div>
        </div>
      </template>

      <el-form
        ref="formRef"
        :model="formData"
        :rules="formRules"
        label-width="250px"
      >
        <FormField
          v-for="field in formFields"
          :key="field.prop"
          :field="field"
          :model="formData"
        >
          <template v-if="field.prop === 'custom_note'">
            <el-input
              v-model="formData.custom_note"
              :placeholder="t('form_demo.custom_note_placeholder')"
              clearable
            />
            <div class="custom-tip">{{ t('form_demo.custom_slot_tip') }}</div>
          </template>
        </FormField>
      </el-form>

      <div class="actions">
        <el-button type="primary" @click="submitForm">{{ t('common.submit') }}</el-button>
      </div>
    </el-card>

    <el-card class="preview-card">
      <template #header>
        <span>{{ t('form_demo.preview') }}</span>
      </template>
      <pre>{{ previewJson }}</pre>
    </el-card>
  </div>
</template>

<script setup>
import { computed, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { useI18n } from 'vue-i18n'
import FormField from '@/components/Form/FormField.vue'
import request from '@/utils/request'

const { t } = useI18n()

const formRef = ref(null)

const getInitialValue = () => ({
  username: '',
  password: '',
  intro: '',
  role: '',
  role_remote: null,
  department_id: null,
  department_remote_id: null,
  gender: '',
  gender_remote: null,
  interests: [],
  interests_remote: [],
  hobbies: [],
  hobbies_remote: [],
  birthday: '',
  meeting_at: '',
  active_days: [],
  active_period: [],
  transfer_permissions: [],
  transfer_permissions_remote: [],
  score: 0,
  score_input_number: 0,
  score_input_number_suffix: 0,
  satisfaction: 3,
  volume: 40,
  enabled: true,
  icon_name: '',
  icon_name_remote: '',
  color: '#409EFF',
  region: [],
  region_remote: [],
  custom_note: ''
})

const formData = reactive(getInitialValue())

const formRules = computed(() => ({
  username: [{ required: true, message: t('form.username_required'), trigger: 'blur' }],
  password: [{ required: true, message: t('form.password_required'), trigger: 'blur' }],
  gender: [{ required: true, message: t('form_demo.gender_required'), trigger: 'change' }]
}))

const genderOptions = computed(() => [
  { label: t('form_demo.gender_male'), value: 'male' },
  { label: t('form_demo.gender_female'), value: 'female' }
])

const hobbyOptions = computed(() => [
  { label: t('form_demo.hobby_reading'), value: 'reading' },
  { label: t('form_demo.hobby_sports'), value: 'sports' },
  { label: t('form_demo.hobby_music'), value: 'music' }
])

const roleOptions = computed(() => [
  { label: t('form_demo.role_admin'), value: 'admin' },
  { label: t('form_demo.role_editor'), value: 'editor' },
  { label: t('form_demo.role_viewer'), value: 'viewer' }
])

const transferOptions = computed(() => [
  { label: t('form_demo.permission_user_view'), value: 'user.view' },
  { label: t('form_demo.permission_user_edit'), value: 'user.edit' },
  { label: t('form_demo.permission_role_view'), value: 'role.view' },
  { label: t('form_demo.permission_role_edit'), value: 'role.edit' },
  { label: t('form_demo.permission_menu_manage'), value: 'menu.manage' }
])

const departmentTree = computed(() => [
  {
    id: 1,
    name: t('form_demo.dept_headquarters'),
    children: [
      { id: 11, name: t('form_demo.dept_rd') },
      { id: 12, name: t('form_demo.dept_operations') }
    ]
  }
])

const formFields = computed(() => [
  { prop: 'username', label: t('table.username'), type: 'input' },
  { prop: 'password', label: t('common.password'), type: 'password' },
  { prop: 'intro', label: t('common.description'), type: 'textarea', rows: 3 },
  { prop: 'role', label: t('table.roles'), type: 'select', options: roleOptions.value },
  {
    prop: 'role_remote',
    label: t('form_demo.role_remote'),
    type: 'select',
    apiUrl: '/options?type=form_demo&scene=default',
    clearable: true
  },
  {
    prop: 'department_id',
    label: t('table.department'),
    type: 'tree-select',
    treeData: () => departmentTree.value,
    treeProps: { label: 'name', value: 'id', children: 'children' },
    clearable: true
  },
  {
    prop: 'department_remote_id',
    label: t('form_demo.department_remote'),
    type: 'tree-select',
    apiUrl: '/options?type=form_demo&scene=tree',
    treeProps: { label: 'name', value: 'id', children: 'children' },
    clearable: true
  },
  { prop: 'gender', label: t('form_demo.gender'), type: 'radio', options: genderOptions.value },
  {
    prop: 'gender_remote',
    label: t('form_demo.gender_remote'),
    type: 'radio',
    apiUrl: '/options?type=form_demo&scene=default'
  },
  { prop: 'interests', label: t('form_demo.interests'), type: 'checkbox', options: hobbyOptions.value },
  {
    prop: 'interests_remote',
    label: t('form_demo.interests_remote'),
    type: 'checkbox',
    apiUrl: '/options?type=form_demo&scene=default'
  },
  { prop: 'hobbies', label: t('form_demo.hobbies'), type: 'checkbox-group', options: hobbyOptions.value },
  {
    prop: 'hobbies_remote',
    label: t('form_demo.hobbies_remote'),
    type: 'checkbox-group',
    apiUrl: '/options?type=form_demo&scene=default'
  },
  { prop: 'birthday', label: t('form_demo.birthday'), type: 'date' },
  { prop: 'meeting_at', label: t('form_demo.meeting_at'), type: 'datetime' },
  { prop: 'active_days', label: t('form_demo.active_days'), type: 'daterange' },
  { prop: 'active_period', label: t('form_demo.active_period'), type: 'datetimerange' },
  {
    prop: 'transfer_permissions',
    label: t('form_demo.transfer_permissions'),
    type: 'transfer',
    options: transferOptions.value,
    titles: [t('form_demo.transfer_source'), t('form_demo.transfer_target')]
  },
  {
    prop: 'transfer_permissions_remote',
    label: t('form_demo.transfer_permissions_remote'),
    type: 'transfer',
    apiUrl: '/options?type=form_demo&scene=default',
    optionLabelKey: 'label',
    optionValueKey: 'value',
    titles: [t('form_demo.transfer_source'), t('form_demo.transfer_target')]
  },
  { prop: 'score', label: t('form_demo.score'), type: 'number', min: 0, max: 100 },
  {
    prop: 'score_input_number',
    label: t('form_demo.score_input_number'),
    type: 'input-number',
    min: 0,
    max: 999,
    prefix: '￥'
  },
  {
    prop: 'score_input_number_suffix',
    label: t('form_demo.score_input_number_suffix'),
    type: 'input-number',
    min: 0,
    max: 999,
    suffix: 'RMB'
  },
  { prop: 'satisfaction', label: t('form_demo.satisfaction'), type: 'rate' },
  { prop: 'volume', label: t('form_demo.volume'), type: 'slider', min: 0, max: 100, step: 5 },
  { prop: 'enabled', label: t('table.status'), type: 'switch' },
  { prop: 'icon_name', label: t('form_demo.icon_name'), type: 'icon' },
  {
    prop: 'icon_name_remote',
    label: t('form_demo.icon_name_remote'),
    type: 'icon',
    apiUrl: '/options?type=form_demo&scene=icon'
  },
  { prop: 'color', label: t('form_demo.color'), type: 'color', showAlpha: false },
  {
    prop: 'region',
    label: t('form_demo.region'),
    type: 'cascader',
    options: [
      {
        value: 'china',
        label: t('form_demo.country_china'),
        children: [
          {
            value: 'guangdong',
            label: t('form_demo.province_guangdong'),
            children: [{ value: 'guangzhou', label: t('form_demo.city_guangzhou') }]
          }
        ]
      }
    ]
  },
  {
    prop: 'region_remote',
    label: t('form_demo.region_remote'),
    type: 'cascader',
    apiUrl: '/options?type=form_demo&scene=cascader',
    cascaderProps: { value: 'id', label: 'name', children: 'children' }
  },
  {
    prop: 'custom_note',
    label: t('form_demo.custom_slot'),
    type: 'custom'
  }
])

const previewJson = computed(() => JSON.stringify(formData, null, 2))

const resetForm = () => {
  Object.assign(formData, getInitialValue())
  formRef.value?.resetFields()
}

const fillSampleData = () => {
  Object.assign(formData, {
    username: 'demo_admin',
    password: '123456',
    intro: 'This is a sample form for FormField testing.',
    role: 'editor',
    role_remote: 'A',
    department_id: 11,
    department_remote_id: 11,
    gender: 'male',
    gender_remote: 'A',
    interests: ['sports'],
    interests_remote: ['A'],
    hobbies: ['reading', 'music'],
    hobbies_remote: ['A'],
    birthday: '2026-03-31',
    meeting_at: '2026-03-31 09:30:00',
    active_days: ['2026-03-01', '2026-03-31'],
    active_period: ['2026-03-01 08:00:00', '2026-03-31 18:00:00'],
    transfer_permissions: ['user.view', 'role.view'],
    transfer_permissions_remote: ['A', 'C'],
    score: 88,
    score_input_number: 92,
    score_input_number_suffix: 120,
    satisfaction: 4,
    volume: 65,
    enabled: true,
    icon_name: 'User',
    icon_name_remote: 'Setting',
    color: '#67C23A',
    region: ['china', 'guangdong', 'guangzhou'],
    region_remote: [100, 110, 111],
    custom_note: 'This field is rendered via FormField default slot.'
  })
}

const loadFromApi = async () => {
  try {
    const res = await request({
      url: '/form-demo/data',
      method: 'get'
    })
    if (res?.data) {
      Object.assign(formData, res.data)
      ElMessage.success(t('form_demo.loaded_from_api'))
    }
  } catch {
    // Global interceptor handles error
  }
}

const submitForm = async () => {
  if (!formRef.value) return
  const valid = await formRef.value.validate().catch(() => false)
  if (!valid) return
  ElMessage.success(t('common.success'))
}
</script>

<style scoped>
.form-demo-page {
  padding: 20px;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.header-actions {
  display: flex;
  gap: 8px;
}

.actions {
  margin-top: 16px;
}

.preview-card {
  margin-top: 16px;
}

pre {
  margin: 0;
  padding: 12px;
  border-radius: 4px;
  background: var(--el-fill-color-light);
  overflow: auto;
}

.custom-tip {
  margin-top: 6px;
  font-size: 12px;
  color: var(--el-text-color-secondary);
}
</style>
