// html-react/src/pages/order/OrderList.tsx
﻿import { useMemo, useState } from 'react'
import {
  App,
  Descriptions,
  Divider,
  Drawer,
  Form,
  Input,
  Modal,
  Select,
  Space,
  Table,
  Tag,
  Upload,
} from 'antd'
import type { ColumnsType, TablePaginationConfig } from 'antd/es/table'
import type { UploadProps } from 'antd/es/upload'
import { UploadOutlined } from '@ant-design/icons'
import { useTranslation } from 'react-i18next'
import {
  deleteOrder,
  exportOrder,
  getOrderDetail,
  getOrderList,
  importOrder,
  updateOrder,
} from '@/api/order'
import { useListPage } from '@/hooks/useListPage'
import { useCrudActions } from '@/hooks/useCrudActions'
import { usePermission } from '@/hooks/usePermission'
import { useUnhandledError } from '@/hooks/useUnhandledError'
import { useQueuedExport } from '@/hooks/useQueuedExport'
import PageContainer from '@/components/PageContainer'
import SearchForm from '@/components/SearchForm'
import PermissionButton from '@/components/PermissionButton'
import { entityField } from '@/utils/normalize'
import OrderFormModal from './OrderFormModal'
import {
  createOrderInitialSearchForm,
  formatOrderAmount,
  formatOrderTime,
  getOrderDetailField,
  getOrderDetails,
  getOrderStatusTagColor,
  getOrderStatusText,
  ORDER_STATUS_OPTIONS,
  type OrderSearchForm,
} from './order.config'

interface OrderRow {
  id: number | string
  order_no?: string
  user_id?: number | string
  amount?: number | string
  status?: string
  remark?: string
  created_at?: string
  details?: Record<string, unknown>[]
  name?: string
}

interface OrderDetailPayload {
  order?: Record<string, unknown>
  details?: Record<string, unknown>[]
}

const initialSearch = createOrderInitialSearchForm()

export default function OrderList() {
  const { t } = useTranslation()
  const { message, modal } = App.useApp()
  const showError = useUnhandledError()
  const { getButtonState } = usePermission()
  const [editForm] = Form.useForm()

  const [createOpen, setCreateOpen] = useState(false)
  const [detailOpen, setDetailOpen] = useState(false)
  const [orderDetail, setOrderDetail] = useState<OrderDetailPayload | null>(null)
  const [editOpen, setEditOpen] = useState(false)
  const [editSubmitting, setEditSubmitting] = useState(false)
  const [currentEditOrder, setCurrentEditOrder] = useState<Record<string, unknown> | null>(null)
  const [importing, setImporting] = useState(false)

  const {
    tableData,
    loading,
    pagination,
    searchForm,
    onSearchFormChange,
    loadData,
    handleSearch,
    handleReset,
    handleSortChange,
    refresh,
  } = useListPage<OrderRow, OrderSearchForm>({
    fetchApi: getOrderList,
    initialSearchForm: initialSearch,
    defaultSort: 'created_at:desc',
    normalizeRows: true,
    transformData: (row) => {
      const record = row
      return {
        id: entityField(record, 'id', '')!,
        order_no: String(entityField(record, 'order_no', '') ?? ''),
        user_id: entityField(record, 'user_id', '') as number | string,
        amount: entityField(record, 'amount', 0) as number | string,
        status: String(entityField(record, 'status', '') ?? ''),
        remark: String(entityField(record, 'remark', '') ?? ''),
        created_at: String(entityField(record, 'created_at', '') ?? ''),
        details: getOrderDetails(record),
        name: String(entityField(record, 'order_no', '') ?? ''),
      }
    },
  })

  const { toolbar } = useCrudActions({
    createPermission: 'order.store',
    onRefresh: refresh,
    onCreate: () => setCreateOpen(true),
  })

  const { exporting, handleExport } = useQueuedExport({
    exportApi: exportOrder,
    getParams: () => ({ ...searchForm }),
    redirectPath: '/exports',
  })

  const statusOptions = useMemo(
    () =>
      ORDER_STATUS_OPTIONS.map((item) => ({
        label: t(item.labelKey),
        value: item.value,
      })),
    [t],
  )

  const openDetail = async (row: OrderRow) => {
    try {
      const orderNo = row.order_no
      const res = await getOrderDetail(row.id, orderNo ? { order_no: orderNo } : {})
      setOrderDetail((res.data || {}) as OrderDetailPayload)
      setDetailOpen(true)
    } catch (error) {
      showError(error, t('common.query_failed'))
    }
  }

  const openEdit = async (row: OrderRow) => {
    try {
      const orderNo = row.order_no
      const res = await getOrderDetail(row.id, orderNo ? { order_no: orderNo } : {})
      const data = (res.data || {}) as OrderDetailPayload
      if (!data.order) {
        message.error(t('common.query_failed'))
        return
      }
      setCurrentEditOrder(data.order)
      editForm.setFieldsValue({
        status: String(getOrderDetailField(data.order, 'status', 'pending')),
        remark: String(getOrderDetailField(data.order, 'remark', '') || ''),
      })
      setEditOpen(true)
    } catch (error) {
      showError(error, t('common.query_failed'))
    }
  }

  const closeEdit = () => {
    setEditOpen(false)
    setCurrentEditOrder(null)
    editForm.resetFields()
  }

  const handleEditSubmit = async () => {
    if (!currentEditOrder) return
    try {
      const values = await editForm.validateFields()
      setEditSubmitting(true)
      const orderNo = String(getOrderDetailField(currentEditOrder, 'order_no', '') || '')
      const id = getOrderDetailField(currentEditOrder, 'id', '') as string | number
      await updateOrder(id, {
        status: values.status,
        remark: values.remark || '',
        order_no: orderNo,
      })
      message.success(t('common.update_success'))
      closeEdit()
      await refresh()
    } catch (error) {
      if ((error as { errorFields?: unknown })?.errorFields) return
      showError(error, t('common.operation_failed'))
    } finally {
      setEditSubmitting(false)
    }
  }

  const handleDelete = (row: OrderRow) => {
    modal.confirm({
      title: t('common.delete_confirm'),
      content: row.order_no || undefined,
      okType: 'danger',
      onOk: async () => {
        try {
          await deleteOrder(row.id, row.order_no ? { order_no: row.order_no } : {})
          message.success(t('common.delete_success'))
          await refresh()
        } catch (error) {
          showError(error, t('common.operation_failed'))
          throw error
        }
      },
    })
  }

  const uploadProps: UploadProps = {
    accept: '.csv',
    showUploadList: false,
    beforeUpload: (file) => {
      if (!file.name.toLowerCase().endsWith('.csv')) {
        message.error(t('common.invalid_file_type'))
        return false
      }
      setImporting(true)
      void importOrder(file as File)
        .then((res) => {
          const payload = (res.data || {}) as Record<string, unknown>
          const result = ((payload.data || payload) as Record<string, unknown>) || {}
          const successCount = Number(result.success_count || 0)
          const failedCount = Number(result.failed_count || 0)
          const errors = Array.isArray(result.errors) ? (result.errors as string[]) : []

          if (successCount > 0) {
            message.success(t('common.import_success'))
            if (failedCount > 0 && errors.length) {
              message.warning(errors.slice(0, 10).join('\n'))
            }
            void refresh()
          } else {
            message.warning(t('common.import_no_data'))
            if (errors.length) {
              message.error(errors.slice(0, 10).join('\n'))
            }
          }
        })
        .catch((error) => showError(error, t('common.operation_failed')))
        .finally(() => setImporting(false))
      return false
    },
  }

  const detailColumns: ColumnsType<Record<string, unknown>> = [
    {
      title: t('order.product_name'),
      dataIndex: 'product_name',
      width: 200,
      render: (_, detail) => String(entityField(detail, 'product_name', '-') ?? '-'),
    },
    {
      title: t('order.price'),
      dataIndex: 'price',
      width: 120,
      render: (_, detail) => formatOrderAmount(entityField(detail, 'price')),
    },
    {
      title: t('order.quantity'),
      dataIndex: 'quantity',
      width: 100,
      render: (_, detail) => Number(entityField(detail, 'quantity', 0) ?? 0),
    },
    {
      title: t('order.subtotal'),
      dataIndex: 'subtotal',
      width: 120,
      render: (_, detail) => formatOrderAmount(entityField(detail, 'subtotal')),
    },
  ]

  const columns: ColumnsType<OrderRow> = [
    { title: t('table.id'), dataIndex: 'id', width: 80, sorter: true },
    { title: t('order.order_no'), dataIndex: 'order_no' },
    { title: t('order.user_id'), dataIndex: 'user_id', width: 100 },
    {
      title: t('order.amount'),
      dataIndex: 'amount',
      width: 120,
      sorter: true,
      render: (v) => formatOrderAmount(v),
    },
    {
      title: t('order.status'),
      dataIndex: 'status',
      width: 110,
      render: (status: string) => (
        <Tag color={getOrderStatusTagColor(status)}>{getOrderStatusText(t, status)}</Tag>
      ),
    },
    {
      title: t('order.created_at'),
      dataIndex: 'created_at',
      width: 180,
      sorter: true,
    },
    {
      title: t('order.remark'),
      dataIndex: 'remark',
      width: 200,
      ellipsis: true,
      render: (v) => v || '-',
    },
    {
      title: t('common.operation'),
      key: 'operation',
      width: 220,
      fixed: 'right',
      render: (_, row) => (
        <Space>
          {getButtonState('order.show').show && (
            <PermissionButton permission="order.show" type="link" onClick={() => void openDetail(row)}>
              {t('common.view')}
            </PermissionButton>
          )}
          {getButtonState('order.update').show && (
            <PermissionButton permission="order.update" type="link" onClick={() => void openEdit(row)}>
              {t('common.edit')}
            </PermissionButton>
          )}
          {getButtonState('order.destroy').show && (
            <PermissionButton permission="order.destroy" type="link" danger onClick={() => handleDelete(row)}>
              {t('common.delete')}
            </PermissionButton>
          )}
        </Space>
      ),
    },
  ]

  const orderInfo = orderDetail?.order

  return (
    <PageContainer
      title={t('menu.order')}
      extra={
        <Space wrap>
          {toolbar}
          <Upload {...uploadProps}>
            <PermissionButton permission="order.import" icon={<UploadOutlined />} loading={importing}>
              {t('common.import')}
            </PermissionButton>
          </Upload>
          <PermissionButton
            permission="order.export"
            type="primary"
            loading={exporting}
            onClick={() => void handleExport()}
          >
            {t('common.export')}
          </PermissionButton>
        </Space>
      }
    >
      <SearchForm
        fields={[
          { name: 'user_id', label: t('order.user_id') },
          { name: 'order_no', label: t('order.order_no') },
          {
            name: 'status',
            label: t('order.status'),
            type: 'select',
            options: statusOptions,
          },
          { name: 'min_amount', label: t('order.min_amount'), advanced: true },
          { name: 'max_amount', label: t('order.max_amount'), advanced: true },
          { name: 'start_time', label: t('order.start_time'), type: 'datetime', advanced: true },
          { name: 'end_time', label: t('order.end_time'), type: 'datetime', advanced: true },
        ]}
        values={searchForm}
        onChange={onSearchFormChange}
        onSearch={handleSearch}
        onReset={handleReset}
      />

      <Table<OrderRow>
        rowKey="id"
        loading={loading}
        columns={columns}
        dataSource={tableData}
        scroll={{ x: 1200 }}
        expandable={{
          expandedRowRender: (row) => (
            <div style={{ padding: '8px 12px' }}>
              <h4 style={{ margin: '0 0 8px' }}>{t('order.order_details')}</h4>
              <Table
                size="small"
                pagination={false}
                rowKey={(_, index) => String(index)}
                columns={detailColumns}
                dataSource={row.details || []}
              />
            </div>
          ),
        }}
        pagination={{
          current: pagination.page,
          pageSize: pagination.pageSize,
          total: pagination.total,
          showSizeChanger: true,
          showTotal: (total) => t('common.total', { total }),
        }}
        onChange={(pager: TablePaginationConfig, _filters, sorter) => {
          const sort = Array.isArray(sorter) ? sorter[0] : sorter
          if (sort?.field && sort.order) {
            handleSortChange(String(sort.field), sort.order)
            return
          }
          void loadData({
            currentPage: pager.current || 1,
            pageSize: pager.pageSize || pagination.pageSize,
          })
        }}
      />

      <OrderFormModal open={createOpen} onClose={() => setCreateOpen(false)} onSuccess={() => void refresh()} />

      <Modal
        open={editOpen}
        title={t('order.edit_order')}
        width={600}
        destroyOnHidden
        confirmLoading={editSubmitting}
        onCancel={closeEdit}
        onOk={() => void handleEditSubmit()}
        okText={t('common.confirm')}
        cancelText={t('common.cancel')}
      >
        <Form form={editForm} layout="vertical">
          <Form.Item
            name="status"
            label={t('order.status')}
            rules={[{ required: true, message: t('order.status_required') }]}
          >
            <Select placeholder={t('order.update_status_tip')} options={statusOptions} />
          </Form.Item>
          <Form.Item name="remark" label={t('order.remark')}>
            <Input.TextArea rows={4} placeholder={t('order.remark_placeholder')} />
          </Form.Item>
        </Form>
      </Modal>

      <Drawer open={detailOpen} title={t('order.detail')} width="80%" onClose={() => setDetailOpen(false)}>
        {orderInfo ? (
          <>
            <Descriptions column={2} bordered size="small">
              <Descriptions.Item label={t('order.order_no')}>
                {String(getOrderDetailField(orderInfo, 'order_no'))}
              </Descriptions.Item>
              <Descriptions.Item label={t('order.user_id')}>
                {String(getOrderDetailField(orderInfo, 'user_id'))}
              </Descriptions.Item>
              <Descriptions.Item label={t('order.amount')}>
                {formatOrderAmount(getOrderDetailField(orderInfo, 'amount', 0))}
              </Descriptions.Item>
              <Descriptions.Item label={t('order.status')}>
                <Tag color={getOrderStatusTagColor(String(getOrderDetailField(orderInfo, 'status', '')))}>
                  {getOrderStatusText(t, String(getOrderDetailField(orderInfo, 'status', '')))}
                </Tag>
              </Descriptions.Item>
              <Descriptions.Item label={t('order.created_at')}>
                {formatOrderTime(getOrderDetailField(orderInfo, 'created_at', ''))}
              </Descriptions.Item>
              <Descriptions.Item label={t('order.remark')}>
                {String(getOrderDetailField(orderInfo, 'remark') || '-')}
              </Descriptions.Item>
            </Descriptions>
            <Divider>{t('order.details')}</Divider>
            <Table
              size="small"
              pagination={false}
              rowKey={(_, index) => String(index)}
              columns={detailColumns}
              dataSource={orderDetail?.details || []}
            />
          </>
        ) : null}
      </Drawer>
    </PageContainer>
  )
}

// html/src/views/order/OrderList.vue
<template>
  <div class="list-page">
    <el-card>
      <template #header>
        <div class="card-header">
          <span>{{ $t('menu.order') }}</span>
          <el-button 
            type="primary" 
            :disabled="getButtonState('order.store').disabled"
            @click="handleAdd"
          >
            <el-icon><Plus /></el-icon>
            {{ $t('order.add_order') }}
          </el-button>
        </div>
      </template>

      <!-- 搜索表单 -->
      <SearchForm
        :model="searchForm"
        :fields="searchFields"
        :initial-values="initialSearchForm"
        i18n-prefix="order"
        @search="handleSearch"
        @reset="handleReset"
      >
        <template #user_id="{ model, field }">
          <el-input v-model="model[field.prop]" :placeholder="t('order.user_id')" />
        </template>
        <template #extra-buttons>
          <el-button 
            type="primary" 
            :disabled="getButtonState('order.import').disabled || isImporting"
            :loading="isImporting"
            @click="handleImport"
          >
            <el-icon><Upload /></el-icon>
            {{ $t('common.import') }}
          </el-button>
          <el-button 
            type="success" 
            :disabled="getButtonState('order.export').disabled || isExporting"
            :loading="isExporting"
            @click="handleExport"
          >
            {{ $t('common.export') }}
          </el-button>
        </template>
      </SearchForm>

      <!-- vxe-table with expand row -->
      <vxe-table
        ref="tableRef"
        :data="tableData"
        :loading="loading"
        border
        :column-config="{ resizable: true }"
        height="600"
        :sort-config="{ multiple: false, trigger: 'default' }"
        @sort-change="handleSortChange"
      >
        <!-- 展开行：显示订单详情 -->
        <vxe-column type="expand" width="60">
          <template #content="{ row }">
            <div class="order-details-expand">
              <h4 style="margin: 10px 0; font-weight: bold;">{{ t('order.order_details') }}</h4>
              <vxe-table
                :data="row.details || row.Details || []"
                border
                size="small"
                :show-header="true"
              >
                <vxe-column field="product_name" :title="t('order.product_name')" width="200">
                  <template #default="{ row: detail }">
                    {{ detail.product_name || detail.ProductName || '-' }}
                  </template>
                </vxe-column>
                <vxe-column field="price" :title="t('order.price')" width="120">
                  <template #default="{ row: detail }">
                    {{ formatAmount(detail.price || detail.Price) }}
                  </template>
                </vxe-column>
                <vxe-column field="quantity" :title="t('order.quantity')" width="100">
                  <template #default="{ row: detail }">
                    {{ detail.quantity || detail.Quantity || 0 }}
                  </template>
                </vxe-column>
                <vxe-column field="subtotal" :title="t('order.subtotal')" width="120">
                  <template #default="{ row: detail }">
                    {{ formatAmount(detail.subtotal || detail.Subtotal) }}
                  </template>
                </vxe-column>
              </vxe-table>
            </div>
          </template>
        </vxe-column>
        <template v-for="(column, index) in tableColumns" :key="column.field || column.slot || index">
          <vxe-column
            v-if="column.type"
            :type="column.type"
            :width="column.width"
            :fixed="column.fixed"
          />
          <vxe-column
            v-else
            :field="column.field"
            :title="column.title"
            :width="column.width"
            :sortable="column.sortable"
            :fixed="column.fixed"
            :formatter="column.formatter"
          >
            <template v-if="column.slot === 'status'" #default="{ row }">
              <el-tag :type="getStatusTagType(row.status || row.Status)">
                {{ getStatusText(row.status || row.Status) }}
              </el-tag>
            </template>
            <template v-else-if="column.slot === 'amount'" #default="{ row }">
              {{ formatAmount(row.amount || row.Amount) }}
            </template>
            <template v-else-if="column.slot === 'operation'" #default="{ row }">
              <TableActionButtons
                :row="row"
                :primary-actions="getPrimaryActions(row)"
                :get-button-state="getButtonState"
                @action="handleAction"
              />
            </template>
          </vxe-column>
        </template>
      </vxe-table>

      <Pagination
        v-model="pagination"
        :auto-load="true"
        :on-page-change="loadData"
        :hide-total-threshold="100000"
      />
    </el-card>

    <!-- 文件上传输入框（隐藏） -->
    <input
      ref="fileInputRef"
      type="file"
      accept=".csv"
      style="display: none"
      @change="handleFileChange"
    />

    <!-- 创建订单对话框 -->
    <OrderForm
      v-model="dialogVisible"
      @success="handleFormSuccess"
    />

    <!-- 编辑订单对话框 -->
    <el-dialog
      v-model="editDialogVisible"
      :title="$t('order.edit_order')"
      width="600px"
      :close-on-click-modal="false"
      @close="handleEditDialogClose"
    >
      <el-form
        ref="editFormRef"
        :model="editFormData"
        :rules="editFormRules"
        label-width="120px"
      >
        <el-form-item :label="$t('order.status')" prop="status">
          <el-select
            v-model="editFormData.status"
            :placeholder="$t('order.update_status_tip')"
            style="width: 100%"
          >
            <el-option
              :label="$t('order.status_pending')"
              value="pending"
            />
            <el-option
              :label="$t('order.status_paid')"
              value="paid"
            />
            <el-option
              :label="$t('order.status_cancelled')"
              value="cancelled"
            />
          </el-select>
        </el-form-item>
        <el-form-item :label="$t('order.remark')" prop="remark">
          <el-input
            v-model="editFormData.remark"
            type="textarea"
            :rows="4"
            :placeholder="$t('order.remark_placeholder')"
          />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="handleEditDialogClose">{{ $t('common.cancel') }}</el-button>
        <el-button type="primary" @click="handleEditSubmit" :loading="editSubmitting">
          {{ $t('common.confirm') }}
        </el-button>
      </template>
    </el-dialog>

    <!-- 订单详情对话框 -->
    <el-dialog
      v-model="detailDialogVisible"
      :title="$t('order.detail')"
      width="80%"
      :close-on-click-modal="false"
    >
      <div v-if="orderDetail" class="order-detail">
        <el-descriptions :column="2" border>
          <el-descriptions-item :label="$t('order.order_no')">
            {{ orderDetail.order?.order_no || orderDetail.order?.OrderNo }}
          </el-descriptions-item>
          <el-descriptions-item :label="$t('order.user_id')">
            {{ orderDetail.order?.user_id || orderDetail.order?.UserID }}
          </el-descriptions-item>
          <el-descriptions-item :label="$t('order.amount')">
            {{ formatAmount(orderDetail.order?.amount || orderDetail.order?.Amount) }}
          </el-descriptions-item>
          <el-descriptions-item :label="$t('order.status')">
            <el-tag :type="getStatusTagType(orderDetail.order?.status || orderDetail.order?.Status)">
              {{ getStatusText(orderDetail.order?.status || orderDetail.order?.Status) }}
            </el-tag>
          </el-descriptions-item>
          <el-descriptions-item :label="$t('order.created_at')">
            {{ formatTime(orderDetail.order?.created_at || orderDetail.order?.CreatedAt) }}
          </el-descriptions-item>
          <el-descriptions-item :label="$t('order.remark')">
            {{ orderDetail.order?.remark || orderDetail.order?.Remark || '-' }}
          </el-descriptions-item>
        </el-descriptions>

        <el-divider>{{ $t('order.details') }}</el-divider>

        <vxe-table
          :data="orderDetail.details || []"
          border
        >
          <vxe-column field="product_name" :title="$t('order.product_name')" />
          <vxe-column field="price" :title="$t('order.price')" :formatter="({ row }) => formatAmount(row.price || row.Price)" />
          <vxe-column field="quantity" :title="$t('order.quantity')" />
          <vxe-column field="subtotal" :title="$t('order.subtotal')" :formatter="({ row }) => formatAmount(row.subtotal || row.Subtotal)" />
        </vxe-table>
      </div>
    </el-dialog>
  </div>
</template>

<script setup>
import { ref, reactive, watch, onMounted, computed, nextTick } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Plus, Upload } from '@element-plus/icons-vue'
import SearchForm from '../../components/SearchForm.vue'
import Pagination from '../../components/Pagination.vue'
import TableActionButtons from '../../components/TableActionButtons.vue'
import OrderForm from './OrderForm.vue'
import { useListPage } from '../../composables/useListPage'
import { usePermission } from '../../composables/usePermission'
import { useCrud } from '../../composables/useCrud'
import { useAppStore } from '../../store/app'
import {
  getOrderList,
  getOrderDetail,
  updateOrder,
  deleteOrder,
  exportOrder,
  getExportStatus,
  importOrder
} from '../../api/order'
import logger from '../../utils/logger'
import ErrorHandler from '../../utils/errorHandler'
import { getSevenDaysAgo } from '../../utils/dateUtils'
import { validateTimeRange, ORDER_MAX_TIME_RANGE_MONTHS } from '../../utils/timeRangeValidator'

// 权限控制
const { getButtonState } = usePermission()
const appStore = useAppStore()
const isDark = computed(() => appStore.darkMode)

const { t } = useI18n()
const router = useRouter()
const tableRef = ref(null)
const isExporting = ref(false) // 导出中状态，防止重复点击
const isImporting = ref(false) // 导入中状态，防止重复点击
const fileInputRef = ref(null) // 文件输入框引用

// 使用 CRUD composable（只用于添加功能）
const {
  dialogVisible,
  editId,
  handleFormSuccess: handleFormSuccessCrud
} = useCrud()

// 订单详情对话框
const detailDialogVisible = ref(false)
const orderDetail = ref(null)

// 编辑订单对话框
const editDialogVisible = ref(false)
const editFormRef = ref(null)
const editSubmitting = ref(false)
const currentEditOrder = ref(null)
const editFormData = reactive({
  status: '',
  remark: ''
})

const editFormRules = computed(() => ({
  status: [
    { required: true, message: t('order.status_required'), trigger: 'change' }
  ]
}))

// 初始搜索表单数据（开始时间默认为一周前）
const initialSearchForm = {
  user_id: '',
  order_no: '',
  status: '',
  min_amount: null,
  max_amount: null,
  start_time: getSevenDaysAgo(),
  end_time: ''
}

// 使用列表页面 composable
const {
  pagination,
  tableData,
  loading,
  searchForm,
  loadData,
  handleSearch: handleSearchBase,
  handleReset,
  handleSortChange,
  initDefaultSort
} = useListPage({
  fetchApi: getOrderList,
  initialSearchForm,
  fieldMapping: {},
  defaultSort: 'created_at:desc',
  tableRef: computed(() => tableRef.value)
})

// 获取当前时间的字符串格式（YYYY-MM-DD HH:mm:ss）
const getCurrentTimeString = () => {
  const now = new Date()
  const year = now.getFullYear()
  const month = String(now.getMonth() + 1).padStart(2, '0')
  const day = String(now.getDate()).padStart(2, '0')
  const hours = String(now.getHours()).padStart(2, '0')
  const minutes = String(now.getMinutes()).padStart(2, '0')
  const seconds = String(now.getSeconds()).padStart(2, '0')
  return `${year}-${month}-${day} ${hours}:${minutes}:${seconds}`
}

// 验证时间范围的函数
const validateTimeRangeForSearch = () => {
  // 如果只填了开始时间，结束时间默认为当前时间
  if (searchForm.start_time) {
    const endTime = searchForm.end_time || getCurrentTimeString()
    const validation = validateTimeRange(searchForm.start_time, endTime, ORDER_MAX_TIME_RANGE_MONTHS)
    if (!validation.valid) {
      // 优先使用翻译键
      let errorMessage = validation.error
      if (validation.errorKey) {
        const translationKey = `order.${validation.errorKey}`
        if (validation.errorParams) {
          errorMessage = t(translationKey, validation.errorParams)
        } else {
          errorMessage = t(translationKey)
        }
      }
      ElMessage.warning(errorMessage)
      return false
    }
  }
  return true
}

// 监听开始时间和结束时间的变化，实时验证
const isInitialized = ref(false)
watch(
  () => [searchForm.start_time, searchForm.end_time],
  ([newStartTime, newEndTime], [oldStartTime, oldEndTime]) => {
    // 跳过初始化时的触发
    if (!isInitialized.value) {
      isInitialized.value = true
      return
    }
    
    // 只在开始时间或结束时间发生变化时验证
    if (newStartTime !== oldStartTime || newEndTime !== oldEndTime) {
      // 如果只填了开始时间，结束时间默认为当前时间
      if (newStartTime) {
        const endTime = newEndTime || getCurrentTimeString()
        const validation = validateTimeRange(newStartTime, endTime, ORDER_MAX_TIME_RANGE_MONTHS)
        if (!validation.valid) {
          // 优先使用翻译键
          let errorMessage = validation.error
          if (validation.errorKey) {
            const translationKey = `order.${validation.errorKey}`
            if (validation.errorParams) {
              errorMessage = t(translationKey, validation.errorParams)
            } else {
              errorMessage = t(translationKey)
            }
          }
          ElMessage.warning(errorMessage)
        }
      }
    }
  },
  { immediate: false }
)

// 包装搜索处理，添加时间范围验证
const handleSearch = () => {
  // 验证时间范围
  if (!validateTimeRangeForSearch()) {
    return
  }
  
  handleSearchBase()
}

// 表格列配置
const tableColumns = computed(() => [
  {
    field: 'id',
    title: t('table.id'),
    width: 80,
    sortable: true
  },
  {
    field: 'order_no',
    title: t('order.order_no'),
    sortable: false
  },
  {
    field: 'user_id',
    title: t('order.user_id'),
    width: 100,
    sortable: false
  },
  {
    field: 'amount',
    title: t('order.amount'),
    width: 120,
    sortable: true,
    slot: 'amount'
  },
  {
    field: 'status',
    title: t('order.status'),
    width: 100,
    sortable: false,
    slot: 'status'
  },
  {
    field: 'created_at',
    title: t('order.created_at'),
    width: 180,
    sortable: true
  },
  {
    field: 'remark',
    title: t('order.remark'),
    sortable: false,
    width: 200,
    formatter: ({ cellValue }) => {
      return cellValue || '-'
    }
  },
  {
    title: t('table.operation'),
    width: 220,
    fixed: 'right',
    slot: 'operation'
  }
])

// 搜索表单字段配置
const searchFields = computed(() => [
  {
    prop: 'user_id',
    label: t('order.user_id'),
    type: 'input',
    width: '150px',
    advanced: false
  },
  {
    prop: 'order_no',
    label: t('order.order_no'),
    type: 'input',
    width: '200px',
    advanced: false
  },
  {
    prop: 'status',
    label: t('order.status'),
    type: 'select',
    width: '150px',
    options: [
      { label: t('order.status_pending'), value: 'pending' },
      { label: t('order.status_paid'), value: 'paid' },
      { label: t('order.status_cancelled'), value: 'cancelled' }
    ],
    advanced: false
  },
  {
    prop: 'min_amount',
    label: t('order.min_amount'),
    type: 'number',
    width: '150px',
    advanced: true,
    min: 0,
    step: 0.01
  },
  {
    prop: 'max_amount',
    label: t('order.max_amount'),
    type: 'number',
    width: '150px',
    advanced: true,
    min: 0,
    step: 0.01
  },
  {
    prop: 'start_time',
    label: t('order.start_time'),
    type: 'datetime',
    width: '200px',
    advanced: true
  },
  {
    prop: 'end_time',
    label: t('order.end_time'),
    type: 'datetime',
    width: '200px',
    advanced: true
  }
])

// 格式化金额
const formatAmount = (amount) => {
  if (amount === null || amount === undefined) return '-'
  return `¥${Number(amount).toFixed(2)}`
}

// 格式化时间
const formatTime = (time) => {
  if (!time) return '-'
  return typeof time === 'string' ? time : new Date(time).toLocaleString('zh-CN')
}

// 获取状态文本
const getStatusText = (status) => {
  const statusMap = {
    'pending': t('order.status_pending'),
    'paid': t('order.status_paid'),
    'cancelled': t('order.status_cancelled')
  }
  return statusMap[status] || status || '-'
}

// 获取状态标签类型
const getStatusTagType = (status) => {
  const typeMap = {
    'pending': 'warning',
    'paid': 'success',
    'cancelled': 'danger'
  }
  return typeMap[status] || 'info'
}

// 查看详情
const handleView = async (row) => {
  try {
    // 优先使用订单号查询（更高效，可直接定位分表，避免分表中订单ID重复的问题）
    const orderNo = row.order_no || row.OrderNo
    const res = await getOrderDetail(row.id, orderNo ? { order_no: orderNo } : {})
    
    if (res.data) {
      orderDetail.value = res.data
      detailDialogVisible.value = true
    }
  } catch (error) {
    logger.error('View order detail error:', error)
    ErrorHandler.handle(error, { silent: true })
  }
}

// 编辑订单（打开编辑对话框）
const handleEdit = async (row) => {
  try {
    // 获取订单详情，优先使用订单号查询（更高效，可直接定位分表，避免分表中订单ID重复的问题）
    const orderNo = row.order_no || row.OrderNo
    const res = await getOrderDetail(row.id, orderNo ? { order_no: orderNo } : {})
    if (res.data && res.data.order) {
      currentEditOrder.value = res.data.order
      // 填充表单数据
      editFormData.status = res.data.order.status || res.data.order.Status || 'pending'
      editFormData.remark = res.data.order.remark || res.data.order.Remark || ''
      editDialogVisible.value = true
    }
  } catch (error) {
    logger.error('Get order detail for edit error:', error)
    ErrorHandler.handle(error, { silent: true })
  }
}

// 编辑对话框关闭
const handleEditDialogClose = () => {
  editDialogVisible.value = false
  currentEditOrder.value = null
  editFormData.status = ''
  editFormData.remark = ''
  editFormRef.value?.resetFields()
  editFormRef.value?.clearValidate()
}

// 提交编辑
const handleEditSubmit = async () => {
  if (!editFormRef.value) return
  
  try {
    await editFormRef.value.validate()
  } catch (error) {
    return
  }
  
  if (!currentEditOrder.value) return
  
  editSubmitting.value = true
  try {
    // 优先使用订单号更新（更高效，可直接定位分表，避免分表中订单ID重复的问题）
    const orderNo = currentEditOrder.value.order_no || currentEditOrder.value.OrderNo
    await updateOrder(currentEditOrder.value.id || currentEditOrder.value.ID, {
      status: editFormData.status,
      remark: editFormData.remark || '',
      order_no: orderNo
    })
    
    ElMessage.success(t('common.update_success'))
    handleEditDialogClose()
    loadData()
  } catch (error) {
    logger.error('Update order error:', error)
    ErrorHandler.handle(error, { silent: true })
  } finally {
    editSubmitting.value = false
  }
}

// 删除订单
const handleDelete = async (row) => {
  try {
    await ElMessageBox.confirm(
      t('common.delete_confirm'),
      t('form.tip'),
      {
        confirmButtonText: t('common.confirm'),
        cancelButtonText: t('common.cancel'),
        type: 'warning'
      }
    )
    
    // 优先使用订单号删除（更高效，可直接定位分表，避免分表中订单ID重复的问题）
    const orderNo = row.order_no || row.OrderNo
    await deleteOrder(row.id, orderNo ? { order_no: orderNo } : {})
    
    ElMessage.success(t('common.delete_success'))
    loadData()
  } catch (error) {
    if (error !== 'cancel') {
      logger.error('Delete order error:', error)
      ErrorHandler.handle(error, { silent: true })
    }
  }
}

// 获取主要操作按钮配置
const getPrimaryActions = (row) => {
  return [
    {
      key: 'view',
      label: t('common.view'),
      type: 'info',
      permission: 'order.show',
      handler: handleView
    },
    {
      key: 'edit',
      label: t('common.edit'),
      type: 'primary',
      permission: 'order.update',
      handler: handleEdit
    },
    {
      key: 'delete',
      label: t('common.delete'),
      type: 'danger',
      permission: 'order.destroy',
      handler: handleDelete
    }
  ]
}

// 处理操作事件
const handleAction = (command, row) => {
  switch (command) {
    case 'view':
      handleView(row)
      break
    case 'edit':
      handleEdit(row)
      break
    case 'delete':
      handleDelete(row)
      break
  }
}

// 导出订单（同步）
const handleExport = async () => {
  // 防止重复点击
  if (isExporting.value) {
    return
  }

  isExporting.value = true
  
  try {
    // 提交导出任务（同步执行）
    const response = await exportOrder(searchForm)
    const exportId = response.data?.export_id || response.data?.data?.export_id
    
    if (!exportId) {
      ElMessage.error(t('common.export_failed'))
      isExporting.value = false
      return
    }

    // 显示提交成功消息
    ElMessage.success(t('common.export_task_submitted') || response.data?.message)
    
    // 立即跳转到导出记录页面
    router.push('/exports')
    
  } catch (error) {
    logger.error('Export order error:', error)
    
    // 检查是否是重复提交错误
    if (error.response?.status === 429) {
      // 429 错误由业务代码处理，显示友好的提示
      ElMessage.warning(t('common.export_in_progress'))
    } else if (!error.__handled) {
      // 其他错误，如果未处理则显示
      ErrorHandler.handle(error, { silent: true })
    }
  } finally {
    // 无论成功还是失败，都要重置导出状态
    isExporting.value = false
  }
}

// 创建订单（打开创建对话框）
const handleAdd = () => {
  dialogVisible.value = true
}

// 导入订单
const handleImport = () => {
  // 触发文件选择
  if (fileInputRef.value) {
    fileInputRef.value.click()
  }
}

// 处理文件选择
const handleFileChange = async (event) => {
  const file = event.target.files?.[0]
  if (!file) {
    return
  }

  // 验证文件类型
  if (!file.name.toLowerCase().endsWith('.csv')) {
    ElMessage.error(t('common.invalid_file_type') || '文件类型错误，请上传CSV文件')
    // 清空文件选择
    if (fileInputRef.value) {
      fileInputRef.value.value = ''
    }
    return
  }

  // 防止重复点击
  if (isImporting.value) {
    return
  }

  isImporting.value = true

  try {
    const response = await importOrder(file)
    const result = response.data?.data || response.data

    // 显示导入结果
    if (result.success_count > 0) {
      ElMessage.success(
        t('common.import_success') || 
        `导入成功：成功 ${result.success_count} 条，失败 ${result.failed_count} 条`
      )
      
      // 如果有失败记录，显示详细信息
      if (result.failed_count > 0 && result.errors && result.errors.length > 0) {
        const errorMsg = result.errors.slice(0, 10).join('\n') // 最多显示10条错误
        if (result.errors.length > 10) {
          ElMessage.warning(`部分导入失败，前10条错误：\n${errorMsg}\n...`)
        } else {
          ElMessage.warning(`部分导入失败：\n${errorMsg}`)
        }
      }

      // 刷新列表
      await loadData()
    } else {
      ElMessage.warning(t('common.import_no_data') || '没有成功导入任何数据')
      if (result.errors && result.errors.length > 0) {
        const errorMsg = result.errors.slice(0, 10).join('\n')
        ElMessage.error(`导入失败：\n${errorMsg}`)
      }
    }
  } catch (error) {
    logger.error('Import order error:', error)
    if (!error.__handled) {
      ErrorHandler.handle(error, { silent: true })
    }
  } finally {
    isImporting.value = false
    // 清空文件选择
    if (fileInputRef.value) {
      fileInputRef.value.value = ''
    }
  }
}

// 表单提交成功回调
const handleFormSuccess = () => {
  handleFormSuccessCrud(loadData)
}

onMounted(async () => {
  try {
    await loadData()
    // 等待表格渲染完成后再初始化排序
    await nextTick()
    initDefaultSort()
  } catch (error) {
    logger.error('OrderList onMounted error:', error)
    ErrorHandler.handle(error)
  }
})
</script>

<style scoped>
.order-details-expand {
  padding: 15px;
  background-color: #f5f7fa;
}

.order-details-expand h4 {
  margin: 10px 0;
  font-weight: bold;
  color: #303133;
}


.order-detail {
  padding: 20px 0;
}
</style>
