// html/src/components/AttachmentImageField.vue
<template>
  <div class="attachment-image-field">
    <el-input
      :model-value="modelValue"
      :placeholder="placeholder || $t('config.site_logo_placeholder')"
      clearable
      @update:model-value="emitValue"
    >
      <template #append>
        <el-button @click="openPicker">
          <el-icon><Picture /></el-icon>
          {{ $t('common.select_from_attachment') }}
        </el-button>
      </template>
    </el-input>

    <div v-if="displayPreviewUrl" class="logo-preview">
      <el-image
        :src="displayPreviewUrl"
        :preview-src-list="[displayPreviewUrl]"
        fit="contain"
        class="logo-preview-image"
        :preview-teleported="true"
      >
        <template #error>
          <div class="logo-preview-error">
            <el-icon><Picture /></el-icon>
          </div>
        </template>
      </el-image>
    </div>

    <el-dialog
      v-model="pickerVisible"
      :title="$t('common.select_from_attachment')"
      width="780px"
      append-to-body
      destroy-on-close
      @opened="handlePickerOpened"
      @closed="handlePickerClosed"
    >
      <div class="picker-toolbar">
        <el-select
          v-model="categoryId"
          clearable
          :placeholder="$t('attachment.category')"
          style="width: 160px"
          @change="handleSearch"
        >
          <el-option
            v-for="opt in categoryOptions"
            :key="opt.value"
            :label="opt.label"
            :value="opt.value"
          />
        </el-select>
        <el-input
          v-model="keyword"
          clearable
          :placeholder="$t('attachment.search_name_placeholder')"
          style="width: 280px"
          @keyup.enter="handleSearch"
        />
        <el-button type="primary" @click="handleSearch">{{ $t('common.search') }}</el-button>
        <el-button @click="handleReset">{{ $t('common.reset') }}</el-button>
      </div>

      <div v-loading="loading" class="picker-grid">
        <div
          v-for="item in list"
          :key="item.id"
          class="picker-item"
          :class="{ active: selectedId === item.id }"
          @click="selectedId = item.id"
          @dblclick="confirmSelect(item)"
        >
          <el-image
            v-if="getImageUrl(item)"
            :src="getImageUrl(item)"
            fit="cover"
            class="picker-thumb"
            @load="handleImageLoad(item)"
            @error="handleImageError(item)"
          >
            <template #error>
              <div class="picker-thumb-error">
                <el-icon><Picture /></el-icon>
              </div>
            </template>
          </el-image>
          <div v-else class="picker-thumb-error">
            <el-icon v-if="getImageLoadingState(item) === 'loading'" class="is-loading"><Loading /></el-icon>
            <el-icon v-else><Picture /></el-icon>
          </div>
          <div class="picker-name" :title="getPickerNameTitle(item)">
            <div class="picker-name-main">{{ item.display_name || item.filename }}</div>
            <div v-if="item.display_name" class="picker-name-sub">{{ item.filename }}</div>
          </div>
        </div>
        <el-empty v-if="!loading && list.length === 0" :description="$t('common.no_data')" />
      </div>

      <div class="picker-pager">
        <el-pagination
          :current-page="page"
          :page-size="pageSize"
          :total="total"
          layout="total, prev, pager, next"
          @current-change="handlePageChange"
        />
      </div>

      <template #footer>
        <el-button @click="pickerVisible = false">{{ $t('common.cancel') }}</el-button>
        <el-button type="primary" :disabled="!selectedItem" @click="confirmSelect(selectedItem)">
          {{ $t('common.confirm') }}
        </el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { ref, computed, watch, nextTick, onBeforeUnmount } from 'vue'
import { Picture, Loading } from '@element-plus/icons-vue'
import { getAttachmentList } from '@/api/attachment'
import { transformAttachmentRow } from '@/views/attachment/attachment.config'
import { useAttachmentImagePreview } from '@/composables/useAttachmentImagePreview'
import { PUBLIC_IMAGE_PATH_RE, resolveImageDisplayUrl } from '@/utils/publicImage'
import { toStablePublicAttachmentUrl } from '@/utils/attachmentUrl'
import request from '@/utils/request'

const props = defineProps({
  modelValue: {
    type: String,
    default: ''
  },
  placeholder: {
    type: String,
    default: ''
  }
})

const emit = defineEmits(['update:modelValue', 'change'])

const pickerVisible = ref(false)
const loading = ref(false)
const list = ref([])
const keyword = ref('')
const categoryId = ref('')
const categoryOptions = ref([])
const page = ref(1)
const pageSize = ref(12)
const total = ref(0)
const selectedId = ref(null)
const displayPreviewUrl = ref('')
let revokePreviewUrl = null

const {
  loadImageAsBlob,
  getImageUrl,
  getImageLoadingState,
  handleImageLoad,
  handleImageError
} = useAttachmentImagePreview()

const selectedItem = computed(() => list.value.find((item) => item.id === selectedId.value) || null)

const toSubmitUrl = (url) => {
  const value = String(url || '').trim()
  if (!value) return ''
  if (value.startsWith('/')) return value
  if (value.startsWith('http')) {
    try {
      const parsed = new URL(value)
      if (PUBLIC_IMAGE_PATH_RE.test(parsed.pathname)) {
        return `${parsed.pathname}${parsed.search || ''}`
      }
      return value
    } catch {
      return value
    }
  }
  return value
}

const emitValue = (value) => {
  const finalValue = toSubmitUrl(value)
  emit('update:modelValue', finalValue)
  emit('change', finalValue)
}

const revokePreviewBlob = () => {
  if (typeof revokePreviewUrl === 'function') {
    revokePreviewUrl()
    revokePreviewUrl = null
  }
  displayPreviewUrl.value = ''
}

const loadPreview = async (raw) => {
  revokePreviewBlob()
  const value = String(raw || '').trim()
  if (!value) return

  const result = await resolveImageDisplayUrl(value)
  if (String(props.modelValue || '').trim() !== value) {
    if (typeof result.revoke === 'function') result.revoke()
    return
  }
  revokePreviewUrl = result.revoke || null
  displayPreviewUrl.value = result.url || ''
}

watch(
  () => props.modelValue,
  (val) => {
    loadPreview(val)
  },
  { immediate: true }
)

onBeforeUnmount(() => {
  revokePreviewBlob()
})

const ensureFileUrl = (item) => {
  if (!item) return ''
  if (item.file_url) return item.file_url
  if (item.id) return `/api/admin/public/images/${item.id}`
  return ''
}

/** 配置类长期引用：统一存公开预览路径，避免 S3 临时签名链过期 */
const toStablePublicUrl = (item) => toStablePublicAttachmentUrl(item)

const loadCategoryOptions = async () => {
  try {
    const res = await request({ url: '/options', method: 'get', params: { type: 'attachment_category' } })
    categoryOptions.value = res?.data?.options || []
  } catch {
    categoryOptions.value = []
  }
}

const loadList = async () => {
  loading.value = true
  try {
    const res = await getAttachmentList({
      page: page.value,
      page_size: pageSize.value,
      file_type: 'image',
      is_public: '1',
      keyword: keyword.value.trim() || undefined,
      category_id: categoryId.value || undefined
    })
    const rows = res?.data?.list || res?.data?.data || []
    list.value = rows.map((row) => {
      const item = transformAttachmentRow(row)
      item.file_url = ensureFileUrl(item)
      return item
    })
    total.value = Number(res?.data?.total || 0)
    await nextTick()
    list.value.forEach((item) => {
      if (item.file_type === 'image') {
        loadImageAsBlob(item)
      }
    })
  } catch {
    list.value = []
    total.value = 0
  } finally {
    loading.value = false
  }
}

const getPickerNameTitle = (item) => {
  if (!item) return ''
  if (item.display_name) return `${item.display_name}\n${item.filename}`
  return item.filename || ''
}

const openPicker = () => {
  selectedId.value = null
  pickerVisible.value = true
}

const handlePickerOpened = () => {
  page.value = 1
  loadCategoryOptions()
  loadList()
}

const handlePickerClosed = () => {
  list.value = []
  selectedId.value = null
}

const handleSearch = () => {
  page.value = 1
  selectedId.value = null
  loadList()
}

const handleReset = () => {
  keyword.value = ''
  categoryId.value = ''
  page.value = 1
  selectedId.value = null
  loadList()
}

const handlePageChange = (newPage) => {
  page.value = newPage
  selectedId.value = null
  loadList()
}

const confirmSelect = (item) => {
  if (!item) return
  const url = toSubmitUrl(toStablePublicUrl(item))
  emitValue(url)
  pickerVisible.value = false
}
</script>

<style scoped>
.attachment-image-field {
  width: 100%;
  max-width: 480px;
}

.logo-preview {
  margin-top: 12px;
}

.logo-preview-image {
  width: 120px;
  height: 120px;
  border: 1px solid var(--el-border-color);
  border-radius: 4px;
  background: var(--el-fill-color-lighter);
}

.logo-preview-error {
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  color: var(--el-text-color-placeholder);
  font-size: 28px;
}

.picker-toolbar {
  display: flex;
  gap: 8px;
  margin-bottom: 16px;
}

.picker-grid {
  min-height: 280px;
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 12px;
}

.picker-item {
  border: 2px solid transparent;
  border-radius: 6px;
  padding: 8px;
  cursor: pointer;
  background: var(--el-fill-color-lighter);
  transition: border-color 0.15s ease, box-shadow 0.15s ease;
}

.picker-item:hover {
  border-color: var(--el-color-primary-light-5);
}

.picker-item.active {
  border-color: var(--el-color-primary);
  box-shadow: 0 0 0 1px var(--el-color-primary-light-7);
}

.picker-thumb {
  width: 100%;
  height: 110px;
  border-radius: 4px;
  display: block;
}

.picker-thumb-error {
  width: 100%;
  height: 110px;
  display: flex;
  align-items: center;
  justify-content: center;
  color: var(--el-text-color-placeholder);
  background: var(--el-fill-color);
  border-radius: 4px;
  font-size: 28px;
}

.picker-name {
  margin-top: 6px;
  font-size: 12px;
  line-height: 1.4;
  color: var(--el-text-color-regular);
}

.picker-name-main {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.picker-name-sub {
  margin-top: 2px;
  font-size: 11px;
  color: var(--el-text-color-secondary);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.picker-pager {
  display: flex;
  justify-content: flex-end;
  margin-top: 16px;
}

:deep(.el-empty) {
  grid-column: 1 / -1;
}
</style>

// html-react/src/components/AttachmentImageField.tsx
import { useCallback, useEffect, useMemo, useState } from 'react'
import {
  Button,
  Empty,
  Image,
  Input,
  Modal,
  Pagination,
  Select,
  Space,
  Spin,
} from 'antd'
import { PictureOutlined } from '@ant-design/icons'
import { useTranslation } from 'react-i18next'
import { getAttachmentList } from '@/api/attachment'
import { useAttachmentImagePreview } from '@/hooks/useAttachmentImagePreview'
import { useOptions } from '@/hooks/useOptions'
import {
  transformAttachmentRow,
  type AttachmentRow,
} from '@/pages/attachment/attachment.config'
import { PUBLIC_IMAGE_PATH_RE, resolveImageDisplayUrl } from '@/utils/publicImage'
import { toStablePublicAttachmentUrl } from '@/utils/attachmentUrl'
import './AttachmentImageField.scss'

export interface AttachmentImageFieldProps {
  value?: string
  onChange?: (value: string) => void
  placeholder?: string
  disabled?: boolean
}

function toSubmitUrl(url: string) {
  const value = String(url || '').trim()
  if (!value) return ''
  if (value.startsWith('/')) return value
  if (value.startsWith('http')) {
    try {
      const parsed = new URL(value)
      if (PUBLIC_IMAGE_PATH_RE.test(parsed.pathname)) {
        return `${parsed.pathname}${parsed.search || ''}`
      }
      return value
    } catch {
      return value
    }
  }
  return value
}

function ensureFileUrl(item: AttachmentRow) {
  if (item.file_url) return item.file_url
  if (item.id) return `/api/admin/public/images/${item.id}`
  return ''
}

export default function AttachmentImageField({
  value = '',
  onChange,
  placeholder,
  disabled,
}: AttachmentImageFieldProps) {
  const { t } = useTranslation()
  const [pickerOpen, setPickerOpen] = useState(false)
  const [loading, setLoading] = useState(false)
  const [list, setList] = useState<AttachmentRow[]>([])
  const [keyword, setKeyword] = useState('')
  const [categoryId, setCategoryId] = useState<string | number | undefined>()
  const [page, setPage] = useState(1)
  const [pageSize] = useState(12)
  const [total, setTotal] = useState(0)
  const [selectedId, setSelectedId] = useState<string | number | null>(null)
  const [displayPreviewUrl, setDisplayPreviewUrl] = useState('')

  const { selectOptions: categoryOptions } = useOptions('attachment_category', pickerOpen)
  const { loadImageAsBlob, getImageUrl, getImageLoadingState } = useAttachmentImagePreview()

  const selectedItem = useMemo(
    () => list.find((item) => item.id === selectedId) || null,
    [list, selectedId],
  )

  const emitValue = useCallback(
    (next: string) => {
      onChange?.(toSubmitUrl(next))
    },
    [onChange],
  )

  useEffect(() => {
    let cancelled = false
    let revoke: (() => void) | undefined

    const run = async () => {
      setDisplayPreviewUrl('')
      const raw = String(value || '').trim()
      if (!raw) return
      const result = await resolveImageDisplayUrl(raw)
      if (cancelled) {
        result.revoke?.()
        return
      }
      revoke = result.revoke
      setDisplayPreviewUrl(result.url || '')
    }

    void run()
    return () => {
      cancelled = true
      revoke?.()
    }
  }, [value])

  const loadList = useCallback(
    async (overrides?: {
      page?: number
      keyword?: string
      categoryId?: string | number
    }) => {
      const nextPage = overrides?.page ?? page
      const nextKeyword = overrides?.keyword ?? keyword
      const nextCategoryId = overrides?.categoryId !== undefined ? overrides.categoryId : categoryId
      setLoading(true)
      try {
        const res = await getAttachmentList({
          page: nextPage,
          page_size: pageSize,
          file_type: 'image',
          is_public: '1',
          keyword: String(nextKeyword || '').trim() || undefined,
          category_id: nextCategoryId || undefined,
        })
        const rows = (res.data?.list || res.data?.data || []) as Array<Record<string, unknown>>
        const nextList = rows.map((row) => {
          const item = transformAttachmentRow(row)
          item.file_url = ensureFileUrl(item)
          return item
        })
        setList(nextList)
        setTotal(Number(res.data?.total || 0))
        nextList.forEach((item) => {
          if (item.file_type === 'image') void loadImageAsBlob(item)
        })
      } catch {
        setList([])
        setTotal(0)
      } finally {
        setLoading(false)
      }
    },
    [page, pageSize, keyword, categoryId, loadImageAsBlob],
  )

  useEffect(() => {
    if (!pickerOpen) return
    void loadList()
  }, [pickerOpen, page, categoryId, loadList])

  const handleSearch = () => {
    setSelectedId(null)
    if (page !== 1) {
      setPage(1)
      return
    }
    void loadList({ page: 1 })
  }

  const handleReset = () => {
    setKeyword('')
    setCategoryId(undefined)
    setSelectedId(null)
    setPage(1)
    void loadList({ page: 1, keyword: '', categoryId: undefined })
  }

  const confirmSelect = (item: AttachmentRow | null) => {
    if (!item) return
    const url = toSubmitUrl(
      toStablePublicAttachmentUrl({
        id: Number(item.id),
        is_public: item.is_public,
        file_url: item.file_url,
      }),
    )
    emitValue(url)
    setPickerOpen(false)
  }

  return (
    <div className="attachment-image-field">
      <Space.Compact style={{ width: '100%' }}>
        <Input
          value={value}
          disabled={disabled}
          placeholder={placeholder || t('config.site_logo_placeholder')}
          allowClear
          onChange={(e) => emitValue(e.target.value)}
        />
        <Button disabled={disabled} icon={<PictureOutlined />} onClick={() => setPickerOpen(true)}>
          {t('common.select_from_attachment')}
        </Button>
      </Space.Compact>

      {displayPreviewUrl ? (
        <div className="attachment-image-field__preview">
          <Image
            src={displayPreviewUrl}
            width={120}
            height={120}
            style={{ objectFit: 'contain' }}
            fallback=""
          />
        </div>
      ) : null}

      <Modal
        open={pickerOpen}
        title={t('common.select_from_attachment')}
        width={780}
        destroyOnHidden
        onCancel={() => setPickerOpen(false)}
        afterOpenChange={(open) => {
          if (open) {
            setSelectedId(null)
            setPage(1)
          } else {
            setList([])
            setSelectedId(null)
          }
        }}
        footer={[
          <Button key="cancel" onClick={() => setPickerOpen(false)}>
            {t('common.cancel')}
          </Button>,
          <Button
            key="ok"
            type="primary"
            disabled={!selectedItem}
            onClick={() => confirmSelect(selectedItem)}
          >
            {t('common.confirm')}
          </Button>,
        ]}
      >
        <div className="attachment-image-field__toolbar">
          <Select
            allowClear
            placeholder={t('attachment.category')}
            style={{ width: 160 }}
            value={categoryId}
            options={categoryOptions}
            onChange={(val) => {
              setCategoryId(val)
              setPage(1)
              setSelectedId(null)
            }}
          />
          <Input
            allowClear
            placeholder={t('attachment.search_name_placeholder')}
            style={{ width: 280 }}
            value={keyword}
            onChange={(e) => setKeyword(e.target.value)}
            onPressEnter={handleSearch}
          />
          <Button type="primary" onClick={handleSearch}>
            {t('common.search')}
          </Button>
          <Button onClick={handleReset}>{t('common.reset')}</Button>
        </div>

        <Spin spinning={loading}>
          <div className="attachment-image-field__grid">
            {list.map((item) => {
              const thumb = getImageUrl(item)
              const loadingState = getImageLoadingState(item)
              return (
                <div
                  key={String(item.id)}
                  className={`attachment-image-field__item${selectedId === item.id ? ' is-active' : ''}`}
                  onClick={() => setSelectedId(item.id)}
                  onDoubleClick={() => confirmSelect(item)}
                >
                  {thumb ? (
                    <img src={thumb} alt="" className="attachment-image-field__thumb" />
                  ) : (
                    <div className="attachment-image-field__thumb-empty">
                      {loadingState === 'loading' ? <Spin size="small" /> : <PictureOutlined />}
                    </div>
                  )}
                  <div
                    className="attachment-image-field__name"
                    title={
                      item.display_name
                        ? `${item.display_name}\n${item.filename || ''}`
                        : item.filename || ''
                    }
                  >
                    <div className="attachment-image-field__name-main">
                      {item.display_name || item.filename}
                    </div>
                    {item.display_name ? (
                      <div className="attachment-image-field__name-sub">{item.filename}</div>
                    ) : null}
                  </div>
                </div>
              )
            })}
            {!loading && list.length === 0 ? (
              <div className="attachment-image-field__empty">
                <Empty description={t('common.no_data')} />
              </div>
            ) : null}
          </div>
        </Spin>

        <div className="attachment-image-field__pager">
          <Pagination
            current={page}
            pageSize={pageSize}
            total={total}
            size="small"
            showSizeChanger={false}
            onChange={(next) => {
              setPage(next)
              setSelectedId(null)
            }}
          />
        </div>
      </Modal>
    </div>
  )
}
